<?php $this->dialog(); ?>
<?php $this->errorMsg(); ?>
<br />
<form name="busca" method="post" action="envia-consulta-por-protocolo" id="consulta-protocolo-horus">
    <input type="hidden" name="numProtocoloHidden" id="numProtocoloHidden" value="<?=$this->numProtocolo?>" />
    <label class="ui-corner-bl ui-corner-tr">Buscar(Num. Protocolo):</label>
    <input size="50" class="focus ui-state-default" name="num_protocolo" id="num_protocolo" value="" type="text" onkeypress='return SomenteNumero(event)'>
    <label class="ui-corner-bl ui-corner-tr">Cod. Produto Horus:</label>
    <input size="50" class="focus ui-state-default" name="num_produto" id="num_produto" value="" type="text">
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
</form>
<br />
<table>
    <?php if (count($this->dados) > 0) { ?>
            <tr>
                
                <td>
                    <a href="#" onclick="baixarXmls(<?=$this->numProtocolo?>)" >
                        <img src="<?=$this->baseUrl()?>/public/images/icons/requisicao_small.png" title="Baixar XMLS" />
                        <span style="float:left; margin-top: 12px; cursor: hand;">Gerar XMLS</span>
                    </a>
                </td>
            </tr>
    <?php } ?>
    <tr>
        <th>Código</th>
        <th>Tipo de Movimentação</th>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Data</th>
        <th>Data de Envio</th>
        <th>Núm. Protocolo</th>
        <th>Responsável</th>
        <?php /*<th>Opções</th>*/ ?>
    </tr>
    <?php if (count($this->dados) > 0) { ?>
        <?php foreach($this->dados as $value) { ?>
                <tr class="odd">
                    <td><?=$value->hor_dad_codigo?></td>
                    <td><?=$value->hor_dad_tpxml?></td>
                    <td><?=$value->hor_dad_nuproduto?></td>
                    <td><?=number_format($value->hor_dad_qtd,0,'.','')?></td>
                    <td><?=$this->data($value->hor_dad_dtcadastro,Zend_Date::DATE_MEDIUM)?></td>
                    <td><?=$this->data($value->hor_dad_dtenvio,Zend_Date::DATE_MEDIUM)?></td>
                    <td><?=$value->hor_dad_numprotocolo_envio?></td>
                    <td><?=$value->hor_dad_nome_respenvio?></td>
                    <?php/*<td>
                        <a href="" onclick="editaDados(<?=$value->hor_dad_codigo?>)">
                            Editar
                        </a>
                    </td>*/?>
                </tr>
        <?php } ?>
    <?php } else { ?>
            <tr>
                <td colspan="9">Nenhuma informação encontrada até o momento! Efetue uma busca!</td>
            </tr>
    <?php } ?>
</table> 

