<div class="msgAtencao" id="selecione-mes-exportacao">
    <p> Selecione a data para exportação dos dados pro HORUS.</p>
</div>

<div class="msgAtencao" id="aguarde-horus">
    <p> Aguarde enquanto as movimentações estão sendo exportadas para o Horus, este processo pode demorar alguns minutos.</p>
</div>
<div id="resultado-entrada">
<!-- Aqui vem o resultado pelo jQuery -->
</div>
<div id="resultado-saida">
<!-- Aqui vem o resultado pelo jQuery -->
</div>
<div id="resultado-dispensacao">
<!-- Aqui vem o resultado pelo jQuery -->
</div>