<br />
<label>Mês de exportação:</label>
<select class="ui-state-default" id="mes_exportacao_horus" name="mes_exportacao_horus" >
    <option value="01">Janeiro</option>
    <option value="02">Fevereiro</option>
    <option value="03">Março</option>
    <option value="04">Abril</option>
    <option value="05">Maio</option>
    <option value="06">Junho</option>
    <option value="07">Julho</option>
    <option value="08">Agosto</option>
    <option value="09">Setembro</option>
    <option value="10">Outubro</option>
    <option value="11">Novembro</option>
    <option value="12">Dezembro</option>
</select>
<br>
<br>
<label>Ano de exportação: </label>
<select class="ui-state-default" id="ano_exportacao_horus" name="ano_exportacao_horus" style="width: 90px">
    <option value="2016">2016</option>
    <option value="2017">2017</option>
    <option value="2018">2018</option>
    <option value="2019">2019</option>
    
</select>