<?php $this->dialog(); ?>
<?php $this->errorMsg(); ?>
<br />
<form name="busca" method="post" action="buscar-protocolo-por-data">
    <label class="ui-corner-bl ui-corner-tr">Buscar protocolo por data:</label>
    <input type="text" size="50" class="mask data"  rel="99/99/9999" name="data" value="" >
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
</form>
<br />
<table>
    <tr>
        <th>Data</th>
        <th>Número de Protocolo</th>
        <th>Tipo de Envio</th>
    </tr>
    <?php if (count($this->dados)>0) { ?>
        <?php foreach($this->dados as $item) { ?>
                <tr class="odd">
                    <td><?=$this->data($item->hor_dad_dtenvio,Zend_Date::DATE_MEDIUM)?></td>
                    <td><?=$item->hor_dad_numprotocolo_envio?></td>
                    <td><?=$item->hor_dad_tpxml?></td>
                </tr>
        <?php } ?>
    <?php } else { ?>
            <tr>
                <td colspan="3">Nenhuma informação encontrada até o momento! Efetue uma busca!</td>
            </tr>
    <?php } ?>
</table> 
