<form method="post">
	<input type="hidden" name="buscar" value="1" id="buscar" />
	<label>Unidade:</label>
	<?=$this->unidades;?><br />
	
	<label>Área:</label>
	<?=$this->areas;?><br />
	
	<label>Mês/Ano:</label>
	<input type="text" name="mes_ano" class="data-mes-ano" value="<?=$this->mes_ano;?>" /><br />	
	
	<a href="#" class="ui-button submit buscar">Buscar</a>
	<a href="#" class="ui-button novo">Adicionar</a>
</form>
<div class="space"></div>

<?php if($this->itens && $this->itens->count()):?>
<table class="grid ui-widget ui-widget-content ui-corner-all" width="100%">
	<tr class="ui-widget-header">
		<th>Unidade</th>
		<th>Área</th>
		<th>Mês/Ano</th>
		<th>Gerado em</th>
		<th>Gerado por</th>
		<th style="width: 80px">Opções</th>
	</tr>
	<?php foreach($this->itens as $item): ?>
	<tr>
		<td class="ui-widget-content"><?=$this->escape($item->uni_desc);?></td>
		<td class="ui-widget-content"><?=$this->escape($item->area_desc);?></td>
		<td class="ui-widget-content c"><?=$this->data($item->pma_mes, "MM/YYYY");?></td>
		<td class="ui-widget-content c"><?=$this->data($item->pma_data);?></td>
		<td class="ui-widget-content"><?=$this->escape($item->usr_nome);?></td>
		<td class="ui-widget-content c">
			<a href="<?=$this->url(array("module"=>"relatorio","controller"=>"pma2","action"=>"editar","pma"=>$item->pma_codigo), NULL, TRUE);?>">
				<img src="<?=$this->baseUrl("/public/images/icons/editar.png");?>" alt="Editar" title="Editar" />
			</a>
			<a href="<?=$this->url(array("module"=>"relatorio","controller"=>"pma2","action"=>"pma2","pma"=>$item->pma_codigo), NULL, TRUE);?>" target="_blank">
				<img src="<?=$this->baseUrl("/public/images/icons/imprimir.png");?>" alt="Imprimir" title="Imprimir" />
			</a>
			<a href="<?=$this->url(array("module"=>"relatorio","controller"=>"pma2","action"=>"apagar","pma"=>$item->pma_codigo), NULL, TRUE);?>" class="excluir">
				<img src="<?=$this->baseUrl("/public/images/icons/excluir2.png");?>" alt="Apagar" title="Apagar"  />
			</a>
			

		</td>
	</tr>
	<?php endforeach;?>
</table>
<?php else:?>
<em>Nenhum registro encontrado</em>
<?php endif; ?>
