<input id="usu_codigo" name="usu_codigo" value="<?= $this->usu_codigo; ?>" type="hidden" />
<input id="usr_codigo" name="usr_codigo" value="<?= $this->usr_codigo; ?>" type="hidden" />
<input type="hidden" name="age_codigo" id="age_codigo" value="<?=$this->age_codigo?>" />
<input type="hidden" name="age_codigo" id="esp_codigo" value="<?=$this->esp_codigo?>" />

<div id="page">
	<div id="header" >
                <div id="logo" style="margin: auto;">
                    <img width="100" height="100" src="<?= $this->baseUrl('/public/images/brasao.gif') ?>" title="Logo Prefeitura" />
		</div>
		<div id="titulo" style="text-align: left; ">
			<h2>Prefeitura Municipal de <?=$this->dadosSecretaria()->cidade;?></h2>
			<b>Secretaria Municipal de Saúde</b><br/>
                        <b><?=$this->dadosSecretaria()->endereco;?></b><br/>
                        <b><?echo date("d/m/Y")."   -   "; echo $this->usr_nome;?></b>
		</div>
		
                 <div id="logo" style="float: right; margin-top: 15px; text-align: right;">
			<img src="<?= $this->baseUrl('/public/images/logo_elotech.png') ?>" title="Logo Prefeitura" />
		</div>
		<div class="clear"></div>
               
	</div>
	<div id="info" style="border:1px solid;">
		<div id="foto" class="" style="float:left; margin-top: 10px; margin-right:15px;">
			<img src="<?= $this->baseUrl('/public/images/sem_foto_' . $this->dados->usu->usu_sexo . '.png') ?>" alt="Foto do Paciente" title="<?= $this->dados->usu->usu_nome; ?>" />
		</div>
		<h2><?=$this->dados->usu->usu_codigo?> - <?= ucwords(strtolower($this->dados->usu->usu_nome)); ?></h2>
		<div class="f" style="" >
                    <label>Sexo:</label> <span><?= $this->mask($this->dados->usu->usu_sexo, "sexo"); ?></span><br />
                    <label>Mãe:</label> <span><?= $this->dados->usu->usu_mae; ?></span><br />
                    <label>End.:</label> <font size="1"><span><?= $this->dados->usu->usu_endereco; ?></span></font><br />
                    <label>Profis.:</label> <span><?= $this->dados->usu->no_ocupacao; ?></span><br />		
		</div>
		<div class="f l2">
			<label>Data Nasc.:</label> <span><?= $this->data($this->dados->usu->usu_datanasc) . " (" . $this->idade($this->dados->usu->usu_datanasc) . ")"; ?></span><br />
			<label>Est. Civil:</label> <span><?= $this->dados->usu->estado_civil; ?></span><br />
			<label>Telefone:</label> <span><?= $this->mask($this->dados->usu->usu_fone); ?></span><br />
			<label>Cartão SUS:</label> <span><?= $this->dados->usu->usu_cartao_sus; ?></span>
		</div>
                <div id="barcode" style="float: right;" >
                    <img src="<?= $this->baseUrl() ?>/public/images/codigo_barras.php?codigo=<?= $this->age_codigo; ?>&lw=1&hi=18&cl=238" alt="Código de Barras: <?= $this->dados->usu->usu_codigo; ?>" title="Código de Barras: <?= $this->dados->usu->usu_codigo; ?>" />
                </div><br/>
		<div class="clear"></div>
		<div class="space"></div>
	</div>
	<div id="relatorio">
		<?php if ($this->dados->alertas): ?>
            <form>
                <br/><label>Data do atendimento: </label>&nbsp;<input type="text" name="data_consulta" id="data_consulta" value="<?=  date("d/m/Y")?>" class="data" style="width:90px;">
            </form>
			<div class="alerta">
				<h2><img src="<?= $this->baseUrl("/public/images/icons/add.png"); ?>" alt="Adicionar" title="Adicionar" class="a add" data-tipo="alerta" /> Alertas</h2>
                                <form method="post" action="<?= $this->url(array("controller" => "alerta", "action" => "salvar")); ?> " id="form-alerta">
                                        <input type="hidden" name="ale_data"  class="data_retroativa" value="<?=$this->data($this->age_data);?>" />
                                        <input id="usu_codigo" name="usu_codigo" value="<?= $this->usu_codigo; ?>" type="hidden" />
                                        <input id="usr_codigo" name="usr_codigo" value="<?= $this->usr_codigo; ?>" type="hidden" />
                                        <input type="hidden" name="json" value="1" />
                                        <?php $this->errorMsg(); ?>
                                        <label>Alerta:</label>
                                        <input type="text" name="ale_desc" value="<?= $this->escape($this->dados->ale_desc); ?>" class="focus"/><br />

                                        <div class="space"></div>

                                        <a href="#" class="ui-button salvar">Salvar</a>
                                        <a href="#" class="ui-button limpar">Limpar</a>
                                </form>
                                <table id="table-alerta">
				<?php if ($this->dados->alertas->count()): ?>
                                        
                                    <tr class="titulo"><th colspan="2">Alerta</th></tr>
					<?php foreach ($this->dados->alertas as $item): ?>
                                                <tr class="line_<?=$item->ale_codigo;?> linha_registro_ale">
                                                    <td width="30"><?/*<img src="<?= $this->baseUrl("/public/images/icons/excluir.png"); ?>" alt="Excluir" title="Excluir" onclick="alertaExcluir(<?php echo $item->ale_codigo; ?>)" />*/?></td>
                                                    <td><?=$item->ale_desc;?></td>
                                                    
                                                </tr>
						<?/*<span id="ale_<?php echo $item->ale_codigo; ?>"><img src="<?= $this->baseUrl("/public/images/icons/excluir.png"); ?>" alt="Excluir" title="Excluir" onclick="alertaExcluir(<?php echo $item->ale_codigo; ?>)" /> <?php echo $item->ale_desc; ?><br /></span>*/?>
					<?php endforeach; ?>
				<?php else: ?>
                                    <em class="em-alerta">Nenhum alerta cadastrado.</em>
				<?php endif; ?>
                                </table>
				<div class="space"></div>
			</div>
		<?php endif; ?>

		<?php if ($this->dados->pre_consultas): ?>
			<div class="pre-consulta">
				<h2><img src="<?= $this->baseUrl("/public/images/icons/add.png"); ?>" alt="Adicionar" title="Adicionar" class="a add" data-tipo="pre-consulta" /> Pré-Consultas</h2>
				<form method="post" action="<?= $this->url(array("controller" => "pre-consulta", "action" => "salvar")); ?>" id="form-pc">
                                        <input type="hidden" name="pc_data"  class="data_retroativa" value="<?=$this->data($this->age_data);?>" />
                                        <input type="hidden" name="age_codigo" id="age_codigo" value="<?=$this->age_codigo?>" />
					<input type="hidden" name="pc_codigo" value="<?= $this->dados->pc_codigo; ?>" />
                                        <input id="usr_codigo" name="usr_codigo" value="<?= $this->usr_codigo; ?>" type="hidden" />
					<input type="hidden" name="json" value="1" />
					<?php $this->errorMsg(); ?>
					<label>Temperatura <small>(ºC)</small>:</label>
					<input type="text" name="temperatura" value="<?= $this->escape($this->dados->pc_temperatura); ?>" class="float focus" rel="2,1" /><br />

					<label>Peso <small>(Kg)</small>:</label>
					<input type="text" name="peso" value="<?= $this->escape($this->dados->pc_peso); ?>" class="float" rel="3,2" /><br />

					<label>Altura <small>(m)</small>:</label>
					<input type="text" name="altura" value="<?= $this->escape($this->dados->pc_altura); ?>" class="float" rel="1,2" /><br />

					<label>Pressão Sistólica <small>(mm/Hg)</small>:</label>
					<input type="text" name="pressao_sistolica" value="<?= $this->escape($this->dados->pc_pressao_sistolica); ?>" /><br />

					<label>Pressão Diastólica <small>(mm/Hg)</small>:</label>
					<input type="text" name="pressao_diastolica" value="<?= $this->escape($this->dados->pc_pressao_diastolica); ?>" /><br />

					<label>Freq. Cardíaca <small>(BPM)</small>:</label>
					<input type="text" name="freq_cardiaca" value="<?= $this->escape($this->dados->pc_freq_cardiaca); ?>" /><br />

					<label>Freq. Respiratória <small>(MPM)</small>:</label>
					<input type="text" name="freq_respiratoria" value="<?= $this->escape($this->dados->pc_freq_respiratoria); ?>" /><br />

					<label>Perímetro Cefálico <small>(cm)</small>:</label>
					<input type="text" name="p_cefalico" value="<?= $this->escape($this->dados->pc_perimetro_cefalico); ?>" class="float" rel="2,2" /><br />

					<label>Outras informações:</label>
					<div class="textarea">
						<textarea name="obs" class="tinymce"><?= $this->escape($this->dados->pc_dados); ?></textarea>

					</div>
					<div class="space"></div>
					<div class="clear"></div>

					<a href="#" class="ui-button salvar">Salvar</a>
					<a href="#" class="ui-button limpar">Limpar</a>
					<div class="clear"></div>
				</form>

                                <table id="table-pc">
				<?php if ($this->dados->pre_consultas->count()): ?>
                                                <tr class="titulo_pc">
                                                    <th></th>
                                                    <th>Data</th>
                                                    <th>Unidade De Saúde</th>
                                                    <th>Profissional</th>
                                                    <th>Temp.</th>
                                                    <th>Peso</th>
                                                    <th>Alt.</th>
                                                    <th>P/A</th>
                                                    <th>IMC</th>
                                                </tr>
						<?php foreach ($this->dados->pre_consultas as $item): ?>
							
							<tr class="line_pc_<?=$item->pc_codigo?> linha_registro_pc">
                                                            <td width="30"><?/*<img src="<?= $this->baseUrl("/public/images/icons/excluir.png"); ?>" alt="Excluir" title="Excluir" onclick="pcExcluir(<?=$item->pc_codigo?>)" />*/?></td>
                                                            <td><?= $this->data($item->pc_data); ?></td>
                                                            <td nowrap><?= $this->escape($item->uni_desc); ?></td>
                                                            <td><?= $this->escape($item->usr_nome); ?></td>
                                                            <td><?= ($item->pc_temperatura ? number_format($item->pc_temperatura, 1, ",", ".") . "º" : "--"); ?></td>
                                                            <td><?= $this->mask($item->pc_peso, "empty", "--"); ?></td>
                                                            <td><?= $this->mask($item->pc_altura, "empty", "--"); ?></td>
                                                            <td><?= $this->mask($item->pc_pressao_sistolica, "empty", "--") . "/" . $this->mask($item->pc_pressao_diastolica, "empty", "--"); ?></td>
                                                            <td><?= $this->imc($item->pc_peso, $item->pc_altura); ?></td>
							</tr>
							<?php if ($item->pc_dados): ?>
								<tr>
									<td colspan="9" class="escape">
										<strong>Observações:</strong> <?= $item->pc_dados; ?>
									</td>
								</tr>
							<?php endif; ?>
						<?php endforeach; ?>
					
				<?php else: ?>
					<em class="em-pc">Nenhuma consulta encontrada.</em>
				<?php endif; ?>
                                </table>
			</div>
		<?php endif; ?>

		<?php if ($this->dados->atendimentos): ?>
			<div class="atendimento">
				<h2><img src="<?= $this->baseUrl("/public/images/icons/add.png"); ?>" alt="Adicionar" title="Adicionar" class="a add" data-tipo="atendimento" /> Consultas</h2>
				<form method="post" action="<?= $this->url(array("controller" => "atendimento", "action" => "salvar")); ?>" style="float: left" id="form-ate">
                                        <input type="hidden" name="age_codigo" id="age_codigo" value="<?=$this->age_codigo?>" />
                                        <input type="hidden" name="ate_data"  class="data_retroativa" value="<?=$this->data($this->age_data);?>" />
					<input type="hidden" name="json" value="1" />
					<label>Evolução:</label>
					<div class="textarea">
						<textarea name="ate_reclamacao" class="tinymce" style="width: 780px;height: 180px;">
							<?= $this->escape($this->dadosAte->ate_reclamacao); ?>
							<?= $this->escape($this->dadosAte->ate_exame_fisico); ?>
							<?= $this->escape($this->dadosAte->ate_diagnostico); ?>
							<?= $this->escape($this->dadosAte->ate_tratamento); ?>
							<?= $this->escape($this->dadosAte->ate_curativo); ?>
						</textarea>
					</div><br />

					<label>Acidente de trabalho?:</label>
					<?= $this->arrayToRadio("ate_acidentetrab", array('S' => "Sim", 'N' => "Não"), is_null($this->dadosAte->ate_acidentetrab) ? 'N' : $this->dadosAte->ate_acidentetrab); ?><br />

					<label><abbr title="Código Internacional de Doença">CID</abbr>:</label>
					<input type="hidden" name="cd10_codigo" id="cd10_codigo" value="<?= $this->dadosAte->cd10_codigo; ?>" />
					<input id="cd10_descricao" value="<?= trim($this->dadosAte->cd10_descricao); ?>" /><br />


					<div class="clear"></div>	
					<div class="space"></div>	
					<a href="#" class="ui-button salvar">Salvar</a>
					<a href="#" class="ui-button limpar">Limpar</a>

				</form>
                                <table id="table-ate">
				<?php if ($this->dados->atendimentos->count()): ?>
                                            <tr class="titulo_ate">
                                                <th></th>
                                                <th>Data</th>
                                                <th>Unidade De Saúde</th>
                                                <th>Profissional</th>
                                                <th>Especialidade</th>
                                            </tr>
						<?php foreach ($this->dados->atendimentos as $item): ?>
							<tr class="linha_registro">
                                                            <td width="30"><?/*<img src="<?= $this->baseUrl("/public/images/icons/excluir.png"); ?>" alt="Excluir" title="Excluir" onclick="pcExcluir(<?=$item->ate_codigo?>)" />*/?></td>
                                                            <td><?= $this->data($item->ate_data); ?></td>
                                                            <td><?= $this->escape($item->uni_desc); ?></td>
                                                            <td><?= $this->escape($item->usr_nome); ?></td>
                                                            <td><?= $this->escape($item->esp_nome); ?></td>
							</tr>
							<tr>
								<td colspan="8"><strong>CID</strong> <?= ($item->cd10_codigo_cid ? $this->escape($item->cd10_codigo_cid . " - " . $item->cd10_descricao) : "<em>Não informado</em>"); ?></td>
							</tr>
							<tr>
								<td colspan="8" class="escape">
									<?= $item->ate_reclamacao; ?>
									<?= $item->ate_exame_fisico; ?>
									<?= $item->ate_diagnostico; ?>
									<?= $item->ate_tratamento; ?>
									<?= $item->ate_curativo; ?>
								</td>
							</tr>
						<?php endforeach; ?>
				<?php else: ?>
					<em class="em-ate">Nenhuma consulta encontrada.</em>
				<?php endif; ?>
                            </table>
			</div>
		<?php endif; ?>

		<?php if ($this->dados->exames): ?>
			<h2>Exames</h2>
			<?php if ($this->dados->exames->count()): ?>
				<table>
					<tr>
						<th>Procedimento</th>
						<th>Profissional</th>
						<th>Prestador</th>
						<th>Data de Coleta</th>
					</tr>
					<?php foreach ($this->dados->exames as $item): ?>
						<tr>
							<td><?= $item->proc_nome; ?></td>
							<td><?= $item->usr_nome; ?></td>
							<td><?= $item->lab_nome; ?></td>
							<td><?= $this->data($item->mlz_datadacoleta); ?></td>
						</tr>
					<?php endforeach; ?>
				</table>
			<?php else: ?>
				<em>Nenhum exame encontrado.</em>
			<?php endif; ?>
		<?php endif; ?>

		<?php if ($this->dados->procedimentos): ?>
			<div class="procedimentos">
				<h2><img src="<?= $this->baseUrl("/public/images/icons/add.png"); ?>" alt="Adicionar" title="Adicionar" class="a add" data-tipo="procedimentos" /> Procedimentos</h2>
				<form method="post" action="<?= $this->url(array("controller" => "procedimento", "action" => "salvar")); ?>" id="form-proc">
                                    <input type="hidden" name="json" value="1" />
                                    <input type="hidden" name="ate_codigo" id="ate_codigo" class="ate_codigo" value="" />
                                    <?php $this->errorMsg(); ?>	
                                    <label>Procedimento:</label>
                                    <input type="hidden" id="proc_codigo" name="proc_codigo" value="" />
                                    <input type="text" id="proc_nome" name="proc_nome" value="" /><br />

                                    <label><abbr title="Código Internacional de Doença">CID</abbr>:</label>
                                            <select name="cd10_codigo" id="cid" disabled="disabled">
                                                    <option value="0">-- Selecione um procedimento --</option>
                                            </select><br />


                                    <div class="space"></div>
                                    <a href="#" class="ui-button salvar">Salvar</a>	
				</form>
                                <table id="table-proc">
				<?php if ($this->dados->procedimentos->count()): ?>
                                        <tr class="titulo_proc">
                                                <!--<th>Data</th>-->
                                                <th>&nbsp;</th>
                                                <th>Procedimento</th>
                                                <th>CID</th>
                                                <th>Profissional</th>
                                                <th>Especialidade</th>
                                        </tr>
                                            <?php foreach ($this->dados->procedimentos as $item): ?>
                                                    <tr id="pat_<?=$item->pat_codigo;?>" class="line_proc_<?=$item->pat_codigo;?> linha_registro_proc">
                                                            <?php if($item->ate_codigo == $this->dadosAte->ate_codigo):?>
                                                            <td><?/*<img class="a" onclick="procExcluir(<?=$item->pat_codigo;?>)" src="<?=$this->baseUrl("/public/images/icons/excluir.png");?>" alt="Excluir" title="Excluir" />*/?></td>
                                                            <?php else: ?>
                                                            <?php endif;?>
                                                            <!--<td><?//= $this->data($item->ate_data); ?></td>-->
                                                            <td><?= $item->proc_nome; ?></td>
                                                            <td><?= $this->mask($item->cd10_descricao, "empty", "--"); ?></td>
                                                            <td><?= $item->usr_nome; ?></td>
                                                            <td><?= $item->esp_nome; ?></td>
                                                    </tr>
                                            <?php endforeach; ?>
					
				<?php else: ?>
					<em class="em-proc">Nenhum procedimento registrado.</em>
				<?php endif; ?>
                                </table>
			</div>
		<?php endif; ?>

		<?php if ($this->dados->medicamentos): ?>
			<h2><img src="<?= $this->baseUrl("/public/images/icons/add.png"); ?>" alt="Adicionar" title="Adicionar" class="a add" data-tipo="medicamentos" />  Receitas</h2>
                       <form method="post" action="<?= $this->url(array("controller" => "receita-medica", "action" => "salvar")); ?>" id="form-rec">
                            <input type="hidden" name="json" value="1" />
                            <input type="hidden" name="rec_tipo" value="ficha">
                            <input type="hidden" name="ate_codigo" id="ate_codigo" class="ate_codigo" value="" />
                            <input type="hidden" name="rec_data"  class="data_retroativa" value="<?=$this->data($this->age_data);?>" />
                            <?php $this->errorMsg(); ?>	
                            <label>Medicamento:</label>
                            <input type="hidden" id="pro_codigo" name="pro_codigo" value="" />
                            <input type="text" id="pro_nome" name="pro_nome" value="" rel="medicamento"/><br />
                            <label>Quantidade:</label>
                            <input name="irec_quantidade" id="quantidade-medicamento" value="" style="width: 40px" /><br />
                            <label>Recomendação Médica:</label>
                            <div class="textarea">
                                    <textarea name="irec_recomendacao" class="tinymce"></textarea>
                            </div><br />
                            <div class="space"></div>
                            <a href="#" class="ui-button salvar">Salvar</a>	
                        </form>
			<table id="table-rec">
				
                            <?php if($this->medicamentos && $this->medicamentos->count()):?>
                            <thead>
                                <tr class="titulo_rec">
                                    <th width="20">&nbsp;</th>
                                    <th width="140">Data</th>
                                    <th>Produto</th>
                                    <th width="60">Quant.</th>
                                    <th>Recomendação</th>
                                </tr>
                            </thead>
                            <tbody>
                                    <?php foreach($this->medicamentos as $item):?>
                                    <tr class="linha_registro_rec">
                                        <td><?/*<img class="a" onclick="irecExcluir(<?=$item->irec_codigo;?>)" src="<?=$this->baseUrl("/public/images/icons/excluir.png");?>" alt="Excluir" title="Excluir" />*/?></td>
                                        <td><?=$this->data($item->rec_data);?></td>
                                        <td><?=$this->escape($item->pro_nome);?></td>
                                        <td class="d"><?=$this->escape($item->irec_quantidade);?></td>
                                        <td class="escape"><?=$item->irec_recomendacao;?></td>
                                    </tr>
                                    <?php endforeach; ?>
                                    <?php endif ;?>
                            </tbody>
                            <em class="em-rec">Nenhum item registrado.</em>
			</table>
			<div class="space"></div>
			
			
		<?php endif; ?>

		<?php if ($this->dados->vacinas): ?>
			<h2>Vacinas</h2>
			<?php if ($this->dados->vacinas->count()): ?>
				<table>
					<tr>
						<th>Data</th>
						<th>Unidade</th>
						<th>Vacina</th>
						<th>Lote</th>
						<th>Dose</th>
					</tr>
					<?php foreach ($this->dados->vacinas as $item): ?>
						<tr>
                                                    <td><?= $this->data($item->vac_data); ?></td>
                                                    <td><?= $item->uni_desc; ?></td>
                                                    <td><?= $item->pro_nome; ?></td>
                                                    <td><?= $item->ite_lote; ?></td>
                                                    <td><?= ($item->vac_dose < 6 ? $item->vac_dose . "&ordf; dose" : "Reforço"); ?></td>
						</tr>
					<?php endforeach; ?>
				</table>
			<?php else: ?>
				<em>Nenhuma vacina aplicada/preenchida.</em>
			<?php endif; ?>
		<?php endif; ?>

		<?php if ($this->dados->vacinasAprazadas): ?>
			<h2>Vacinas - Aprazadas</h2>
			<?php if ($this->dados->vacinasAprazadas->count()): ?>
				<table>
					<tr>
                                            <th>Data</th>
                                            <th>Unidade</th>
                                            <th>Vacina</th>
                                            <th>Dose</th>
					</tr>
					<?php foreach ($this->dados->vacinasAprazadas as $item): ?>
						<tr>
                                                    <td><?= $this->data($item->vac_data); ?></td>
                                                    <td><?= $item->uni_desc; ?></td>
                                                    <td><?= $item->pro_nome; ?></td>
                                                    <td><?= ($item->vac_dose < 6 ? $item->vac_dose . "&ordf; dose" : "Reforço"); ?></td>
						</tr>
					<?php endforeach; ?>
				</table>
			<?php else: ?>
				<em>Nenhuma vacina aprazada.</em>
			<?php endif; ?>
		<?php endif; ?>

	</div>
	<div class="clear"></div>
        <a href='#'class="ui-button finalizar">Finalizar Atendimento</a>
	<div id="footer">
		<span><?= $this->dadosSecretaria()->endereco; ?></span>
	</div>
</div>