<script type="text/javascript">
    window.print()
</script>
<html>
    <head>
        <title>Teste</title>
        <style type="text/css">
            <!--
            body { font-family: Arial; font-size: 11.6px }
            .pos { position: absolute; z-index: 0; left: 0px; top: 0px }
            -->
        </style>
    </head>
    <body>
    <nobr><nowrap>
            <div class="pos" id="_0:0" style="top:0">
                <img name="_1170:827" src="/WebSocialSaude/zf/public/images/prontuario/ficha/img_internacao_hospitalar.jpg" height="1170" width="827" border="0" usemap="#Map"></div>
            <div class="pos" id="_145:57" style="top:57;left:145">
                <span id="_11.0" style="font-weight:bold; font-family:Arial; font-size:11.0px; color:#000000">
                    Sistema</span>
            </div>
            <div class="pos" id="_204:57" style="top:57;left:204">
                <span id="_11.0" style="font-weight:bold; font-family:Arial; font-size:11.0px; color:#000000">
                    Minist&#233;rio</span>
            </div>
            <div class="pos" id="_145:70" style="top:70;left:145">
                <span id="_11.0" style="font-weight:bold; font-family:Arial; font-size:11.0px; color:#000000">
                    &#218;nico de</span>
            </div>
            <div class="pos" id="_352:59" style="top:59;left:352">
                <span id="_14.7" style="font-weight:bold;font-style:italic; font-family:Arial; font-size:14.7px; color:#000000">
                    LAUDO PARA SOLICITAÇÃO DE AUTORIZAÇÃO</span>
            </div>
            <div class="pos" id="_145:84" style="top:84;left:145">
                <span id="_11.0" style="font-weight:bold; font-family:Arial; font-size:11.0px; color:#000000">
                    Saúde
                </span>
            </div>
            <div class="pos" id="_204:84" style="top:70;left:204">
                <span id="_11.0" style="font-weight:bold; font-family:Arial; font-size:11.0px; color:#000000">
                    da</span>
            </div>
            <div class="pos" id="_204:84" style="top:84;left:204">
                <span id="_11.0" style="font-weight:bold; font-family:Arial; font-size:11.0px; color:#000000">
                    Saúde
                </span>
            </div>
            <div class="pos" id="_412:77" style="top:77;left:412">
                <span id="_14.7" style="font-weight:bold;font-style:italic; font-family:Arial; font-size:14.7px; color:#000000">
                    DE INTERNA&#199;&#195;O HOSPITALAR</span>
            </div>
            <div class="pos" id="_80:106" style="top:106;left:80">
                <span id="_12.6" style="font-weight:bold; font-family:Arial; font-size:11px; color:#000000">
                    Identificação do Estabelecimento de Saúde</span>
            </div>
            <div class="pos" id="_91:119" style="top:121;left:91">
                <span id="_8" style=" font-family:Arial; font-size:8px; color:#000000">
                    1 - NOME DO ESTABELECIMENTO SOLICITANTE
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->uni_desc?>
                </span>
            </div>
            <div class="pos" id="_646:119" style="top:121;left:648">
                <span id="_8" style=" font-family:Arial; font-size:8px; color:#000000">
                    2 - CNES
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->uni_cnes?>
                </span>
            </div>
            <div class="pos" id="_91:151" style="top:154;left:91">
                <span id="_8" style=" font-family:Arial; font-size:8px; color:#000000">
                    3 - NOME DO ESTABELECIMENTO EXECUTANTE
                </span>
            </div>
            <div class="pos" id="_646:151" style="top:153;left:648">
                <span id="_8" style=" font-family:Arial; font-size:8px; color:#000000">
                    4 - CNES
                </span>
            </div>
            <div class="pos" id="_80:186" style="top:189;left:82">
                <span id="_12.6" style="font-weight:bold; font-family:Arial; font-size:11px; color:#000000">
                    Identificação do Paciente
                </span>
            </div>
            <div class="pos" id="_91:200" style="top:203;left:93">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    5 - NOME DO PACIENTE
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->usu_nome?>
                </span>
            </div>
            <div class="pos" id="_669:200" style="top:203;left:671">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    6 - N&#186; DO PRONTU&#193;RIO
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->usu_prontuario?>
                </span>
            </div>
            <div class="pos" id="_91:233" style="top:236;left:93">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    7 - CARTÃO NACIONAL DE SAÚDE (CNS)
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->usu_cartao_sus?>
                </span>
            </div>
            <div class="pos" id="_455:232" style="top:235;left:457">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    8 - DATA DE NASCIMENTO
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->data($this->dados->usu_datanasc,Zend_Date::DATE_MEDIUM)?>
                </span>
            </div>
            <div class="pos" id="_667:233" style="top:236;left:669">
                <span id="_8.1" style=" font-family:Arial; font-size:8px; color:#000000">
                    9 - SEXO
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <? if($this->dados->usu_sexo == "M") { echo "Masculino"; }?>
                    <? if($this->dados->usu_sexo == "F") { echo "Feminino"; }?>
                </span>
            </div>
            <div class="pos" id="_91:264" style="top:267;left:93">
                <span id="_8.6" style=" font-family:Arial; font-size:8px; color:#000000">
                    10 - NOME DA MÃE OU RESPONSÁVEL
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->usu_mae?>
                </span>
            </div>
            <div class="pos" id="_612:264" style="top:267;left:615">
                <span id="_8.6" style=" font-family:Arial; font-size:8px; color:#000000">
                    11 - TELEFONE DE CONTATO
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->dom_telefone?>
                </span>
            </div>
            <div class="pos" id="_91:297" style="top:300;left:93">
                <span id="_8.8" style=" font-family:Arial; font-size:8px; color:#000000">
                    12 - ENDEREÇO (RUA, N&#186;, BAIRRO)
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <? if ($this->dados->rua_nome != "") { echo $this->dados->rua_nome; } ?>
                    <? if ($this->dados->rua_nome != "" && $this->dados->dom_numero != "") { echo ",".$this->dados->dom_numero; } ?>
                    <? if ($this->dados->rua_nome != "" && $this->dados->rua_cep != "" ) { echo ",".$this->dados->rua_cep; } ?>
                    <? if ($this->dados->rua_nome != "" && $this->dados->rua_bairro != "" ) { echo ",".$this->dados->rua_bairro; } ?>
                </span>
            </div>
            <div class="pos" id="_91:331" style="top:333;left:93">
                <span id="_8.8" style=" font-family:Arial; font-size:8px; color:#000000">
                    13 - MUNICÍPIO DE RESIDÊNCIA
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->cid_nome?>
                </span>
            </div>
            <div class="pos" id="_495:331" style="top:334;left:497">
                <span id="_8.8" style=" font-family:Arial; font-size:8px; color:#000000">
                    14 - COD. IBGE MUNICÍPIO
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->cid_codigo_ibge?>
                </span>
            </div>
            <div class="pos" id="_612:331" style="top:334;left:614">
                <span id="_8.2" style=" font-family:Arial; font-size:8px; color:#000000">
                    15 - UF
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->uf_sigla?>
                </span>
            </div>
            <div class="pos" id="_694:331" style="top:334;left:696">
                <span id="_8.2" style=" font-family:Arial; font-size:8px; color:#000000">
                    16 - CEP
                </span>
                <br />
                <span style="font-family:Arial; font-size:10px; color:#000000">
                    <?=$this->dados->rua_cep?>
                </span>
            </div>
            <div class="pos" id="_314:373" style="top:376;left:329">
                <span id="_12.4" style="font-weight:bold; font-family:Arial; font-size:11px; color:#000000">
                    JUSTIFICATIVA DA INTERNAÇÃO
                </span>
            </div>
            <div class="pos" id="_91:386" style="top:389;left:93">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    17 - PRINCIPAIS SINAIS E SINTOMAS CLÍNICOS
                </span>
            </div>
            <div class="pos" id="_91:547" style="top:550;left:93">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    18 - CONDIÇÕES QUE JUSTIFICAM A INTERNAÇÃO
                </span>
            </div>
            <div class="pos" id="_91:621" style="top:624;left:93">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    19 - PRINCIPAIS RESULTADOS DE PROVAS DIAGNÓSTICAS (RESULTADOS DE EXAMES REALIZADOS)</span>
            </div>
            <div class="pos" id="_159:694" style="top:697;left:161">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    20 - DIAGNÓSTICO INICIAL</span>
            </div>
            <div class="pos" id="_390:694" style="top:697;left:392">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    21 - CID 10 PRINCIPAL
                </span>
            </div>
            <div class="pos" id="_513:694" style="top:697;left:515">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    22 - CID 10 SECUNDÁRIO
                </span>
            </div>
            <div class="pos" id="_634:694" style="top:697;left:636">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    23 - CID 10 CAUSAS ASSOCIADAS
                </span>
            </div>
            <div class="pos" id="_323:731" style="top:734;left:338">
                <span id="_12.5" style="font-weight:bold; font-family:Arial; font-size:11px; color:#000000">
                    PROCEDIMENTO SOLICITADO
                </span>
            </div>
            <div class="pos" id="_66:746" style="top:749;left:68">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    24 - DESCRIÇÃO DO PROCEDIMENTO SOLICITADO
                </span>
            </div>
            <div class="pos" id="_606:746" style="top:749;left:608">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    25 - CÓDIGO DO PROCEDIMENTO
                </span>
            </div>
            <div class="pos" id="_95:777" style="top:780;left:97">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    26 - CLÍNICA
                </span>
            </div>
            <div class="pos" id="_195:777" style="top:780;left:197">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    27 - CARÁTER DA INTERNAÇÃO</span>
            </div>
            <div class="pos" id="_359:777" style="top:780;left:361">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    28 - DOCUMENTO
                </span>
            </div>
            <div class="pos" id="_455:777" style="top:780;left:457">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    29 - N&#186; DOCUMENTO (CNS/CPF) DO PROFISSIONAL SOLICITANTE/ASSISTENTE
                </span>
            </div>
            <div class="pos" id="_343:791" style="top:794;left:345">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    (
                </span>
            </div>
            <div class="pos" id="_360:791" style="top:794;left:362">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    ) CNS
                </span>
            </div>
            <div class="pos" id="_400:791" style="top:794;left:402">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    (
                </span>
            </div>
            <div class="pos" id="_416:791" style="top:794;left:418">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    ) CPF
                </span>
            </div>
            <div class="pos" id="_66:812" style="top:815;left:68">
                <span id="_8.6" style=" font-family:Arial; font-size:8px; color:#000000">
                    30 - NOME DO PROFISSIONAL SOLICITANTE/ASSISTENTE
                </span>
                <br />
                <div class="pos" id="_403:812" style="top:18;">
                    <span style="font-family:Arial; font-size:10px; color:#000000">
                        <?=$this->dados->usr_nome?>
                    </span>
                </div>
            </div>
            <div class="pos" id="_403:812" style="top:815;left:405">
                <span id="_8.6" style=" font-family:Arial; font-size:8px; color:#000000">
                    31 - DATA DA SOLICITAÇÃO
                </span>
                <br />
                <div class="pos" id="_403:812" style="top:18;left:4">
                    <span style="font-family:Arial; font-size:10px; color:#000000">
                       <?=date("d/m/Y")?>
                    </span>
                </div>
            </div>
            <div class="pos" id="_403:812" style="top:815;left:524">
                <span id="_8.6" style=" font-family:Arial; font-size:8px; color:#000000">
                    32-ASSINATURA E CARIMBO (N&#186; DO REGISTRO DO CONSELHO)
                </span>
            </div>
            <div class="pos" id="_181:863" style="top:866;left:212">
                <span id="_12.5" style="font-weight:bold; font-family:Arial; font-size:11px; color:#000000">
                    PREENCHER EM CASO DE CAUSAS EXTERNAS (ACIDENTES OU VIOLÊNCIAS)
                </span>
            </div>
            <div class="pos" id="_273:878" style="top:881;left:275">
                <span id="_8.8" style=" font-family:Arial; font-size:8px; color:#000000">
                    36 - CNPJ DA SEGURADORA
                </span>
            </div>
            <div class="pos" id="_593:878" style="top:881;left:595">
                <span id="_8.8" style=" font-family:Arial; font-size:8px; color:#000000">
                    37 - N&#186; DO BILHETE</span>
            </div>
            <div class="pos" id="_712:878" style="top:881;left:714">
                <span id="_8.8" style=" font-family:Arial; font-size:8px; color:#000000">
                    38 - SÉRIE</span>
            </div>
            <div class="pos" id="_57:889" style="top:889;left:57">
                <span id="_8.1" style="font-weight:bold; font-family:Arial; font-size:7px; color:#000000">
                    33 - (</span>
            </div>
            <div class="pos" id="_88:889" style="top:889;left:88">
                <span id="_9.1" style="font-weight:bold; font-family:Arial; font-size:8px; color:#000000">
                    ) ACIDENTE DE TRÁNSITO</span>
            </div>
            <div class="pos" id="_57:908" style="top:908;left:57">
                <span id="_8.1" style="font-weight:bold; font-family:Arial; font-size:7px; color:#000000">
                    34 - (</span>
            </div>
            <div class="pos" id="_88:908" style="top:908;left:88">
                <span id="_9.1" style="font-weight:bold; font-family:Arial; font-size:8px; color:#000000">
                    ) ACIDENTE TRABALHO TÍPICO</span>
            </div>
            <div class="pos" id="_273:914" style="top:917;left:275">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    39 - CNPJ EMPRESA
                </span>
            </div>
            <div class="pos" id="_584:914" style="top:917;left:586">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    40 - CNAE DA EMPRESA
                </span>
            </div>
            <div class="pos" id="_713:914" style="top:917;left:715">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    41 - CBOR
                </span>
            </div>
            <div class="pos" id="_57:928" style="top:928;left:57">
                <span id="_8.3" style="font-weight:bold; font-family:Arial; font-size:7px; color:#000000">
                    35 - (
                </span>
            </div>
            <div class="pos" id="_88:928" style="top:928;left:88">
                <span id="_9.2" style="font-weight:bold; font-family:Arial; font-size:8px; color:#000000">
                    ) ACIDENTE TRABALHO TRAJETO
                </span>
            </div>
            <div class="pos" id="_79:949" style="top:952;left:81">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    42 - VÍNCULO COM A PREVIDÊNCIA
                </span>
            </div>
            <div class="pos" id="_66:960" style="top:963;left:66">
                <span id="_8.3" style=" font-family:Arial; font-size:8.3px; color:#000000">
                    (
                </span>
            </div>
            <div class="pos" id="_82:960" style="top:963;left:84">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    ) EMPREGADO
                </span>
            </div>
            <div class="pos" id="_184:960" style="top:963;left:186">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    (
                </span>
            </div>
            <div class="pos" id="_200:960" style="top:963;left:202">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    ) EMPREGADOR
                </span>
            </div>
            <div class="pos" id="_308:960" style="top:963;left:310">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    (
                </span>
            </div>
            <div class="pos" id="_324:960" style="top:963;left:326">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    ) AUTÔNOMO
                </span>
            </div>
            <div class="pos" id="_419:960" style="top:963;left:421">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    (
                </span>
            </div>
            <div class="pos" id="_436:960" style="top:963;left:438">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    ) DESEMPREGADO
                </span>
            </div>
            <div class="pos" id="_553:960" style="top:963;left:555">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    (
                </span>
            </div>
            <div class="pos" id="_569:960" style="top:963;left:571">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    ) APOSENTADO
                </span>
            </div>
            <div class="pos" id="_672:960" style="top:963;left:674">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    (
                </span>
            </div>
            <div class="pos" id="_689:960" style="top:963;left:691">
                <span id="_8.8" style=" font-family:Arial; font-size:8px; color:#000000">
                    ) N&#195;O SEGURADO
                </span>
            </div>
            <div class="pos" id="_368:985" style="top:988;left:374">
                <span id="_12.7" style="font-weight:bold; font-family:Arial; font-size:11px; color:#000000">
                    AUTORIZAÇÃO
                </span>
            </div>
            <div class="pos" id="_66:1001" style="top:1004;left:68">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    43 - NOME DO PROFISSIONAL AUTORIZADOR
                </span>
            </div>
            <div class="pos" id="_410:1001" style="top:1004;left:412">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    44 - COD. ORGÃO EMISSOR
                </span>
            </div>
            <div class="pos" id="_541:1001" style="top:1004;left:543">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    49 - N&#186; DA AUTORIZAÇÃO DE INTERNAÇÃO HOSPITALAR
                </span>
            </div>
            <div class="pos" id="_95:1033" style="top:1036;left:97">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    45 - DOCUMENTO
                </span>
            </div>
            <div class="pos" id="_234:1033" style="top:1036;left:236">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    46 - N&#186; DOCUMENTO (CNS/CPF) DO PROFISSIONAL AUTORIZADOR
                </span>
            </div>
            <div class="pos" id="_76:1046" style="top:1049;left:78">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    (
                </span>
            </div>
            <div class="pos" id="_92:1046" style="top:1049;left:94">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    ) CNS
                </span>
            </div>
            <div class="pos" id="_146:1046" style="top:1049;left:148">
                <span id="_8.3" style=" font-family:Arial; font-size:8px; color:#000000">
                    (
                </span>
            </div>
            <div class="pos" id="_162:1046" style="top:1046;left:162">
                <span id="_8.3" style=" font-family:Arial; font-size:8.3px; color:#000000">
                    ) CPF</span>
            </div>
            <div class="pos" id="_57:1065" style="top:1068;left:59">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    47-DATA DA AUTORIZAÇÃO
                </span>
            </div>
            <div class="pos" id="_225:1065" style="top:1068;left:227">
                <span id="_8.7" style=" font-family:Arial; font-size:8px; color:#000000">
                    48 - ASSINATURA E CARIMBO (N&#186; DO REGISTRO DO CONSELHO)
                </span>
            </div>
        </nowrap></nobr>
</body>
</html>
