<?php if ($this->itens && $this->itens->count()){ ?>
	<table class="grid ui-widget ui-widget-content ui-corner-all" width="100%">
            <tr class="ui-widget-header">
                <th>Profissional</th>
                    <th>Especialidade</th>
                <th>Opções</th>
            </tr>
        <?php foreach ($this->itens as $item){ ?>
                <tr>
                    <td class="ui-state-default"><?= $this->escape($item->item_nome); ?></td>
                    <td class="ui-state-default"><?= $this->escape($item->esp_nome); ?></td>
                    <td class="ui-state-default c" width="80">
                            <a href="<?= $this->url(array("controller" => "convenio-itens", "action" => "editar-agendamento-estabelecimentos-de-saude-profissionais", "id" => $item->coni_codigo)); ?>" class="editar"><img src="<?= $this->baseUrl('/public/images/icons/editar.png'); ?>" alt="Editar" title="Editar" /></a>
                            <a href="<?= $this->url(array("controller" => "convenio-itens", "action" => "excluir-agendamento-estabelecimentos-de-saude-profissionais", "id" => $item->coni_codigo)); ?>" class="excluir"><img src="<?= $this->baseUrl('/public/images/icons/excluir.png'); ?>" alt="Excluir" title="Excluir" /></a>
                    </td>
                </tr>
        <?php } ?>
<?php } else { ?>
        <em>Nenhum profissional cadastrado</em>
<?php } ?>