<form method="post" name="form" id="form" action="<?= $this->url(array("action" => "salvar-procedimento-laboratorio")); ?>">
    <?php $this->errorMsg(); ?>
    <?php $this->dialog(); ?>
    <label>Convênio:</label>
    <span><?= $this->conv->nome_convenio ?></span><br />
    <input type="hidden" name="conv_codigo" id="conv_codigo" value="<?= $this->escape($this->conv->conv_codigo); ?>" />
    <input type="hidden" name="coni_codigo" id="coni_codigo" value="<?= $this->escape($this->dados->coni_codigo); ?>" />
    <input type="hidden" name="prestador" id="prestador" value="<?= $this->conv->prestador_servico ?>" />
    <label>Proced. Específico:</label>
    <input type="text" name="proc_nome" id="proc_nome" value="<?= $this->escape($this->dados->proc_nome); ?>" class="focus" />
    <input type="hidden" name="proc_codigo" id="proc_codigo" value="<?= $this->escape($this->dados->proc_codigo); ?>" />
    <a href="<?= $this->url(array("action" => "novo", "controller" => "procedimento", "pop" => 1), NULL, TRUE) ?>" class="ui-button novo popup" rel="600x300" data-atalho="CTRL+N">Novo</a><br />
    <label>Grupo Proced.</label>
    <select name="gruex_codigo" id="gruex_codigo" class="ui-state-default">
        <option value=""> --Selecione--</option>
        <?foreach($this->grupos as $grupo):?>
            <option value="<?=$grupo->gruex_codigo?>" <?=($this->dados->gruex_codigo == $grupo->gruex_codigo ? "selected=selected" : "")?>><?=$grupo->gruex_descricao?></option>
        <?endforeach;?>
    </select>
    <br/>
    <label>Valor <small>(R$)</small>:</label>
    <input type="text" name="coni_valor" id="proc_vlsa" style="width:100px;" class="float" rel="9,2" value="<?= $this->dados->coni_valor ? number_format($this->dados->coni_valor, 2, '.', '') : ""; ?>" /><br />
    <label>Quantidade máxima por mês:</label>
    <input type="hidden" name="coni_cota_mes_original" value="<?= ($this->dados->coni_cota_mes == -1 ? "" : $this->dados->coni_cota_mes); ?>" />
    <input type="text" name="coni_cota_mes" id="coni_cota_mes" style="width:50px;" value="<?= ($this->dados->coni_cota_mes == -1 ? "" : $this->dados->coni_cota_mes); ?>" /><small>(vazio = ilimitado)</small><br />
    <label>Quantidade máxima por dia:</label>
    <input type="hidden" name="coni_cota_dia_original" value="<?= ($this->dados->coni_cota_dia == -1 ? "" : $this->dados->coni_cota_dia); ?>" />
    <input type="text" name="coni_cota_dia" id="coni_cota_dia" style="width:50px;"  value="<?= ($this->dados->coni_cota_dia == -1 ? "" : $this->dados->coni_cota_dia); ?>" /><small>(vazio = ilimitado)</small><br />
    <label>Ativo:</label>
    <input type="radio" name="coni_ativo" value="S" <?= ($this->dados->coni_ativo != "N" ? "checked=checked" : "") ?>> Sim
    <input type="radio" name="coni_ativo" value="N"<?= ($this->dados->coni_ativo == "N" ? "checked=checked" : "") ?>> Não<br />
    <a href="#" class="ui-button salvar"  style="margin-left: 185px;">Salvar</a>
    <a href="<?= $this->url(array("action" => "index", "module" => "agenda", "controller" => "convenio"), NULL, TRUE) ?>" class="ui-button voltar" data-atalho="ESC">Voltar</a>
</form>
<div class="space"></div>
<?= $this->action("itens", "convenio-itens", "agenda", array("conv" => $this->conv->conv_codigo)); ?>