<?php if ($this->itens && $this->itens->count()): ?>
	<table class="grid ui-widget ui-widget-content ui-corner-all" width="100%">
		<tr class="ui-widget-header">
                        <?if($this->prestador == "U"){?>
                            <th>Profissional</th>
                        <?}else{?>
                            <th>Procedimento</th>
                            <th>Valor <small>(R$)</small></th>
                        <?}?>
			<th>Vagas/mês</th>
			<th>Vagas/dia</th>
			<th>Status</th>
			<th>Opções</th>

		</tr>
		<?php foreach ($this->itens as $item): ?>
			<tr>
				<td class="ui-state-default"><?= $this->escape($item->item_nome); ?></td>
                                <?if($this->prestador != "U"){?>
                                    <td class="ui-state-default d" width="100"><?= number_format($item->coni_valor, 2, ',', '.'); ?></td>
                                <?}?>
				<td class="ui-state-default d" width="100"><?= ($item->coni_cota_mes == -1 ? "<em>ilimitado</>" : $item->coni_cota_mes); ?></td>
				<td class="ui-state-default d" width="100"><?= ($item->coni_cota_dia == -1 ? "<em>ilimitado</>" : $item->coni_cota_dia); ?></td>
				<td class="ui-state-default d" width="80"><?= ($item->coni_ativo == 'S' ? "Ativo" : "Inativo"); ?></td>
				<td class="ui-state-default c" width="80">
					<a href="<?= $this->url(array("controller" => "convenio-itens", "action" => "editar", "id" => $item->coni_codigo)); ?>" class="editar"><img src="<?= $this->baseUrl('/public/images/icons/editar.png'); ?>" alt="Editar" title="Editar" /></a>
					<a href="<?= $this->url(array("controller" => "convenio-itens", "action" => "excluir", "id" => $item->coni_codigo)); ?>" class="excluir"><img src="<?= $this->baseUrl('/public/images/icons/excluir.png'); ?>" alt="Excluir" title="Excluir" /></a>
				</td>
			</tr>
		<?php endforeach; ?>
	<?php else: ?>
		<em>Nenhum procedimento cadastrado</em>
	<?php endif; ?>