ALTER TABLE resultadoexame ADD COLUMN age_codigo bigint;
ALTER TABLE resultadoexame ADD FOREIGN KEY (age_codigo) REFERENCES agendamento (age_codigo) ON UPDATE NO ACTION ON DELETE NO ACTION;
COMMENT ON COLUMN resultadoexame.age_codigo IS 'COLUNA PARA COLOCAR O CODIGO DE AGENDAMENTO DE CONSULTA PARA QUANDO O MÉDICO DIGITAR O RESULTADO DE EXAME';


