--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.5.850
--  Created On : quarta-feira, 02 maio, 2012 
--  DBMS       : PostgreSQL 
--  -------------------------------------------------- 

CREATE TABLE convenio ( 
	conv_codigo bigserial NOT NULL,
	med_codigo bigint,
	conv_valor_mes double precision,
	conv_sabado boolean NOT NULL,
	conv_domingo boolean NOT NULL,
	uni_codigo bigint
)
;
COMMENT ON TABLE convenio
    IS 'Cadastro de convênios prestadores de serviço, podendo ser inclusive uma unidade de saúde do município'
;

ALTER TABLE convenio ADD CONSTRAINT PK_Convenio 
	PRIMARY KEY (conv_codigo)
;



--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.5.850
--  Created On : quarta-feira, 02 maio, 2012 
--  DBMS       : PostgreSQL 
--  -------------------------------------------------- 

CREATE TABLE convenio_itens ( 
	coni_codigo bigserial NOT NULL,
	conv_codigo bigint NOT NULL,
	proc_codigo bigint,
	med_codigo bigint,
	esp_codigo bigint,
	coni_valor double precision,
	coni_tipo_origem char(1) NOT NULL,    -- P - Hospital e laboratório U - Unidade de saúde do município  
	coni_tipo_prestador char(1) NOT NULL,    -- Q - Quantidade V - Valor 
	coni_cota_mes integer,
	coni_cota_dia integer,
	usr_codigo integer
)
;
COMMENT ON TABLE convenio_itens
    IS 'Cadastro de procedimentos ou especialidades / médicos atendidos pelo convênio'
;
COMMENT ON COLUMN convenio_itens.coni_tipo_origem
    IS 'P - Hospital e laboratório U - Unidade de saúde do município '
;
COMMENT ON COLUMN convenio_itens.coni_tipo_prestador
    IS 'Q - Quantidade V - Valor'
;

ALTER TABLE convenio_itens ADD CONSTRAINT PK_convenio_itens 
	PRIMARY KEY (coni_codigo)
;

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.5.850
--  Created On : quarta-feira, 02 maio, 2012 
--  DBMS       : PostgreSQL 
--  -------------------------------------------------- 

CREATE TABLE grade_dia ( 
	grad_codigo bigserial NOT NULL,
	grad_cota_dia integer,
	grad_dia date,
	grad_valor double precision,
	coni_codigo bigint NOT NULL
)
;

ALTER TABLE grade_dia ADD CONSTRAINT PK_grade_dia 
	PRIMARY KEY (grad_codigo)
;


ALTER TABLE grade_dia ADD CONSTRAINT FK_grade_dia_convenio_itens 
	FOREIGN KEY (coni_codigo) REFERENCES convenio_itens (coni_codigo)
;

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.5.850
--  Created On : quarta-feira, 02 maio, 2012 
--  DBMS       : PostgreSQL 
--  -------------------------------------------------- 

CREATE TABLE grade_mes ( 
	gram_codigo bigserial NOT NULL,
	coni_codigo bigint,
	gram_cota_mes integer,
	gram_mes date,
	gram_valor double precision DEFAULT 0 NOT NULL
)
;

ALTER TABLE grade_mes ADD CONSTRAINT PK_grade_mes 
	PRIMARY KEY (gram_codigo)
;


ALTER TABLE grade_mes ADD CONSTRAINT FK_grade_mes_convenio_itens 
	FOREIGN KEY (coni_codigo) REFERENCES convenio_itens (coni_codigo)
;

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.5.850
--  Created On : quarta-feira, 02 maio, 2012 
--  DBMS       : PostgreSQL 
--  -------------------------------------------------- 

CREATE TABLE horarioAtendimentoMedico ( 
	hor_codigo bigserial NOT NULL,
	hor_dia char(1),    -- Coluna que define os dias 0 a 6 começando por domingo 
	hor_horario_inicio timestamp,
	hot_hora_fim timestamp,
	hor_quantidade bigint,
	hor_valor double precision,
	coni_codigo bigint
)
;
COMMENT ON TABLE horarioAtendimentoMedico
    IS 'Cadastro de horários de atendimento do médico.'
;
COMMENT ON COLUMN horarioAtendimentoMedico.hor_dia
    IS 'Coluna que define os dias 0 a 6 começando por domingo'
;

ALTER TABLE horarioAtendimentoMedico ADD CONSTRAINT PK_horario 
	PRIMARY KEY (hor_codigo)
;


ALTER TABLE horarioAtendimentoMedico ADD CONSTRAINT FK_horario_convenio_itens 
	FOREIGN KEY (coni_codigo) REFERENCES convenio_itens (coni_codigo)
;


--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.5.850
--  Created On : quarta-feira, 02 maio, 2012 
--  DBMS       : PostgreSQL 
--  -------------------------------------------------- 

CREATE TABLE agenda ( 
	age_codigo bigserial NOT NULL,
	usu_codigo bigint,
	age_status char(1)
)
;

ALTER TABLE agenda ADD CONSTRAINT PK_agenda 
	PRIMARY KEY (age_codigo)
;
COMMENT ON COLUMN agenda.age_status IS 'A - Agendado
R - Recepsionado
F - Falta
C - Cancelado
T - Transferência';

CREATE TABLE agenda_itens
(
  agei_codigo bigserial NOT NULL,
  age_codigo bigint,
  agei_data date,
  agei_hora time without time zone,
  coni_codigo bigint,
  agei_valor double precision,
  CONSTRAINT pk_agenda_itens PRIMARY KEY (agei_codigo ),
  CONSTRAINT fk_agenda_itens_agenda FOREIGN KEY (age_codigo)
      REFERENCES agenda (age_codigo) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_agenda_itens_convenio_itens FOREIGN KEY (coni_codigo)
      REFERENCES convenio_itens (coni_codigo) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE agenda_itens
  OWNER TO postgres;

ALTER TABLE convenio_itens ADD FOREIGN KEY (conv_codigo) REFERENCES convenio (conv_codigo) ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE agenda ADD COLUMN usr_codigo integer;
ALTER TABLE agenda ADD COLUMN usr_data_insert timestamp with time zone;
ALTER TABLE agenda_itens
   ALTER COLUMN agei_data TYPE date;

   ALTER TABLE convenio ADD COLUMN conv_status boolean;

ALTER TABLE agenda_itens
   ALTER COLUMN agei_valor TYPE double precision;
   ALTER TABLE agenda ADD COLUMN age_status character(1);

   
   ALTER TABLE agenda
   ALTER COLUMN age_status SET DEFAULT 'A';
ALTER TABLE agenda
   ALTER COLUMN age_status SET NOT NULL;

   ALTER TABLE agenda_itens
   ALTER COLUMN agei_hora TYPE time without time zone;
   
   ALTER TABLE horarioatendimentomedico
   ALTER COLUMN hor_horario_inicio TYPE time without time zone;
ALTER TABLE horarioatendimentomedico
   ALTER COLUMN hot_hora_fim TYPE time without time zone;

   ALTER TABLE grade_mes
   ALTER COLUMN gram_valor DROP NOT NULL;
ALTER TABLE grade_mes ADD COLUMN gram_alterado boolean;
ALTER TABLE grade_dia ADD COLUMN grad_alterado boolean;

 ALTER TABLE agenda_itens ADD COLUMN usr_codigo bigint;
ALTER TABLE agenda_itens ADD CONSTRAINT fk_usr_codigo FOREIGN KEY (usr_codigo) REFERENCES usuarios (usr_codigo) ON UPDATE NO ACTION ON DELETE NO ACTION;

 ALTER TABLE agenda_itens ADD COLUMN agei_status character(1);
COMMENT ON COLUMN agenda_itens.agei_status IS 'A - Agendado
R - Recepsionado
F - Falta
C - Cancelado
T - Transferência';

ALTER TABLE agenda DROP COLUMN age_status;

ALTER TABLE agenda_itens
  ALTER COLUMN agei_status SET DEFAULT 'A';
  
  ALTER TABLE agenda RENAME usr_data_insert  TO age_data_insert;



