<div class="msgAtencao" id="aguarde-esus">
    <p> Aguarde enquanto o arquivo é gerado, este processo pode demorar alguns minutos.</p>
</div>
<div class='success' id='ok-esus' style="display: none;">
    <h1>ARQUIVO GERADO COM SUCESSO!</h1>
    <a href='../../../e-sus/download.php?arquivo=<?=$_SESSION["root"]."".$_SESSION["modulo"]?>e-sus/arqs/RAS_FileZip.zip'>
        <img src='../../../imgs/download.png' title='Baixar arquivo'>
    </a>
</div>
