<?php $this->dialog(); ?>
<ul>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=pais" class="popup" rel="400x200">
            Importa Países
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=estado" class="popup" rel="400x200">
            Importa Estados
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=tplocalidade" class="popup" rel="400x200">
            Importa Tipo de Cidades
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=cidades" class="popup" rel="400x200">
            Importa Cidades
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=bairros" class="popup" rel="400x200">
            Importa Bairros
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=baiesus" class="popup" rel="400x200">
            Importa Bairros E-SUS
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=atubairro" class="popup" rel="400x200">
            Importa Vínculo de  Bairros
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=tplogradouro" class="popup" rel="400x200">
            Importa Tipos de Logradouro
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=tppatente" class="popup" rel="400x200">
            Importa Títulos Logradouro
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=tpparidade" class="popup" rel="400x200">
            Importa Posições Logradouro
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=logradouro" class="popup" rel="400x200">
            Importa Logradouros
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=endereco" class="popup" rel="400x200">
            Importa Logradouros Domicílio
        </a>
    </li>
    <li>
        <a href="<?=$_SESSION[linkroot].$_SESSION[modulo]?>e-sus/h2/domicilio.php?importa=domicilio" class="popup" rel="400x200">
            Importa Domícilios
        </a>
    </li>
</ul>
