<?php $this->dialog(); ?>
<form name='upload' action='<?=$this->url(array("action"=>"ler-arquivo"))?>' method='post' enctype='multipart/form-data' id="cnes">
    <label>Importação Cidadão-Resultado: </label>
    <input type='file' name='arquivo' id="arquivo" class="field" style="height: 26px; width: 380px;"><br />
    <a href="#" class="ui-button salvar" id="enviar" style="margin-left: 184px; margin-top: 06px;">Importar Dados</a>
</form>
