<div class="msgManual" id="aguarde-esus">
    <p>Para realizar a exportação de dados para o E-SUS, continue utilizando o sistema normalmente, segue abaixo as novidades e modificações realizadas:</bold></p>
    <p>1- Alguns campos foram incluídos e outros deixados como obrigatórios, garantindo o envio dos dados necessários para o Ministério da Saúde</p>
    <p>
        2- Implementação do Atendimento Individual, podendo ser acessado em:
        <a href='<?=$this->baseUrl()?>/atendimento/atendimento-simplificado/index'><span>Prog. Federais >> E-SUS >> Atendimento Individual</span></a>
    </p>
    <p>
        3- Implementação da Visita Domiciliar, podendo ser acessada em:
        <a href='<?=$this->baseUrl()?>/atendimento/atendimento-simplificado/index'><span>Visita Domiciliar</span></a>
    </p>
    <p>
        4- Implementação do Atendimento Individual, podendo ser acessado em:
        <a href='<?=$this->baseUrl()?>/atendimento/atendimento-simplificado/index'><span>Atendimento Individual</span></a>
    </p>
    <p>
        2- Implementação do Atendimento Individual, podendo ser acessado em:
        <a href='<?=$this->baseUrl()?>/atendimento/atendimento-simplificado/index'><span>Atendimento Individual</span></a>
    </p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
</div>
