<?

    // echo "<pre>";;print_r($this->recebeCrm);die();

?>

<style>
@media print {
    body {zoom: 85%;}
}
</style>
<?$tamanho_linha = "style='height: 25px;'"?>

<div id="page">
        
	<div id="header" style="border:0px solid;height:70px">
                <div id="logo" style="margin: auto;">
                    <img width="80" height="70" src="<?= $this->baseUrl('/public/images/brasao.gif') ?>" title="Logo Prefeitura" />
		</div>

		<div id="titulo" style="text-align: left;width:80%; ">
			<h2><?=$_SESSION['logon']['usr']->uni_desc?></h2>
			<b>Secretaria Municipal de Saúde</b><br/>
                        <b><?=$this->dadosSecretaria()->endereco;?></b>
                        
		</div>
	
               
	</div>
	<div id="info" style="border:1px solid;">
		<div id="foto" class="" style="width:70px;float:left; margin-top: 5px; margin-right:5px;margin-bottom:5px">
			<img  style="width:70px" src="<?= $this->baseUrl('/public/images/sem_foto_' . $this->dados->usu->usu_sexo . '.png') ?>" alt="Foto do Paciente" title="<?= $this->dados->usu->usu_nome; ?>" />
		</div>
		
		<div class="f" style=" width: 630px;" >
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Data:</b><? echo date("d/m/Y");?>&nbsp;&nbsp;&nbsp;&nbsp;<b>Hora:</b><? echo date("H:i.s");?>
                    <label>Paciente: </label><span> &nbsp;&nbsp;&nbsp;<?=$this->dados->usu->usu_prontuario?> - <?= strtoupper($this->dados->usu->usu_nome); ?></span><br/>
                    <label>Sexo:</label> <span><?= $this->mask($this->dados->usu->usu_sexo, "sexo"); ?></span><br />
                    <label>Mãe:</label> <span><?=strtoupper($this->dados->usu->usu_mae); ?></span><br />
                    <label>End.:</label> <font size="1"><span><?=$this->dados->usu->rua_bairro?>, <?=$this->dados->usu->usu_endereco; ?>, <?=$this->dados->usu->dom_numero?></span></font><br>
		</div>
                <div class="f l2" style="width:630px;border:0px solid">
			<label>Data Nasc.:</label> <span><?= $this->data($this->dados->usu->usu_datanasc) . " (" . $this->idade($this->dados->usu->usu_datanasc) . ")"; ?></span><br />
			<label>Telefone:</label> <span><?= $this->dados->usu->usu_fone; ?></span>
			<label>Celular:</label> <span><?//= $this->dados->usu->usu_celular; ?></span><br>
			<label>CPF:</label> <span><?//= $this->dados->usu->usu_cpf; ?></span>
			<label>RG:</label> <span><?//= $this->dados->usu->usu_rg; ?></span><br>
			<label>Cartão SUS:</label> <span><?= $this->dados->usu->usu_cartao_sus; ?></span>
		</div>
               
                
		<div class="clear"></div>
	</div>
	
        <h3>Triagem</h3>
        Profissional Triagem:_____________________________________________________________________________________<br><br><br>
        <table>
            <tr <?=$tamanho_linha;?>>
                <td>Pressão:_________x________</td>
                <td>Temperatura:______________</td>
                <td>Peso:______________Kg</td>
                <td>Glicemia:_____________</td>
                <td>Estatura:_____________m</td>
            </tr>
            <tr>
                <td colspan="5">&nbsp;</td>
            </tr>
            <tr <?=$tamanho_linha;?>>
                <td>Freq. Cardiaca(min):_________________</td>
                <td>Freq. Respiratoria:______________</td>
                <td colspan="2">Classificassao de Risco:_____________</td>
            </tr>            
        </table>
        
        <h3>Exame Físico/Consulta de Enfermagem</h3>
        <table>
            <tr <?=$tamanho_linha;?>>
                <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td> 
            </tr>
            <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td> 
            </tr>
            <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td>
            </tr>
        </table>

        
        <h3>Anamnese/Historico da Doen&ccedil;a Atual:</h3>
        <table>
            <tr <?=$tamanho_linha;?>>
                <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td> 
            </tr>
            <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td> 
            </tr>
            <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td>
            </tr>
            <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td>
            </tr>
        </table>
        
             <h3>Procedimentos Realizados:</h3>
        <table>
            <tr <?=$tamanho_linha;?>>
                <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td> 
            </tr>
            <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td> 
            </tr>
        </table>

        <h3>Prescri&ccedil;&atilde;o de Medicamentos:</h3>
        <table>
            <tr <?=$tamanho_linha;?>>
                <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td> 
            </tr>
            <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td> 
            </tr>
            <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td>
            </tr>
            <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td>
            </tr>
           <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td>
            </tr>
          <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td>
            </tr>
          </table>

             <h3>Exames Solicitados:</h3>
        <table>
            <tr <?=$tamanho_linha;?>>
                <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td> 
            </tr>
            <tr <?=$tamanho_linha;?>>
               <td colspan="5" style="border-bottom: 1px solid;">&nbsp;</td> 
            </tr>
        </table>



        <table>
            <tr <?=$tamanho_linha;?>>
                <td>Cid Principal:_________________</td>
            </tr>
            <tr>
                <td>Saida do Atendimento:___________________________________________________________________________</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>Encaminhamento:_______________________________     _______________________________</td>
            </tr>
            <table>
<br><br><br>
                <table>
            <tr>
                <td colspan="5"  width="50%" align="center">
                    <br/>________________________________________<br/>
                    
                    <?= $this->med_nome; ?> | <?= $this->recebeCrm[0][med_crm]?>
                </td>
                <td colspan="5" width="50%" align="center">
                    <br/>________________________________________<br/>
                    <?=$this->dados->usu->usu_nome?>
                </td>
            </tr>
        </table>
        <br><br>
</div>