<div id="page">
	<div id="header">
		<div id="logo">
			<img src="<?= $this->baseUrl('/public/images/brasao.gif') ?>" title="Logo Prefeitura" width="80"/>
		</div>
		<div id="titulo">
			<h2>Prefeitura Municipal de <?=$this->dadosSecretaria()->cidade;?></h2>
			<h3>Secretaria Municipal de Saúde</h3>
		</div>
		<div id="barcode">
			<img src="<?= $this->baseUrl() ?>/public/images/codigo_barras.php?codigo=<?= $this->dados->usu->usu_codigo; ?>&lw=1&hi=18" alt="Código de Barras: <?= $this->dados->usu->usu_codigo; ?>" title="Código de Barras: <?= $this->dados->usu->usu_codigo; ?>" />
		</div>
		<div class="clear"></div>
                <?php if($this->data_inicial || $this->data_final):?>
                    <div style="text-align:center">Período: <?=$this->data_inicial?> a <?=$this->data_final?></div>
                <?php endif; ?>
                    <div style="text-align:center">Este prontuário foi impresso pelo operador: <?=$this->usr_nome?></div>
	</div>
	<div id="info">
		<div id="foto">
			<img src="<?= $this->baseUrl('/public/images/sem_foto_' . $this->dados->usu->usu_sexo . '.png') ?>" alt="Foto do Paciente" title="<?= $this->dados->usu->usu_nome; ?>" />
		</div>
		<h2><?=$this->dados->usu->usu_prontuario?> - <?= ucwords(strtolower($this->dados->usu->usu_nome)); ?></h2>
		<div class="f">
			<label>Sexo:</label> <span><?= $this->mask($this->dados->usu->usu_sexo, "sexo"); ?></span><br />
			<label>Mãe:</label> <span><?= $this->dados->usu->usu_mae; ?></span><br />
			<label>End.:</label> <font size="1"><span><?= $this->dados->usu->usu_endereco; ?></span></font><br />
			<label>Profis.:</label> <span><?= $this->dados->usu->no_ocupacao; ?></span><br />
		</div>
		<div class="f l2">
			<label>Data Nasc.:</label> <span><?= $this->data($this->dados->usu->usu_datanasc) . " (" . $this->idade($this->dados->usu->usu_datanasc) . ")"; ?></span><br />
			<label>Est. Civil:</label> <span><?= $this->dados->usu->estado_civil; ?></span><br />
			<label>Telefone:</label> <span><?= $this->mask($this->dados->usu->dom_telefone); ?></span><br />
			<label>Cartão SUS:</label> <span><?= $this->dados->usu->usu_cartao_sus; ?></span>
		</div>
		<div class="clear"></div>
		<div class="space"></div>
	</div>
        <div class="space"></div>
        <div>
            <div style="border: 1px solid; width: 400px;">
                <font size="1">"Este Prontuário contem dados de toda equipe que assistiu o referido
                 paciente, sendo um documento sigiloso a sua guarda é de responsabilidade
                 da entidade mantenedora e em direito legal do paciente." Desta forma só
                 poderá ser impresso sob ordem judicial e a responsabilidade de quem
                 imprimiu pertence a sua senha de permissão para tal.</font>
            </div>
        </div>
	<div id="relatorio">
		<?php if($this->dados->alertas): ?>
		<h2>Alertas</h2>
		<?php if ($this->dados->alertas->count()): ?>
			<?php foreach ($this->dados->alertas as $item): ?>
				<span><?php echo $item->ale_desc; ?></span><br/>
			<?php endforeach; ?>
		<?php else: ?>
			<em>Nenhum alerta cadastrado.</em>
		<?php endif; ?>
		<div class="space"></div>
		<?php endif;?>

		<?php if($this->dados->atendimentos):?>
		<h2>Consultas</h2>
		<?php if ($this->dados->atendimentos->count()): ?>
			<table>
				<?php foreach ($this->dados->atendimentos as $item): ?>
					<tr>
						<th>Data</th>
						<th>Unidade De Saúde</th>
						<th>Profissional</th>
						<th>Especialidade</th>
						<th>Peso</th>
						<th>Alt.</th>
						<th>P/A</th>
						<th>IMC</th>
					</tr>
					<tr>
						<td><?= $this->data($item->ate_data); ?></td>
						<td><?= $this->escape($item->uni_desc); ?></td>
						<td><?= $this->escape($item->usr_nome); ?></td>
						<td><?= $this->escape($item->esp_nome); ?></td>
						<td><?= $this->mask($item->pc_peso, "empty", "--"); ?></td>
						<td><?= $this->mask($item->pc_altura, "empty", "--"); ?></td>
						<td><?= $this->mask($item->pc_pressao_sistolica, "empty", "--") . "/" . $this->mask($item->pc_pressao_diastolica, "empty", "--"); ?></td>
						<td><?= $this->imc($item->pc_peso, $item->pc_altura); ?></td>
					</tr>
					<tr>
						<td colspan="8"><strong>CID</strong> <?= ($item->cd10_codigo_cid ? $this->escape($item->cd10_codigo_cid . " - " . $item->cd10_descricao) : "<em>Não informado</em>"); ?></td>
					</tr>
					<tr>
						<td colspan="8" class="escape">
							<?= $item->ate_reclamacao; ?>
							<?= $item->ate_exame_fisico; ?>
							<?= $item->ate_diagnostico; ?>
							<?= $item->ate_tratamento; ?>
							<?= $item->ate_curativo; ?>
						</td>
					</tr>
					<tr><td colspan="8">&nbsp;</td></tr>
				<?php endforeach; ?>
			</table>
		<?php else: ?>
			<em>Nenhuma consulta encontrada.</em>
		<?php endif; ?>
		<?php endif;?>

		<?php if($this->dados->pre_consultas):?>
		<h2>Pré-Consultas</h2>
		<?php if ($this->dados->pre_consultas->count()): ?>
			<table>
				<?php foreach ($this->dados->pre_consultas as $item): ?>
                                   <?php
                                   //echo $this->escape($item->pc_clas_risco); exit;
                                       if($this->escape($item->pc_clas_risco) == ""){
                                           $clas_risco = "--";
                                       }
                                       if($this->escape($item->pc_clas_risco) == 1){
                                        $clas_risco = "Imediato";
                                       }else if($this->escape($item->pc_clas_risco) == 2){
                                        $clas_risco = "20 Min";
                                       }else if($this->escape($item->pc_clas_risco) == 3){
                                        $clas_risco = "60 Min";
                                       }else if($this->escape($item->pc_clas_risco) == 4){
                                        $clas_risco = "4 Horas";
                                       }


                                       ?>
					<tr>
						<th>Data</th>
						<th>Unidade</th>
						<th>Profissional</th>
						<th>Especialidade</th>
                                                <th>Temp.</th>
						<th>Peso</th>
						<th>Alt.</th>
						<th>P/A</th>
						<th>IMC</th>
                                                <th>Freq. Card. </th>
                                                <th>Freq. Resp.</th>
                                                <th>Perí. Cef.</th>
                                                <th>Glic.</th>
                                                <th>Satu.</th>
                                                <th>Class.</th>
					</tr>
					<tr>
						<td><?= $this->data($item->age_data); ?></td>
						<td><?= $this->escape($item->uni_desc); ?></td>
						<td><?= $this->escape($item->usr_nome_enf); ?></td>
						<td><?= $this->escape($item->esp_nome); ?></td>
                                                <td><?= $this->mask($item->pc_temperatura, "empty", "--"); ?></td>
						<td><?= $this->mask($item->pc_peso, "empty", "--"); ?></td>
						<td><?= $this->mask($item->pc_altura, "empty", "--"); ?></td>
						<td><?= $this->mask($item->pc_pressao_sistolica, "empty", "--") . "/" . $this->mask($item->pc_pressao_diastolica, "empty", "--"); ?></td>
						<td><?= $this->imc($item->pc_peso, $item->pc_altura); ?></td>
                                                <td><?= $this->mask($item->pc_freq_cardiaca,"empty","--"); ?></td>
                                                <td><?= $this->mask($item->pc_freq_respiratoria,"empty","--"); ?></td>
                                                <td><?= $this->mask($item->pc_perimetro_cefalico,"empty","--"); ?></td>
                                                <td><?= $this->mask($item->pc_glicose,"empty","--"); ?></td>
                                                <td><?= $this->mask($item->pc_saturacao,"empty","--"); ?></td>
                                                <td><?= $clas_risco?></td>
					</tr>
					<tr>
						<td colspan="15" class="escape">
							<?= $item->pc_dados; ?>
						</td>
					</tr>
					<tr><td colspan="15">&nbsp;</td></tr>
				<?php endforeach; ?>
			</table>
		<?php else: ?>
			<em>Nenhuma consulta encontrada.</em>
		<?php endif; ?>
		<?php endif;?>

		<?php if($this->dados->exames):?>
		<h2>Exames</h2>
		<?php if ($this->dados->exames->count()): ?>
			<table>
				<tr>
					<th>Procedimento</th>
                                        <th>Profissional</th>
					<th>Prestador</th>
					<th>Data de Coleta</th>
				</tr>
				<?php foreach ($this->dados->exames as $item): ?>
				<tr>
					<td><?=$item->proc_nome;?></td>
                                        <td><?=$item->usr_nome;?></td>
					<td><?=$item->med_nome;?></td>
					<td><?=$this->data($item->agei_data);?></td>
				</tr>
				<?php endforeach; ?>
			</table>
		<?php else: ?>
			<em>Nenhum exame encontrado.</em>
		<?php endif; ?>
		<?php endif;?>

		<?php if($this->dados->procedimentos):?>
		<h2>Procedimentos</h2>
		<?php if ($this->dados->procedimentos->count()): ?>
			<table>
				<tr>
					<th>Data</th>
					<th>Procedimento</th>
					<th>CID</th>
					<th>Profissional</th>
					<th>Observações</th>
				</tr>
				<?php foreach ($this->dados->procedimentos as $item): ?>
				<tr>
					<td><?=$this->data($item->age_data);?></td>
					<td><?=$item->proc_nome;?></td>
					<td><?=$this->mask($item->cd10_descricao,"empty","--");?></td>
					<td><?=$item->usr_nome;?></td>
					<td><?=$item->ate_diagnostico;?></td>
				</tr>
				<?php endforeach; ?>
			</table>
		<?php else: ?>
			<em>Nenhum procedimento registrado.</em>
		<?php endif; ?>
		<?php endif;?>

		<?php if($this->dados->medicamentos):?>
		<h2>Medicamentos</h2>
		<?php if ($this->dados->medicamentos->count()): ?>
			<table>
				<tr>
					<th>Data</th>
					<th>Unidade</th>
					<th>Medicamento</th>
                                        <th>Lote</th>
					<th>Quant.</th>
					<th>Profissional</th>
				</tr>
				<?php foreach ($this->dados->medicamentos as $item): ?>
				<tr>
					<td><?=$this->data($item->mov_data);?></td>
					<td><?=$item->uni_desc;?></td>
					<td><?=$item->pro_nome;?></td>
                                        <td><?=$item->ite_lote;?></td>
					<td class="d"><?=number_format($item->ite_quantidade,0);?></td>
					<td><?=$item->usr_nome;?></td>
				</tr>
				<?php endforeach; ?>
			</table>
		<?php else: ?>
			<em>Nenhum medicamento dispensado.</em>
		<?php endif; ?>
		<?php endif;?>

		<?php if($this->dados->observacoes):?>
			<h2>Observações</h2>
			<?=$this->dados->observacoes; ?>
		<?php endif;?>

                <?php if($this->dados->importacoes):?>
			<h2>Observações</h2>
			<?=$this->dados->importacoes; ?>
		<?php endif;?>

		<?php if($this->dados->vacinas):?>
		<h2>Vacinas</h2>
		<?php if ($this->dados->vacinas->count()): ?>
			<table>
				<tr>
					<th>Data</th>
					<th>Unidade</th>
					<th>Vacina</th>
					<th>Lote</th>
					<th>Dose</th>
				</tr>
				<?php foreach ($this->dados->vacinas as $item): ?>
				<tr>
					<td><?=$this->data($item->vac_data);?></td>
					<td><?=$item->uni_desc;?></td>
					<td><?=$item->pro_nome;?></td>
					<td><?=$item->ite_lote;?></td>
					<td><?=($item->vac_dose<6?$item->vac_dose."&ordf; dose":"Reforço");?></td>
				</tr>
				<?php endforeach; ?>
			</table>
		<?php else: ?>
			<em>Nenhuma vacina aplicada/preenchida.</em>
		<?php endif; ?>
		<?php endif;?>

		<?php if($this->dados->vacinasAprazadas):?>
		<h2>Vacinas - Aprazadas</h2>
		<?php if ($this->dados->vacinasAprazadas->count()): ?>
			<table>
				<tr>
					<th>Data</th>
					<th>Unidade</th>
					<th>Vacina</th>
					<th>Dose</th>
				</tr>
				<?php foreach ($this->dados->vacinasAprazadas as $item): ?>
				<tr>
					<td><?=$this->data($item->vac_data);?></td>
					<td><?=$item->uni_desc;?></td>
					<td><?=$item->pro_nome;?></td>
					<td><?=($item->vac_dose<6?$item->vac_dose."&ordf; dose":"Reforço");?></td>
				</tr>
				<?php endforeach; ?>
			</table>
		<?php else: ?>
			<em>Nenhuma vacina aprazada.</em>
		<?php endif; ?>
		<?php endif;?>



		<h2>Internação</h2>
		<?php if ($this->dados->internacoes->count()): ?>
			<table>
				<tr>
					<th>Data</th>
					<th>Unidade</th>
					<th>Profissional que encaminhou</th>
					<th>Conduta Médica</th>
				</tr>
				<?php foreach ($this->dados->internacoes as $item):
                                if($age_codigo != $item->age_codigo){
                                ?>
				<tr>
					<td><?=$this->data($item->age_data);?></td>
					<td><?=$item->uni_desc;?></td>
					<td><?=$item->usr_nome;?></td>
					<td><?=$item->age_observacao;?></td>
				</tr>
				<?php
                                $age_codigo = $item->age_codigo;
                                }
                                endforeach; ?>
			</table>
		<?php else: ?>
			<em>Nenhuma internação realizada.</em>
		<?php endif; ?>

                <?php if($this->dados->compra_produtos):?>
		<h2>Compra Produtos</h2>
		<?php if ($this->dados->compra_produtos->count()): ?>
			<table>
				<tr>
					<th>Data</th>
					<th>Produto</th>
					<th>Quantidade</th>
					<th>Valor</th>
					<th>Fornecedor</th>
				</tr>
				<?php foreach ($this->dados->compra_produtos as $item): ?>
				<tr>
					<td><?=$this->data($item->comp_data);?></td>
					<td><?=$item->pro_nome;?></td>
					<td><?=$item->compi_quantidade;?></td>
					<td><?=$item->compi_valor;?></td>
					<td><?=$item->for_nome;?></td>
				</tr>
				<?php endforeach; ?>
			</table>
		<?php else: ?>
			<em>Nenhuma Produto efetuado compra.</em>
		<?php endif; ?>
		<?php endif;?>

                <?php if($this->dados->agendamento_externo):?>
		<h2>Agendamento Externo</h2>
		<?php if ($this->dados->agendamento_externo->count()): ?>
			<table>
				<tr>
					<th>Data</th>
					<th>Especialista</th>
					<th>Unidade</th>
					<th>Observação</th>
					<th>Especialidade</th>
				</tr>
				<?php foreach ($this->dados->agendamento_externo as $item): ?>
				<tr>
					<td><?=$this->data($item->agee_data);?></td>
					<td><?=$item->med_destino?></td>
					<td><?=($item->med_prestador ? $item->med_prestador : $item->usr_prestador);?></td>
					<td><?=$item->agee_observacao;?></td>
					<td><?=$item->esp_nome;?></td>
				</tr>
				<?php endforeach; ?>
			</table>
		<?php else: ?>
			<em>Nenhum agendamento realizado.</em>
		<?php endif; ?>
		<?php endif;?>

                <?php //ID #105426?>

                <?php if($this->dados->atividade_coletiva):?>
                    <h2>Atividades Coletivas</h2>
                    <?php if ($this->dados->atividade_coletiva->count()): ?>
                            <table>
                                    <tr>
                                            <th>Data</th>
                                            <th>Hora Início</th>
                                            <th>Hora Fim</th>
                                            <th>Tipo Atividade</th>
                                            <th>Profissional Responsável</th>
                                    </tr>
                                    <?php foreach ($this->dados->atividade_coletiva as $atividade): ?>
                                    <tr>
                                            <td><?=$atividade->data_atividade?></td>
                                            <td><?=$atividade->hora_inicio?></td>
                                            <td><?=$atividade->hora_fim?></td>
                                            <td><?=$atividade->no_cds_tipo_ativ_col?></td>
                                            <td><?=$atividade->usr_nome?></td>
                                    </tr>
                                    <?php endforeach; ?>
                            </table>
                    <?php else: ?>
                            <em>Não participou de nenhuma atividade coletiva.</em>
                    <?php endif; ?>
		<?php endif;?>

                <?php //ID #105426?>

				<h2>Faltas em Consultas</h2>
				 <table>
					<tr>
						<th>Profissional</th>
						<th>Data</th>
						<th>Observação</th>
					</tr>
				 <?php foreach ($this->fantante as $faltantes): ?>
					<tr>
						<td><?=$faltantes->usr_nome?></td>
						<td><?=$faltantes->age_data?></td>
						<td><?=$faltantes->age_observacao?></td>
					</tr>
				 <?php endforeach; ?>
				</table>

	</div>
	<div class="clear"></div>
        <div class="space"></div>
        <div style="text-align:center">Este prontuário foi impresso pelo operador: <?=$this->usr_nome?></div>
	<div id="footer">
		<span><?=$this->dadosSecretaria()->endereco;?></span>
	</div>
</div>