<table>
    <tr>
        <td><b><font size="2">Nome</font></b></td>
        <td><b><font size="2">Quantidade de registros</font></b></td>
    </tr>
    <?php foreach($this->duplicados as $duplicados):?>
        <tr>
            <td>
                <?=$duplicados->usu_nome?>
            </td>
            <td>
                <?=$duplicados->count?>
            </td>
        </tr>
    <?php endforeach;?>
</table>