<?php $this->dialog(); ?>

<form method="post" action="<?= $this->url(array("action" => "salvar")); ?>">
	<input type="hidden" name="si_codigo" value="<?= $this->dados->si_codigo; ?>" />
	<?php $this->errorMsg(); ?>
	<label>Temperatura <small>(ºC)</small>:</label>
	<input type="text" name="temperatura" value="<?= $this->dados->si_temperatura?(number_format($this->dados->si_temperatura,2)):""; ?>" class="float focus" rel="2,1" <?=$readonly?>/><br />

	<label>Peso <small>(Kg)</small>:</label>
	<input type="text" name="peso" value="<?= $this->dados->si_peso?(number_format($this->dados->si_peso,2)):""; ?>" class="float" rel="3,2" <?=$readonly?>/><br />

	<label>Altura <small>(m)</small>:</label>
	<input type="text" name="altura" value="<?= $this->dados->si_altura?(number_format($this->dados->si_altura,2)):""; ?>" class="float" rel="1,2" <?=$readonly?>/><br />

	<label>Pressão Sistólica <small>(mm/Hg)</small>:</label>
	<input type="text" name="pressao_sistolica" value="<?= $this->escape($this->dados->si_pressao_sistolica); ?>" <?=$readonly?>/><br />

	<label>Pressão Diastólica <small>(mm/Hg)</small>:</label>
	<input type="text" name="pressao_diastolica" value="<?= $this->escape($this->dados->si_pressao_diastolica); ?>" <?=$readonly?>/><br />

	<label>Freq. Cardíaca <small>(BPM)</small>:</label>
	<input type="text" name="freq_cardiaca" value="<?= $this->escape($this->dados->si_freq_cardiaca); ?>" <?=$readonly?>/><br />

	<label>Freq. Respiratória <small>(MPM)</small>:</label>
	<input type="text" name="freq_respiratoria" value="<?= $this->escape($this->dados->si_freq_respiratoria); ?>" <?=$readonly?>/><br />

	<label>Perímetro Cefálico <small>(cm)</small>:</label>
	<input type="text" name="p_cefalico" value="<?= $this->escape(number_format($this->dados->si_perimetro_cefalico,2)); ?>" class="float" rel="2,2" <?=$readonly?>/><br />
        
        <label>Glicose <small>(mg glicose/dl)</small>:</label>
	<input type="text" name="glicose" value="<?= $this->escape(number_format($this->dados->si_glicose,2)); ?>" class="float" rel="2,2" <?=$readonly?>/><br />

	<label>Outras informações:</label>
	<div class="textarea">
		<textarea name="obs" class="tinymce" <?=$readonly?>><?= $this->escape($this->dados->si_dados);?> </textarea>
		
	</div>

	<?php if (!$this->bloquear && !$this->readonly): ?>
		<div class="space"></div>
		<div class="clear"></div>

		<a href="#" class="ui-button salvar">Salvar</a>
		<a href="#" class="ui-button limpar">Limpar</a>
	
	<?php endif; ?>
	<div class="clear"></div>
</form>

