<?php $this->dialog(); ?>
<form method="post" action="<?= $this->url(array("action" => "salvar")); ?>">
	<?php $this->errorMsg(); ?>
	<label>Conduta do Tratamento: </label>
	<input type="hidden" name="io_codigo" id="io_codigo" value="<?= $this->dados->io_codigo; ?>">
	<input type="hidden" name="ate_codigo" id="ate_codigo" value="<?= $this->ate_codigo; ?>">
	<div class="textarea">
            <textarea name="io_observacao" class="tinymce"><?= $this->dados->io_observacao; ?></textarea>	
	</div>
        <div style="float:right; margin-right:236px; width: 300px; height: 140px;">
            <? $action = $this->url(array("module"=>"prontuario","controller"=>"ficha","action"=>"internacao-hospitalar","id"=>$this->ate_codigo)); ?>
            <a href="<?=$action?>" class="ui-button detalhes popup" rel="840x827">Ficha de internação hospitalar</a>
            <? $action = $this->url(array("module"=>"prontuario","controller"=>"ficha","action"=>"internacao","id"=>$this->ate_codigo)); ?>
            <a href="<?=$action?>" class="ui-button detalhes popup" rel="750x700">Ficha de encaminhamento</a><br />    
        </div>
        <br />
	<label>Tipo de Encaminhamento</label>
	<?php
	if ($this->escape($this->dados->io_status) == "" || $this->escape($this->dados->io_status) == null) {
		$checked = "checked=checked";
	}
	?>
	<input type="radio" name="io_status" id="io_status" value="O" <?= $checked ?> <?= ($this->escape($this->dados->io_status) == "O" ? "checked=checked" : "") ?>>Observação
	<input type="radio" name="io_status" id="io_status" value="I" <?= ($this->escape($this->dados->io_status) == "I" ? "checked=checked" : "") ?>>Internação

	<div class="space"></div>
	<a href="#" class="ui-button salvar">Salvar</a>
	<a href="#" class="ui-button limpar">Limpar</a>

	<div class="space"></div>
	<? if ($this->dados->io_codigo): ?>
		<?= $this->action("ver", "medicamentos", "leito", array("obs" => "S", "io_codigo" => $this->dados->io_codigo, "ate_codigo" => $this->ate_codigo, "prontuario" => "S")); ?>
	<? endif; ?>
</form>
