<?php $this->errorMsg(); ?>
<?php echo $this->action("form","buscar");?>
<table class="grid ui-widget ui-widget-content ui-corner-all" width="100%">
    	
<?php 
$i=0;
if($this->itens && $this->itens->count()):
foreach($this->itens as $item): ?>
        <?php if($i < 1) :?>
            <tr class="ui-widget-header">
		<th>Categoria</th>
		<th>Opções</th>
            </tr>
        <?php $i++; endif;?>
        <tr>
            <td class="ui-state-default"><?=$this->escape($item->lgc_descricao);?></td>
            <td class="ui-state-default c" width="100">
                <a href="<?=$this->url(array("controller"=>"categoria","action"=>"editar","id"=>$item->lgc_codigo));?>" class="editar"><img src="<?=$this->baseUrl('/public/images/icons/editar.png');?>" alt="Editar" title="Editar" /></a>
                <a href="<?=$this->url(array("controller"=>"categoria","action"=>"excluir","id"=>$item->lgc_codigo));?>" class="excluir"><img src="<?=$this->baseUrl('/public/images/icons/excluir.png');?>" alt="Excluir" title="Excluir" /></a>
            </td>
        </tr>
<?php endforeach; ?>
</table>
<?php else:?>
        <em>Nenhum item encontrado</em>
<?php endif;?>
