<?php
    session_start();
?>


<div id='message' class='ui-state-error' style="display: none"></div><br>
<form method="post" name="form" id="form" action="#">
    <input type="hidden" id="man_exc" name="man_exc" value="0" />
    <input type="hidden" name="uni_codigo" id="uni_codigo" value="<?=$_SESSION[logon][usr]->uni_codigo?>">
    <input type="hidden" name="data_atual" id="data_atual"  value="<?=date("d/m/Y")?>"><br>
    <input type="hidden" name="conv_codigo" id="conv_codigo" value="">
    <input type="hidden" name="coni_codigo" id="coni_codigo" value="">
    <input type="hidden" name="usr_codigo" id="usr_codigo" value="">
    <input type="hidden" name="codigo_convenio" id="codigo_convenio" value="<?=$_SESSION[logon][usr]->uni_codigo?>">
    <label>Profissional: </label>
    <select id="usuarios" name="usuarios">
        <option value="">Selecione</option>
    </select><br>
    <div id="esp" style="display: none" >
        <label>Especialidade: </label>
        <select id="especialidade" name="especialidade">

        </select>
    </div>
    <label>Data Consulta:</label>
    <input type="text" name="age_data" id="age_data" style="width: 100px" class="data" value="<?=date("d/m/Y")?>"><br>
    <a href="#" class="ui-button detalhes" style="margin-left: 185px;">Listar Pacientes</a>
</form>
<div class="space"></div>
<?//echo "<pre>".print_r($this->itens,1);exit;?>
<div id="msg" title="Cancelar Agendamento" style="display: none">
	<input type="radio" name="falta" checked="checked" value="M" id="falta-m" /> <label for="falta-m">Falta Médica</label><br />
	<input type="radio" name="falta" value="F" id="falta-p" /> <label for="falta-p">Paciente Ausentou-se</label><br />
	<input type="radio" name="falta" value="C" id="falta-c" /> <label for="falta-c">Cancelar agendamento</label>
</div>

<div id="tabela" style="display: none;">
    <table class="grid ui-widget ui-widget-content ui-corner-all lista sortable" id="tabelaPac" width="100%">
            <tr class="ui-widget-header"  >
                    <th><input type="checkbox" name="tudo" id="tudo" onclick="checar()" onchange='habalitaDesabilita()' /></th>
                    <th style="width:10px">Qtd</th>
                    <th>Prontuário</th>
                    <th>Paciente</th>
                    <th>Idade</th>
                    <th>Telefone</th>
                    <th>Mãe</th>
                    <th>Horário</th>
                    <th>Situação</th>
                    <th>Estratificação</th>           
                    <th>Encaixe</th>           
                    <th>Opções</th>
            </tr>
            <tbody>
                
            </tbody>
    </table>
    <br />
    <?/*<div id="legenda">
        <div class="marcada"></div> Agendado
        <div class="transferir_agendamento"></div> Transferir Agendamento
    </div>*/?>
    <br />
    <div style="border:0px solid; text-align:center; margin-top: 5px">
        <a  href="#" class="ui-button excluir3 click" onclick="modal()" >Cancelar Agendamento</a>
        <a  href="#" class="ui-button transferir" onclick="carregaListaAgendados($('#coni_codigo').val(),$('#age_data').val(),$('#usr_codigo').val());">Transferir Agendamento</a>
        <a  href="#" class="ui-button imprimir imprimir-pacientes" >Imprimir Pacientes</a>
     </div>
</div>
		
