<?php if (isset($this->itens) && $this->itens && $this->itens->count()): ?>
	<table class="grid ui-widget ui-widget-content ui-corner-all" width="100%">
		<tr class="ui-widget-header">
			<th width="80">Entrega</th>
			<th>Solicitado por</th>
			<th>Procedimento</th>
			<th>Laboratório</th>
			<th width="60">Opções</th>
		</tr>
		<?php foreach ($this->itens as $item): ?>
			<tr>
				<td class="ui-state-default c"><?= $this->data($item->mlz_datadacoleta); ?></td>
				<td class="ui-state-default"><?= $this->escape($item->usr_nome); ?></td>
				<td class="ui-state-default"><?= $this->escape($item->proc_nome); ?></td>
				<td class="ui-state-default"><?= $this->escape($item->lab_nome); ?></td>
				<td class="ui-state-default c">
					<a href="<?= $this->url(array("controller" => "exame", "action" => "ver", "id" => $item->itx_codigo)); ?>" title="Resultado do Exame" class="modal" rel="630x400"><img src="<?= $this->baseUrl('/public/images/icons/historico.png'); ?>" alt="Ver detalhes" title="Ver detalhes" /></a>
					<a href="/WebSocialSaude/laudos/print_laudos.php?datacoleta=<?=$this->data($item->mlz_datadacoleta);?>&itx_codigo[]=<?=$item->itx_codigo;?>&p_codigo[]=<?=$item->proc_codigo;?>&cad_exame=<?=$item->cad_exame;?>&proc_nome=<?=$item->proc_nome;?>&proc_codigo[<?=$item->proc_codigo;?>]=<?=$item->proc_codigo;?>" class="popup" rel="850x650"><img src="<?= $this->baseUrl('/public/images/icons/imprimir.png'); ?>" alt="Imprimir" title="Imprimir" /></a>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
<?php else: ?>
	<br /><em>Nenhuma consulta encontrada.</em>
<?php endif; ?>