<form method="post" id="rel-ranking-consumo" action="<?=$this->url(array("action"=>"rel-ranking-consumo"));?>" target="_blank">
	<input name="filtro" id="filtro" type="hidden" value="s" />
	<label>Setor:</label>
	<input name="set_nome" id="set_nome" />
        <input name="set_codigo" id="set_codigo" type="hidden"/><br />
        <label>Quantidade:</label>
	<input name="quantidade" id="quantidade" /><br/>
	<label>Data inicial:</label>
	<input name="data_inicial" id="data_inicial" class="data" style="width: 80px"/><br />
	<label>Data final:</label>
	<input name="data_final" id="data_final" class="data" style="width: 80px" /><br />
        <label>Subgrupo</label>
        <select name="pros_codigo" id="pros_codigo">
            <option value="">--SELECIONE--</option>
            <?foreach($this->subgrupos as $subgrupo):?>
                <option value="<?=$subgrupo->pros_codigo?>"><?=$subgrupo->pros_descricao?></option>
            <?endforeach;?>
        </select>
	<div class="clear"></div>
	<a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;" class="popup" rel="600x500">Gerar Relatório</a>
</form>