<form method="post" id="rel-curva-abc" action="<?=$this->url(array("action"=>"rel-curva-abc"));?>" target="_blank">
	<input name="filtro" id="filtro" type="hidden" value="s" />
	<label>Setor:</label>
	<input name="set_nome" id="set_nome" />
        <input name="set_codigo" id="set_codigo" type="hidden"/><br />
	<label>Data inicial:</label>
	<input name="data_inicial" id="data_inicial" class="data" style="width: 80px"/><br />
	<label>Data final:</label>
	<input name="data_final" id="data_final" class="data" style="width: 80px" /><br />
	<div class="clear"></div>
	<a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;" class="popup" rel="600x500">Gerar Relatório</a>
</form>