<?php $this->dialog(); ?>
<?php echo $this->action('form','buscar');?>
<table class='grid ui-widget ui-widget-content ui-corner-all' width='100%'>
    <tr class='ui-widget-header'>
           <th>Veículo</th>
           <th>Placa</th>
           <th>Tipo de Veiculo</th>
           <th>Tipo Combustivel</th>  
           <th>Capacidade</th>
           <th>Situação</th>            
           <th>Opções</th>
       </tr>
<?php
$i=0;
if($this->itens && $this->itens->count()):
foreach($this->itens as $item):?>     
        <tr>
            <td class='ui-state-default' width='150'><?=$this->escape($item->vei_descricao);?></td>
            <td class='ui-state-default c' width='150'><?=$this->escape($item->vei_placa);?> </td>
            <td class='ui-state-default c' width='80'><?=$this->escape($item->veie_descricao);?></td>
            <td class='ui-state-default c' width='80'><?=$this->escape($item->veic_descricao);?></td>
            <td class='ui-state-default c' width='80'><?=$this->escape($item->vei_capacidade);?></td>
            <td class='ui-state-default c' width='80'><?=$this->escape($item->veis_descricao);?></td>
            <td class='ui-state-default c' width='80'>
                <input type="hidden" name="id" id="id" value="<?=$item->vei_codigo?>">
                <a href='<?=$this->url(array("module"=>"transporte", 'controller'=>'veiculo','action'=>'editar','id'=>$item->vei_codigo), NULL, TRUE);?>' class='editar'><img src='<?=$this->baseUrl('/public/images/icons/editar.png');?>' alt='Editar Itens' title='Editar Itens' /></a>
                <? if ($item->quantviagem==0) {?>
                <a href=#' id='excluir' onclick="excluir(<?=$item->vei_codigo?>)"><img src='<?=$this->baseUrl('/public/images/icons/excluir.png');?>' alt='Excluir' title='Excluir' /></a>		
                <? } ?>
            </td>
        </tr>
<?php endforeach; ?>
</table>
<?php else:?>
        <em>Nenhum item encontrado</em>
<?php endif;?>
