<body>
    <input type="hidden" name="tipo_mov" id="tipo_mov" value="" onkeypress="duplica();">
    <div id="pai_mov" style="">
        <div id="botoes" >
            <div class="botao_superior" data-tipo="E">
                <img src="<?=$this->baseUrl("/public/images/icons/cart-add-icon.png");?>" alt="Entrada" title="Entrada" />
                <br/>
                <label><b>Entrada</b></label>
            </div>
            <div class="botao_superior" data-tipo="S">
                <img src="<?=$this->baseUrl("/public/images/icons/cart-delete-icon.png");?>" alt="Saida" title="Saida" />
                <br/>
                <label><b>Saída</b></label>
            </div>
            <div class="botao_superior" data-tipo="T">
                <img src="<?=$this->baseUrl("/public/images/icons/cart-go-icon.png");?>" alt="Transferência" title="Transferência" />
                <br/>
                <label><b>Transferência</b></label>
            </div>&nbsp;
            <div class="clear"></div>
            <br/>
            <div class="botao_superior" data-tipo="C">
                <img src="<?=$this->baseUrl("/public/images/icons/counter-count-up-icon.png");?>" alt="Controle Movimentos" title="Controle Movimentos" />
                <br/>
                <label><b>Controle Movimentos</b></label>
            </div>
            <div class="botao_superior" data-tipo="R">
                <img src="<?=$this->baseUrl("/public/images/icons/requisicao.png");?>" alt="Requisição de Materiais" title="Requisição de Materiais" />
                <br/>
                <label><b>Requisição de Materiais</b></label>
            </div>
            <div class="botao_superior" data-tipo="EV">
                <img src="<?=$this->baseUrl("/public/images/icons/envio.png");?>" alt="Envio de Materiais" title="Envio de Materiais" />
                <br/>
                <label><b>Envio de Materiais</b></label>
            </div>
        </div>
       
    </div>
</body>

