<div class="col-20">
<!--<a class="icon-print" onclick="">Imprimir</a>-->
    <a href='javascript: $(this).hide(); self.print(); $(this).show();'>
        <img src='<?=$_SESSION["linkroot"].$_SESSION["comum"];?>/imgs/printer.png' align='absmiddle' border='0'/>
        Imprimir
    </a>
</div>
<div class="center-block" id="contentPage" style="width: 700px; height: auto; min-height: 600px; border: 4px solid black; background: #fff">
    <div class="header">
        <div class="col-50 pull-right">
            <img src="/WebSocialSaude/zf/public/images/logo-do-sus.jpg" width="120" class="img-responsive">
        </div>
        <div class="col-50">
            <div style="padding-left: 5px;" class="text-p-reduced">
                <p class="text-bold">Sistema Único de Saúde</p>
                <p class="text-bold">Ministério da Saúde</p>
                <p class="text-bold">Secretaria de Estado da Saúde</p>
            </div>
        </div>
    </div>
    <div class="space"></div>
    <div class="sub-header black" style="border: 5px ridge #BBB; line-height: 0;">
        <p class="text-center font-16 text-bold">COMPONENTE ESPECIALIZADO DA ASSISTÊNCIA FARMACÊUTICA</p>
    </div>
    <div class="sub-header" style="background: #ddd;">
        <p class="text-bold text-center" style="margin: 0; vertical-align: middle; line-height: 32px">LAUDO DE SOLICITAÇÃO, AVALIAÇÃO E AUTORIZAÇÃO EM MEDICAMENTO(S)</p>
    </div>
    <div class="center-block">
        <p class="text-bold font-16 text-center" style="margin: 5px 0 -15px 0;">AVALIAÇÃO TÉCNICA</p>
    </div>
    <div class="col-100">
        <div class="col-70">
            <fieldset class="radius" style="height: 30px">
                <legend>1 - Nome do Paciente</legend>
                <input type="text" id="nomePaciente" style="background: transparent; color: #000; border: none; outline: none; width: 100%;" autofocus placeholder="Informe o nome do paciente" />
            </fieldset>
        </div>
        <div class="col-30">
            <fieldset class="radius" style="height: 30px">
                <legend>2 - CNS</legend>
                <p id="cnsPaciente" style="margin: 1px 0"></p>
            </fieldset>
        </div>
    </div>
    <div class="col-100">
        <div class="col-75">
            <ul class="medList" style="border: 2px solid #000; margin-left: 10px; border-radius: 20px;" data-li="1">
                <div class="text-center">
                    <span class="text-center font-16 text-bold"><small>3</small> - Código(s)/Medicamento(s)</span>
                </div>                
                <li style="line-height: 25px; height: 25px; border-top: 2px solid black" class="li_1">
                    <div class="text-center" style="float: left; min-height: 1px; border-right: 2px solid black; width: 20px;">
                        <counter>1</counter>
                    </div>
                    <div class="text-center" style="float: left; min-height: 1px; border-right: 2px solid black; width: calc(35% - 25px);">
                        <input type="text" class="codMed text-center" onkeypress='buscarCodigo(this); return event.charCode >= 48 && event.charCode <= 57; ' inputmode="numeric" pattern="[0-9]*" id="codMed_1" placeholder="Código do remédio" class="text-center" style="outline: none; background-color: transparent; color: #000; border: none; width: 100%;">
                    </div>
                    <div class="text-center" style="float: left; min-height: 1px; width: calc(65% + 1px);" onmouseover="this.children[0].value != '' ? $('.exclude_1').show() : ''" onmouseleave="$('.exclude_1').hide()">
                        <input type="text" class="nomeMed" placeholder="Nome do medicamento" onkeyup="buscarMedicamento(this)" style="width: 90%; outline: none; background-color: transparent; border: none; margin: 0 15px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                        <img src="/WebSocialSaude/zf/public/images/icons/excluir.png" onclick="javascript: excluirLi($(this).parent().parent())" class="exclude_1" title="Excluir Medicamento" alt="Clique aqui para excluir o medicamento" style="float: right; cursor: pointer; width: 10px; right: 5px; margin-top: -16px; display: none; z-index: 999; position: absolute">
                    </div>
                </li>
            </ul>
        </div>
        <div class="col-25 center-block">
            <div class="center-block" style="width: 85%; border: 2px solid black; border-radius: 10px; height: 30px; margin-top: 80px">
                <div class="col-40 text-center" style="height: 100%">
                    <span class="text-bold font-10" style="vertical-align: middle; line-height: 30px;"><small>4 - </small>CID-10</span>
                </div>
                <div class="col-60" style="border-left: 2px solid black; height: 100%">
                    <br>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="">
        <img class="img-responsive" src="/WebSocialSaude/zf/public/images/ficha.png" style="height: 505px" />
    </div>
    <div style="height: 3px; background-color: #000; width: 100%; margin-top: 5px; margin-bottom: 5px;"></div>
    <div>
        <img class="img-responsive" src="/WebSocialSaude/zf/public/images/ficha-autorizacao.png" />
    </div>
</div>
<script>
    $("#nomePaciente").buscar({
        url: baseUrl + '/default/paciente/buscar-usuarios',
        minLength: 3,
        template: function (ul, item) {
            return $("<li/>").data("item.autocomplete", item).append("<a>" + item.label + "</a>").appendTo(ul)
        },
        callback: function (el, i) {
            $("#cnsPaciente").text(i.item.data.usu_cartao_sus)
            return true
        }
    })

    function buscarCodigo(elem){
        $(elem).buscar({
            url: baseUrl + '/default/produto/busca-remedio-codigo',
            template: function (ul, item) {
                return $("<li/>").data("item.autocomplete", item).append(
                "<a>" + item.pro_codigo + "</a>").appendTo(ul)
            },
            callback: function (el, i) { 
                var count = 0
                
                count = parseInt($(".medList").attr('data-li'))

                $(".medList .li_"+(count)+" input.nomeMed").val(i.item.pro_nome)
                
                $(elem).val(i.item.pro_codigo)

                $(".medList").append(`
                <li style="line-height: 25px; height: 25px; border-top: 2px solid black" class="li_${count+1}">
                    <div class="text-center" style="float: left; min-height: 1px; border-right: 2px solid black; width: 20px;">
                        <counter>${count+1}</counter>
                    </div>
                    <div class="text-center" style="float: left; min-height: 1px; border-right: 2px solid black; width: calc(35% - 25px);">
                        <input type="text" name="cod_medicamento" class="codMed text-center" onkeypress='buscarCodigo(this); return event.charCode >= 48 && event.charCode <= 57;' inputmode="numeric" pattern="[0-9]*" placeholder="Código do remédio" class="text-center" style="outline: none; background-color: transparent; color: #000; border: none; width: 100%;">
                    </div>
                    <div class="text-center" style="float: left; min-height: 1px; width: calc(65% + 1px);" onmouseover="this.children[0].value != '' ? $(this).find('img').show() : ''" onmouseleave="$(this).find('img').hide()">
                        <input type="text" class="nomeMed" placeholder="Nome do medicamento" onkeyup="buscarMedicamento(this)" style="width: 90%; outline: none; border: none; background-color: transparent; margin: 0 15px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap">
                        <img src="/WebSocialSaude/zf/public/images/icons/excluir.png" onclick="javascript: excluirLi($(this).parent().parent())" class="exclude_${count+1}" title="Excluir Medicamento" alt="Clique aqui para excluir o medicamento" style="float: right; cursor: pointer; width: 10px; position: absolute; right: 5px; margin-top: -16px; display: none">
                    </div>
                </li>
                `)

                $(".medList").find('li').get(count-1).children[2].children[0].innerText = i.item.pro_nome

                $(".medList").attr("data-li", count+1)
                
                return true
            }
        })
    }

    function buscarMedicamento(elm){
        $(elm).buscar({
            url: baseUrl + '/default/produto/medicamento-controlados',
            minLength: 3,
            template: function (ul, item) {
                return $("<li/>").data("item.autocomplete", item).append(
                "<a>" + item.label + "</a>").appendTo(ul)
            },
            callback: function (el, i) {
                
                var count = parseInt($(".medList").attr('data-li'))
                
                $(elm).parent().parent().get(0).children[1].children[0].value = i.item.data.pro_codigo

                $(".medList").append(`
                <li style="line-height: 25px; height: 25px; border-top: 2px solid black" class="li_${count+1}">
                    <div class="text-center" style="float: left; min-height: 1px; border-right: 2px solid black; width: 20px;">
                        <counter>${count+1}</counter>
                    </div>
                    <div class="text-center" style="float: left; min-height: 1px; border-right: 2px solid black; width: calc(35% - 25px);">
                        <input type="text" name="cod_medicamento" class="codMed text-center" onkeypress='buscarCodigo(this); return event.charCode >= 48 && event.charCode <= 57;' inputmode="numeric" pattern="[0-9]*" placeholder="Código do remédio" class="text-center" style="outline: none; background-color: transparent; color: #000; border: none; width: 100%;">
                    </div>
                    <div class="text-center" style="float: left; min-height: 1px; width: calc(65% + 1px);" onmouseover="this.children[0].value != '' ? $(this).find('img').show() : ''" onmouseleave="$(this).find('img').hide()">
                        <input type="text" class="nomeMed" placeholder="Nome do medicamento" onkeypress="buscarMedicamento(this)" style="width: 90%; outline: none; border: none; background-color: transparent; margin: 0 15px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap">
                        <img src="/WebSocialSaude/zf/public/images/icons/excluir.png" onclick="javascript: excluirLi($(this).parent().parent())" class="exclude_${count+1}" title="Excluir Medicamento" alt="Clique aqui para excluir o medicamento" style="float: right; cursor: pointer; width: 10px; right: 5px; position: absolute; margin-top: -16px; display: none">
                    </div>
                </li>
                `)

                $(".medList").attr("data-li", count+1)

                return
            }
        })
    }

    function excluirLi(li){

        var c = parseInt($(li).find('counter').text())

        var count = parseInt($(".medList").attr('data-li'))

        if(count > 1){
            $(li).remove()
            
            $(".medList li").each((i, el) => {
                $(el).attr("class", "")
                $(el).addClass("li_"+(i+1))
                $(el).find('img').attr("class", "").addClass("exclude_"+(i+1))
                
                $(el).find('counter').text(i+1)
            })
            
            $(".medList").attr("data-li", count-1)

            return
        }
    }
</script>