<form method="post" id="form-num-paciente-atendido-por-medicamentos" action="<?=$this->url(array("action"=>"num-pacientes-atendidos-por-medicamento-dispensado"));?>" target="_blank">
    <label>Setor:</label>
    <input name="set_nome" id="set_nome" />
    <input name="set_codigo" id="set_codigo" type="hidden" /><br />
    <label>Produto:</label>
    <input name="pro_nome" id="busca_produtos" />
    <input name="pro_codigo" id="pro_codigo" type="hidden" /><br />
    <label>Data inicial:</label>
    <input name="data_inicial" id="data_inicial" class="data" style="width: 100px"/><br />
    <label>Data final:</label>
    <input name="data_final" id="data_final" class="data" style="width: 100px" /><br />
    <div class="clear"></div>
    <a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;">Gerar Relatório</a>
</form>