<form method="post" action="<?= $this->url(array("action" => "relatorio")); ?>" target="_blank" id="form">
    <input name="tipo" id="tipo" type="hidden" value="<?=$this->action?>"/><br />
	<label>Setor:</label>
	<input type="text" id="set_nome" name="set_nome" value="<?=($this->dados->set_nome); ?>" class="focus" />
	<input type="hidden" id="set_codigo" name="set_codigo" value="" />
        <br/>
	<label>Data inicial:</label>
	<input name="data_inicial" class="data" style="width: 80px"/><br />
	
	<label>Data final:</label>
	<input name="data_final" class="data" style="width: 80px" /><br />
        
        <div class="clear"></div>
        <a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;">Gerar Relatório</a>
	
</form>