<style type="text/css">
<!--
.style1 {
    font-family: Verdana, Arial, Helvetica, sans-serif;
    font-size: 14px;
}
.style2 {
    font-family: Verdana, Arial, Helvetica, sans-serif;
    font-size: 18px;
}
.break { page-break-before: always; }
-->
</style>
</head>

<body>
<?php 
echo "<center><h2>Entradas e Saidas</h2></center><br><br>";
echo "<table width=100% cellspacing=0 cellpadding=0 border=0>
        <tr>
         <td><b>Estado:</b>".$this->sec->sec_sigla."</td>
         <td><b>Muncipio:</b>".$this->sec->nome_cidade."</td>
        </tr>
        <tr>
         <td colspan=2><b>Periodo Selecionado : </b>".$this->params[0]." <b>a</b> ".$this->params[1]."</td>
        </tr>
        <tr>
         <td colspan=2><b>Estabelecimento de Saude : </b>".$this->sec->nome_secretaria."</td>
        </tr>
        </table><br>";
?>
<table width="100%" height="40" border="0" cellspacing="2" cellpadding="5">
  <tr>
    <td bgcolor="#D7D7D7"><span class="style5">Produto</span></td>
    <td width="100" height="40" bgcolor="#D7D7D7"><div align="center" class="style5">Qtd Entrada </div></td>
    <td width="100" bgcolor="#D7D7D7"><div align="center" class="style5">Valor Entrada </div></td>
    <td width="100" bgcolor="#D7D7D7"><div align="center" class="style5">Qtd Saida </div></td>
    <td width="100" bgcolor="#D7D7D7"><div align="center" class="style5">Valor Saida </div></td>
    <td width="130" bgcolor="#D7D7D7"><div align="center" class="style5">Qtd Dispensada </div></td>
    <td width="130" bgcolor="#D7D7D7"><div align="center" class="style5">Valor Dispensado </div></td>
    <td width="130" bgcolor="#D7D7D7"><div align="center" class="style5">Qtd Est. Atual </div></td>
  </tr>
  <?php 
        foreach ($this->dados as $k) { 
            $bgcolor = ($bgcolor=='F5F5F5')?"FAF0F0":"F5F5F5";
            $total_entrada += $k->entrada;
            $total_saida += $k->saida;
            $total_dispensada += $k->dispensada;
            $total_saldo += $k->saldo;
            $cal_entrada = ($k->valor_produto*$k->entrada);
            $cal_dist = ($k->valor_produto*$k->dispensada);
            $cal_saida = ($k->valor_produto*$k->saida);

            $total_cal_entrada += ($k->valor_produto*$k->entrada);
            $total_cal_dist += ($k->valor_produto*$k->dispensada);
            $total_cal_saida += ($k->valor_produto*$k->saida);
  ?>
  <tr>
    <td height="40" bgcolor='<?=$bgcolor?>'><span class="style5"><?=$k->pro_nome?></span></td>
    <td width="100" bgcolor='<?=$bgcolor?>'><div align="center" class="style5"><?=number_format($k->entrada, 0, ',', '.')?></div></td>
    <td width="100" bgcolor='<?=$bgcolor?>'><div align="center" class="style5">R$ <?=number_format($cal_entrada, 2, '.', ',')?></div></td>
    <td width="100" bgcolor='<?=$bgcolor?>'><div align="center" class="style5"><?=number_format($k->saida, 0, ',', '.')?></div></td>
<td width="100" bgcolor='<?=$bgcolor?>'><div align="center" class="style5">R$ <?=number_format($cal_saida, 2, '.', ',')?></div></td>
        <td width="130" bgcolor='<?=$bgcolor?>'><div align="center" class="style5"><?=number_format($k->dispensada, 0, ',', '.')?></div></td>
    <td width="130" bgcolor='<?=$bgcolor?>'><div align="center" class="style5">R$ <?=number_format($cal_dist, 2, '.', ',')?></div></td>
    <td width="130" bgcolor='<?=$bgcolor?>'><div align="center" class="style5"><?=number_format($k->saldo, 0, ',', '.')?></div></td>
  </tr>
 <? } ?> 
  <tr>
    <td height="40" align="right"><span class="style5">TOTAL:</span></td>
    <td width="100"><div align="center" class="style5"><?=number_format($total_entrada, 0, ',', '.')?></div></td>
    <td width="100"><div align="center" class="style5">R$ <?=number_format($total_cal_entrada, 2, '.', ',')?></div></td>
    <td width="100" ><div align="center" class="style5"><?=number_format($total_saida, 0, ',', '.')?></div></td>
    <td width="100"><div align="center" class="style5">R$ <?=number_format($total_cal_saida, 2, '.', ',')?></div></td>
    <td width="130"><div align="center" class="style5"><?= number_format($total_dispensada, 0, ',', '.')?></div></td>
    <td width="130" ><div align="center" class="style5">R$ <?=number_format($total_cal_dist, 2, '.', ',')?></div></td>
    <td width="130"><div align="center" class="style5"><?=number_format($total_saldo, 0, ',', '.')?></div></td>
  </tr>
</table>
