<div id="page">
	<div id="header">
		<div id="logo">
			<img src="<?= $this->baseUrl('/public/images/brasao.jpg') ?>" title="Logo Prefeitura" />
		</div>
		<div id="titulo">
			<h2>Prefeitura Municipal de <?=$this->dadosSecretaria()->cidade;?></h2>
			<h3>Secretaria Municipal de Saúde</h3>
		</div>
		<div id="barcode">
			<img src="<?= $this->baseUrl() ?>/public/images/codigo_barras.php?codigo=<?= $this->dados->usu->usu_codigo; ?>&lw=1&hi=18" alt="Código de Barras: <?= $this->dados->usu->usu_codigo; ?>" title="Código de Barras: <?= $this->dados->usu->usu_codigo; ?>" />
		</div>
		<div class="clear"></div>
	</div>
	<div id="info">
		<div id="foto">
			<img src="<?= $this->baseUrl('/public/images/sem_foto_' . $this->dados->usu->usu_sexo . '.png') ?>" alt="Foto do Paciente" title="<?= $this->dados->usu->usu_nome; ?>" />
		</div>
		<h2><?= ucwords(strtolower($this->dados->usu->usu_nome)); ?></h2>
		<div class="f">
			<label>Sexo:</label> <span><?= $this->mask($this->dados->usu->usu_sexo, "sexo"); ?></span><br />
			<label>Mãe:</label> <span><?= $this->dados->usu->usu_mae; ?></span><br />
			<label>End.:</label> <span><?= $this->dados->usu->usu_endereco; ?></span><br />
			<label>Profis.:</label> <span><?= $this->dados->usu->usu_ocupacao; ?></span>			
		</div>
		<div class="f l2">
			<label>Data Nasc.:</label> <span><?= $this->data($this->dados->usu->usu_datanasc) . " (" . $this->idade($this->dados->usu->usu_datanasc) . ")"; ?></span><br />
			<label>Est. Civil:</label> <span><?= $this->dados->usu->estado_civil; ?></span><br />
			<label>Telefone:</label> <span><?= $this->mask($this->dados->usu->usu_fone); ?></span><br />
			<label>Cartão SUS:</label> <span><?= $this->dados->usu->usu_cartao_sus; ?></span>
		</div>
		<div class="clear"></div>
		<div class="space"></div>
	</div>
	<div id="relatorio">
		<? if($this->dados->alertas){ ?>
		<h2>Alertas</h2>
			<? if ($this->dados->alertas->count()){ ?>
				<? foreach ($this->dados->alertas as $item){ ?>
					<span><?php echo $item->ale_desc; ?></span><br/>
				<? } ?>
			<? } else { ?>
				<em>Nenhum alerta cadastrado.</em>
			<? } ?>
		<div class="space"></div>
		<? } ?>

		<? if($this->dados->atendimentos){ ?>
		<h2>Consultas</h2>
			<? if ($this->dados->atendimentos->count()){ ?>
				<table>
					<? foreach ($this->dados->atendimentos as $item){ ?>
						<tr>
							<th>Data</th>
							<th>Unidade De Saúde</th>
							<th>Profissional</th>
							<th>Especialidade</th>
							<th>Peso</th>
							<th>Alt.</th>
							<th>P/A</th>
							<th>IMC</th>
						</tr>
						<tr>
							<td><?= $this->data($item->ate_data); ?></td>
							<td><?= $this->escape($item->uni_desc); ?></td>
							<td><?= $this->escape($item->usr_nome); ?></td>
							<td><?= $this->escape($item->esp_nome); ?></td>
							<td><?= $this->mask($item->pc_peso, "empty", "--"); ?></td>
							<td><?= $this->mask($item->pc_altura, "empty", "--"); ?></td>
							<td><?= $this->mask($item->pc_pressao_sistolica, "empty", "--") . "/" . $this->mask($item->pc_pressao_diastolica, "empty", "--"); ?></td>
							<td><?= $this->imc($item->pc_peso, $item->pc_altura); ?></td>
						</tr>
						<tr>
							<td colspan="8"><strong>CID</strong> <?= ($item->cd10_codigo_cid ? $this->escape($item->cd10_codigo_cid . " - " . $item->cd10_descricao) : "<em>Não informado</em>"); ?></td>
						</tr>
						<tr>
							<td colspan="8" class="escape">
								<?= $item->ate_reclamacao; ?>
								<?= $item->ate_exame_fisico; ?>
								<?= $item->ate_diagnostico; ?>
								<?= $item->ate_tratamento; ?>
								<?= $item->ate_curativo; ?>
							</td>
						</tr>
						<tr><td colspan="8">&nbsp;</td></tr>
					<? } ?>
				</table>
			<? } else { ?>
				<em>Nenhuma consulta encontrada.</em>
			<? } ?>
		<? } ?>

		<? if($this->dados->exames) { ?>
		<h2>Exames</h2>
			<? if ($this->dados->exames->count()) { ?>
				<table>
					<tr>
						<th>Procedimento</th>
						<th>Profissional</th>
						<th>Prestador</th>
						<th>Data de Coleta</th>
					</tr>
					<? foreach ($this->dados->exames as $item){ ?>
					<tr>
						<td><?=$item->proc_nome;?></td>
						<td><?=$item->usr_nome;?></td>
						<td><?=$item->lab_nome;?></td>
						<td><?=$this->data($item->mlz_datadacoleta);?></td>
					</tr>
					<? } ?>
				</table>
			<? } else { ?>
				<em>Nenhum exame encontrado.</em>
			<? } ?>
		<? } ?>

		<? if($this->dados->procedimentos){ ?>
		<h2>Procedimentos</h2>
			<? if ($this->dados->procedimentos->count()){ ?>
				<table>
					<tr>
						<th>Data</th>
						<th>Procedimento</th>
						<th>CID</th>
						<th>Profissional</th>
						<th>Especialidade</th>
					</tr>
					<?php foreach ($this->dados->procedimentos as $item) { ?>
					<tr>
						<td><?=$this->data($item->ate_data);?></td>
						<td><?=$item->proc_nome;?></td>
						<td><?=$this->mask($item->cd10_descricao,"empty","--");?></td>
						<td><?=$item->usr_nome;?></td>
						<td><?=$item->esp_nome;?></td>
					</tr>
					<? } ?>
				</table>
			<? } else { ?>
				<em>Nenhum procedimento registrado.</em>
			<? } ?>
		<? } ?>

		<? if($this->dados->medicamentos) { ?>
		<h2>Medicamentos</h2>
			<? if ($this->dados->medicamentos->count()) { ?>
				<table>
					<tr>
						<th>Data</th>
						<th>Unidade</th>
						<th>Medicamento</th>
						<th>Quant.</th>
						<th>Profissional</th>
					</tr>
					<? foreach ($this->dados->medicamentos as $item){ ?>
					<tr>
						<td><?=$this->data($item->mov_data);?></td>
						<td><?=$item->uni_desc;?></td>
						<td><?=$item->pro_nome;?></td>
						<td class="d"><?=number_format($item->ite_quantidade,0);?></td>
						<td><?=$item->usr_nome;?></td>
					</tr>
					<? } ?>
				</table>
			<? } else { ?>
				<em>Nenhum medicamento dispensado.</em>
			<? } ?>
		<? } ?>

		<? if($this->dados->vacinas) { ?>
		<h2>Vacinas</h2>
			<? if ($this->dados->vacinas->count()) { ?>
				<table>
					<tr>
						<th>Data</th>
						<th>Unidade</th>
						<th>Vacina</th>
						<th>Lote</th>
						<th>Dose</th>
					</tr>
					<? foreach ($this->dados->vacinas as $item){ ?>
					<tr>
						<td><?=$this->data($item->vac_data);?></td>
						<td><?=$item->uni_desc;?></td>
						<td><?=$item->pro_nome;?></td>
						<td><?=$item->ite_lote;?></td>
						<td><?=($item->vac_dose<6?$item->vac_dose."&ordf; dose":"Reforço");?></td>
					</tr>
					<? } ?>
				</table>
			<? } else { ?>
				<em>Nenhuma vacina aplicada/preenchida.</em>
			<? } ?>
		<? } ?>
			
		<? if($this->dados->vacinasAprazadas) { ?>
		<h2>Vacinas - Aprazadas</h2>
			<? if ($this->dados->vacinasAprazadas->count()) { ?>
				<table>
					<tr>
						<th>Data</th>
						<th>Unidade</th>
						<th>Vacina</th>
						<th>Dose</th>
					</tr>
					<? foreach ($this->dados->vacinasAprazadas as $item) { ?>
					<tr>
						<td><?=$this->data($item->vac_data);?></td>
						<td><?=$item->uni_desc;?></td>
						<td><?=$item->pro_nome;?></td>
						<td><?=($item->vac_dose<6?$item->vac_dose."&ordf; dose":"Reforço");?></td>
					</tr>
					<? } ?>
				</table>
			<? } else { ?>
				<em>Nenhuma vacina aprazada.</em>
			<? } ?>
		<? } ?>

	</div>
	<div class="clear"></div>
	<div id="footer">
		<span><?= $this->dadosSecretaria()->endereco;?></span>
	</div>
</div>