<?php $this->errorMsg(); 
//echo "<pre>".  print_r($this->itens,1);

if($_GET['error']){
    if($_GET['error'] == "exists"){ ?>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
        <script>
            Swal.fire({
                title: 'Atenção!',
                text: 'Já existe viagem cadastrada neste período.',
                type: 'warning',
                confirmButtonText: 'Ok'
            })
        </script>

    <?}
} else if($_GET['alert']){
    if($_GET['alert'] == "success"){ ?>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
        <script>
            Swal.fire({
                title: 'Sucesso!',
                text: 'Viagem cadastrada com sucesso.',
                type: 'success',
                confirmButtonText: 'Ok'
            })
        </script>

    <?}
}
?>
<?php echo $this->action('form','buscar');?>

<table class='grid ui-widget ui-widget-content ui-corner-all' width='100%'>
    <tr class='ui-widget-header'>
        <th>Data Viagem</th>
        <th>Carro</th>
        <th>Motorista</th> 
        <th>Local de Embarque</th>
        <th>Hora de Embarque</th>
        <th>Opções</th>
    </tr>
<?php
$i=0;
if($this->itens && $this->itens->count()){
    foreach($this->itens as $item){?>
    <tr id="tr<?=$item->via_codigo?>">
        <td class='ui-state-default c' width='50'><?=$this->data($item->via_data_ida);?></td>
        <td class='ui-state-default c' width='80'><?=$this->escape($item->vei_descricao);?></td>  
        <td class='ui-state-default c' width='150'><?=$this->escape($item->usr_nome);?></td>
        <td class='ui-state-default c' width='150'><?=$this->escape($item->via_local);?> </td>
        <td class='ui-state-default c' width='80'><?=$this->escape($item->via_hora);?></td>
        <td class='ui-state-default c' width='80'>
            <a href='<?=$this->url(array("module"=>"transporte", 'controller'=>'viagem','action'=>'editar','id'=>$item->via_codigo), NULL, TRUE);?>' class='editar'><img src='<?=$this->baseUrl('/public/images/icons/editar.png');?>' alt='Editar Itens' title='Editar Itens' /></a>
            <a href='#' id='excluir' onclick="excluir(<?=$item->via_codigo?>)"><img src='<?=$this->baseUrl('/public/images/icons/excluir.png');?>' alt='Excluir' title='Excluir' /></a>		
        </td>
    </tr>
<?  } ?>
</table>
<? 
} else { ?>
    <em>Nenhum item encontrado</em>
<? } ?>