<form method="post" action="<?= $this->url(array("action" => "rel-relatorio-media-atendimentos")); ?>" target="_blank">        
	<label>Data inicial:</label>
	<input name="data_inicial" class="data" style="width: 80px"/><br />
	
	<label>Data final:</label>
	<input name="data_final" class="data" style="width: 80px" /><br />
       
        <label>INE</label>
        <input type='text' name='nu_ine' id="nu_ine" value=""/>
        <input type='hidden' name='co_seq_equipe' id="co_seq_equipe" class="field" value="0"/>
        <br/>
        <div class="clear"></div>
        <a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;" class="popup" rel="500x500">Gerar Relatório</a>
	
</form>