<form method="post" action="<?= $this->url(array("action" => "rel-familia-por-ine")); ?>" target="_blank">        
	<label>Unidade:</label>
	<input name="uni_desc" id="uni_desc"  class="focus"/>
	<input name="uni_codigo" id="uni_codigo" type="hidden" /><br />
	<label>Profissional:</label>
	<input name="usr_nome" id="usr_nome"  class="focus"/>
	<input name="usr_codigo" id="usr_codigo" type="hidden" /><br />
       
        <label>INE</label>
        <input type='text' name='nu_ine' id="nu_ine" value=""/>
        <input type='hidden' name='co_seq_equipe' id="co_seq_equipe" class="field" value="0"/>
        <br/>
        <div class="clear"></div>
        <a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;" class="popup" rel="500x500">Gerar Relatório</a>
	
</form>