<br />
<table>
    <tr>
        <th>Unidade</th>
        <th>Ine</th>  
        <th>Quantidade Domicilio</th>  
        <th>Quantidade Paciente</th>           
    </tr>
 <?php // echo "<pre>".print_r($this->total,1)."aaaaaa";die();?> 
    <tr>
        <td style='text-align:center'><?=$this->total?></td>
        <td style='text-align:center'><?=$this->medicos?></td>   
        <td style='text-align:center'><?=$this->enfermeiros?></td>
    </tr>   

</table>