<form name="busca" method="POST" action="<?= $this->url(array("action" => "inconsistencias")); ?>" id="busca-comum">
    <label class="ui-corner-bl ui-corner-tr">Buscar por UUID:</label>
    <input type="text" name="uuid" /> 
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
</form>
<table style="width: 100%;">
    <tr>
        <th style="width: 5%;"><span style="margin-left: 4px;">ID</span></th>
        <th style="width: 16%"><span style="margin-left: 4px;">Cód. Usuário</span></th>
        <th style="width: 30%"><span style="margin-left: 4px;">Nome</span></th>
        <th style="width: 19%"><span style="margin-left: 4px;">Data de nascimento</span></th>
        <th style="width: 30%"><span style="margin-left: 4px;">Nome da mãe</span></th>
        <th style="width: 10%"><span style="margin-left: 4px;">Opções</span></th>
    </tr>
    <?php if (count($this->dados) > 0) { ?>
        <?php foreach ($this->dados as $dados) { ?>
                <tr class="odd">
                    <td style="width: 5%;"><span style="margin-left: 4px;"><?=$dados->eci_codigo?></span></td>
                    <td style="width: 16%"><span style="margin-left: 4px;"><?=$dados->usu_codigo?></span></td>
                    <td style="width: 30%"><span style="margin-left: 4px;"><?=$dados->usu_nome?></span></td>
                    <td style="width: 19%"><span style="margin-left: 4px;"><?=$this->data($dados->usu_datanasc,Zend_Date::DATE_MEDIUM)?></span></td>
                    <td style="width: 30%"><span style="margin-left: 4px;"><?=$dados->usu_mae?></span></td>
                    <td style="width: 10%">
                        <span style="margin-left: 4px;">
                            <a href="<?=$this->baseUrl();?>/default/paciente/form-paciente/pessoa/<?=$dados->usu_codigo?>">
                                <img src="<?=$this->baseUrl();?>/public/images/icons/editar.png" alt="Editar Item" title="Editar Item">
                            </a>    
                        </span>
                    </td>
                </tr>
        <?php } ?>
    <?php } else {  ?>
            <tr height="26">
                <td style="border: 1px solid #919B9C;" colspan="9">
                    <span style="margin-left: 04px;">Nenhuma inconsistência até o momento!</span>
                </td>
            </tr>
    <?php } ?>
</table>