<form method="post" action="<?= $this->url(array("action" => "rel-custo-viagem")); ?>" target="_blank">
   	<label>Veículo:</label>
	<select name="vei_codigo" id="vei_codigo"> 
		<option value="">TODOS</option>         
		<? foreach($this->veiculo as $veiculo) { ?>
				<option value="<?=$veiculo->vei_codigo;?>"><?=$veiculo->vei_descricao;?></option>         
		<? } ?>		
	</select>
	<br />
	<label>Motorista:</label>
        <select name="usr_codigo" id="usr_codigo"> 
             <option value="">TODOS</option>         
            <?foreach ($this->motorista as $motorista){?>
            <option value="<?=$motorista->usr_codigo?>" <? if ($this->dados->usr_codigo == $motorista->usr_codigo) { echo("selected=\"selected\""); } ?>><?=$motorista->usr_nome?></option>         
            <?}?>           
    </select><br />
    <label>Cidade Destino:</label>
    <input type="text" name="busca1" id="busca1" value="" /><br />
    <input type="hidden" name="cid_codigo" id="cid_codigo" value="">

	<label>Data inicial:</label>
	<input name="data_inicial" class="data" style="width: 80px"/><br />
	<label>Data final:</label>
	<input name="data_final" class="data" style="width: 80px" /><br />
	<div class="clear"></div>
	<a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;" class="popup" rel="500x500">Gerar Relatório</a>
</form>