<form id="relatorioProducaoDiaria" method="post" action="<?= $this->url(array("action" => "producao-diaria")); ?>" target="_blank">
    <input name="tipo" id="tipo" type="hidden" value="<?=$this->action?>"/><br />
	<label>Profissional:</label>
	<input name="usr_nome" id="usr_nome" />
	<input name="usr_codigo" id="usr_codigo" type="hidden" /><br />
        
	<div class="clear"></div>
	<div class="space"></div>
        
	<label>Data Inicial:</label>
	<input name="data_inicial" class="data" style="width: 80px"/><br />
	
	<label>Data Final:</label>
	<input name="data_final" class="data" style="width: 80px" /><br />

        <div class="clear"></div>
        <a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;" 
           title="Para melhor vizualização dos dados, selecione um filtro!" onclick=validarFiltrosRelatorioProducaoDiaria()>Gerar Relatório</a>	
</form>