<div class="space"></div>
<div class="space"></div>
<a href="<?= $this->url(array("controller" => "index", "action" => "index")); ?>" class="editar"><img src="<?= $this->baseUrl('/public/images/consultas/fazeragendamento.png'); ?>" alt="Fazer Agendamento" title="Fazer Agendamento" /></a>
<a href="<?= $this->url(array("module" => "default", "controller" => "agendamento-externo", "action" => "index")); ?>" class="editar"><img src="<?= $this->baseUrl('/public/images/consultas/fazeragendamento_externo.png'); ?>" alt="Fazer Agendamento Externo" title="Fazer Agendamento Externo" /></a>
<a href="<?= $this->url(array("module"=>"agenda", "controller" => "convenio", "action" => "agendamento-estabelecimentos-de-saude")); ?>" class="editar"><img src="<?= $this->baseUrl('/public/images/consultas/vinc_est_de_saude_profissionais.png'); ?>" alt="Vínculo Estabelecimentos de Saúdes/Profissionais" title="Vínculo Estabelecimentos de Saúdes/Profissionais" /></a>
<a href="<?= $this->url(array("module"=>"agenda", "controller" => "distribuicao", "action" => "index")); ?>" class="editar"><img src="<?= $this->baseUrl('/public/images/consultas/manutencao_agendamento.png'); ?>" alt="Manutenção e exceção de agendamento" title="Manutenção e exceção de agendamento" /></a>
<a href="<?= $this->url(array("module"=>"agenda", "controller" => "recepcao", "action" => "index")); ?>" class="editar"><img src="<?=$this->baseUrl('/public/images/consultas/transf_horarios.png');?>" alt="Recepção e Transferência dos horários de agendamento" title="Recepção e Transferência dos horários de agendamento" /></a>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>