<div class="abas">
    <ul class="tabs">
        <li><a href="#tabs2-1">Criar novo grupo</a></li>
        <li><a href="#tabs2-2">Listar Grupo</a></li>
    </ul>
    <div id="tabs2-1">
        <?= $this->action("grupo", "estratificacao","estratificacao"); ?>
    </div>    

    
    <div id="tabs2-2">
        <?= $this->action("apresentar-lista-grupo", "estratificacao","estratificacao"); ?>
    </div>


</div>