<div class="space"></div>

<table class="grid ui-widget ui-widget-content ui-corner-all" width="100%" id="grade">
	<?php echo $this->thTabelaData($this->data_inicial, $this->data_final); ?>
	<?php foreach($this->vagas as $coni_codigo => $dias): // para cada exame ?>
	<tr>
		<th class="ui-widget-header" style="font-size: 10px; max-width: 200px">
			<?=trim($this->nomeProcs[$coni_codigo]);?>
		</th>
		<th style="width: 20px">
                    <input readonly="readonly" type="text" style="width:60px;font-size: 10px;" name="coni[<?=$coni_codigo;?>]" value="" id="coni_<?=$coni_codigo;?>" class="hidden-coni" data-coni="<?=$coni_codigo;?>" />
		</th>
		<?php $index = 0; foreach($dias as $dia => $vagas): // para cada dia ?>
		<td class="c <?=($vagas==0?"sem-vaga":"com-vaga");?>" data-dia="<?=$dia;?>" data-coni="<?=$coni_codigo;?>" data-vagas="<?=$vagas;?>" data-index="<?=(++$index);?>">&nbsp;</td>
		<?php endforeach; ?>
	</tr>
	<?php endforeach; ?>
</table>
