<? if ($this->pageCount) { ?>
<div>
<!-- Previous page link -->
<? if (isset($this->previous)) { ?>
    <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
        &lt; Anterior
    </a> |
<?
} else { ?>
    <span>&lt; Anterior</span> |
<?
} ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page) { ?>
    <?php if ($page != $this->current) { ?>
        <a href="<?php echo $this->url(array('page' => $page)); ?>">
            <?php echo $page; ?>
        </a> |
    <?php 
} else { ?>
        <?php echo $page; ?> |
    <?php 
} ?>
<?php 
} ?>
 
<!-- Next page link -->
<?php if (isset($this->next)) { ?>
    <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
        Próximo &gt;
    </a>
<?php 
} else { ?>
    <span>Próximo &gt;</span>
<?php 
} ?>
</div>
<?
} ?>