<?php if(isset($this->itens) && $this->itens && $this->itens->count()): ?>
<table class="grid ui-widget ui-widget-content ui-corner-all" width="100%">
	<tr class="ui-widget-header">
		<th>Data</th>
		<th>Procedimento</th>
		<th>Observação</th>
                <th>Med.Solicitante</th>
                <th width="80">Opções</th>
	</tr>
	<?php foreach($this->itens as $item): ?>
	<tr>
		<td class="ui-widget ui-widget-content c"><?=$this->data($item->dt_requisicao);?></td>
		<td class="ui-widget ui-widget-content"><?=$this->escape($item->proc_nome);?></td>
                <td class="ui-widget ui-widget-content escape"><?=str_replace("<p>&nbsp;</p>","",$item->req_observacao);?></td>
                <td class="ui-widget ui-widget-content"><?=$this->escape($item->usr_nome);?></td>
                <td class="ui-widget ui-widget-content" align="center">
                    <a href="/WebSocialSaude/laudos/laudo2.php?acao=form_add&proc_codigo=<?=$item->proc_codigo;?>&id_login=<?=$this->usr_codigo->usr_codigo?>&usu_codigo=<?=$item->usu_codigo?>&age_codigo=<?=$item->age_codigo?>" class="popup" rel="850x650"><img src="<?= $this->baseUrl('/public/images/icons/historico.png'); ?>" alt="Imprimir" title="Imprimir" /></a>
                </td>
                
	</tr>
	<?php endforeach; ?>
</table>
<?php else: ?>
<br /><em>Paciente não possui histórico de solicitações de exames.</em>
<?php endif; ?>