<?php $this->dialog(); ?>
<?php $this->errorMsg(); ?>
<form name="edita_inc" method="post" action="<?= $this->url(array("action" =>"salvar-edita-inconsistencias")); ?>">
    <input type="hidden" name="age_codigo" value="<?=$this->dados->age_codigo?>" />
    <label>Local de atendimento: </label>
    <?=$this->selectLocais?><br />
    <label>CNS profissional:</label>
    <input name="efp_profissional_cns" class="ui-state-default" value="<?=$this->dados->efp_profissional_cns?>" /><br />
    <label>Data de nasc. profissional:</label>
    <input name="efp_dtnascimento" class="ui-state-default mask" rel='99/99/9999' value="<?=$this->data($this->dados->efp_dtnascimento,Zend_Date::DATE_MEDIUM)?>" /><br />
    <label>CNS paciente:</label>
    <input name="efp_num_cartao_sus" class="ui-state-default" value="<?=$this->dados->efp_num_cartao_sus?>" /><br />
    <label>Sexo:</label>
    <select name="efp_sexo" class='ui-state-default'>
        <option value="0 L" <?=($this->dados->efp_sexo == '0 L' ? 'selected' : '')?>>Masculino</option>
        <option value="1 L" <?=($this->dados->efp_sexo == '1 L' ? 'selected' : '')?>>Feminino</option>
    </select><br />
    <a href="#" class="ui-button salvar">Salvar</a>
    <a href="#" class="ui-button limpar">Limpar</a>
</form>
<div class="space"></div>