<?
echo $this->doctype() . "\n";
$action = Zend_Controller_Front::getInstance()->getRequest()->getControllerName().'/'.Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$cabecalhoDuplo = $action == 'exame/imprimir' ? true : false;
print_r($this->paciente);
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt">
    <head>
        <?= $this->headMeta() . "\n"; ?>
        <?= $this->headTitle() . "\n"; ?>
        <?= $this->headLink() . "\n"; ?>
        <link href='<?=$this->baseUrl('/public/css/paisagem-print.css')?>' rel='stylesheet' type='text/css'></link>
        <script type="text/javascript">
                var baseUrl = '<?=$this->baseUrl();?>';
                $(function(){
                    window.print();
                });
        </script>
        <?= $this->headScript() . "\n"; ?>
        <?= $this->analytics(); ?>
    </head>
    <body>
        <?//=$this->tipo_impressao?>

        <div id="pageprint">
            <!--CABEÇALHO-->
            <div class="cabecalho">
                 <div class="brasao">
                     <img src="<?=$this->baseUrl("/public/images/brasao.gif");?>" height="90" width="100"/>
                 </div>
                 <div class="dados_cabecalho">
                     <b><?=$this->secretaria->nome_secretaria?></b><br/>
                     C.N.P.J.:<?=$this->secretaria->cnpj_secretaria?><br/>
                     <b><?=$this->usr->uni_desc;?></b>
                 </div>
                <div class="cod_bar">
                    <div id="img_bar">
                        <img src="<?=$this->baseUrl()?>/public/images/codigo_barras.php?codigo=<?=$this->dados->codigo;?>&lw=1&hi=18" width="95" alt="Código de Barras: <?=$this->dados->codigo;?>" title="Código de Barras: <?=$this->dados->codigo;?>" width="110" />
                    </div>
                </div>
            </div>
			
			
            <div id="titulo_impressao"><b><?=$this->tipo_impressao;?></b></div>
            <div class="dados_titulo">
                IDENTIFICAÇÃO DO PACIENTE
            </div>
            <div class="identificacao_responsavel">
                <table class="table-dados">
                    <tr>
                        <td width="100" align="right"><b>Pront.| Paciente:</b></td>
                        <td colspan="5"><?=$this->dados->usu_prontuario?> | <?=$this->dados->usu_nome?></td>
                    </tr>
                    <tr>
                        <td width="100" align="right"><b>Idade | Sexo:</b></td>
                        <td><?=$this->idade($this->dados->idade)?> | <?=($this->dados->usu_sexo == "F" ? "Feminino" : "Masculino")?></td>
                        <td width="100" align="right"><b>Dt.Nascimento:</b></td>
                        <td width="60"><?=$this->data($this->dados->usu_datanasc)?></td>
                    </tr>
                    <tr>
                        <td width="100" align="right"><b>CNS:</b></td>
                        <td><?=($this->dados->usu_cartao_sus == "" ? "-" : $this->dados->usu_cartao_sus)?></td>
                        <td width="100" align="right"><b>Dt.Emissão:</b></td>
                        <td width="60"><?=date("d/m/Y");?></td>
                    </tr>
                    <tr>
                        <td width="100" align="right"><b>Endereço:</b></td>
                        <td colspan="3">
				            <?=($this->dados->rua_nome == "" ? "SEM ENDEREÇO" : $this->dados->rua_nome.",")?> <?= $this->dados->dom_numero == 0 ? "S/N" : $this->dados->dom_numero ?> - <?=$this->dados->cid_nome?>
                        </td>
                    </tr>
                </table>
            </div>
            <!--FIM DO CABEÇALHO-->
            <?= $this->layout()->content; ?> <!--???-->
            <!--RODAPE -->
            <div id="footer">
                <div id="assinatura">
                    ____________________________________________<br/>
                    <font face=verdana size=2><b><?=$this->dados->usr_nome?></b><br/>
                    <?=$this->dados->con_descricao.": ".$this->dados->usr_num_conselho. " - ". $this->dados->cnes_sigla_est?></font>
                </div>
                <div id="endereco">
                    <?=$this->secretaria->endereco_secretaria?>, CNPJ:<?=$this->secretaria->cnpj_secretaria?>, FONE:<?=$this->secretaria->telefone_secretaria?>
                </div>
            </div>
            <!--fim do rodapé-->
        </div>
     </body>
</html>