<?= $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt">
    <head>
        <?= $this->headMeta() . "\n"; ?>
        <?= $this->headTitle() . "\n"; ?>
        <?= $this->headLink() . "\n"; ?>
		<script type="text/javascript">
			var baseUrl = '<?=$this->baseUrl();?>';
		</script>
        <?= $this->headScript() . "\n"; ?>
        <?= $this->analytics(); ?>
    </head>
    <body>

		<?= $this->layout()->content; ?>
    </body>
</html>


