<?php $this->dialog(); ?>
<?php $this->errorMsg(); ?>
<link rel="stylesheet" href="/WebSocialSaude/zf/public/css/grid.css?<?=time()?>">
<form method="post" action="<?= $this->url(array("action" => "salvar")); ?><?= ($this->valida ? "/valida/N" : "") ?>"
      id="fichaOdontologica">
    <div class="col-md-12">
        <div class="col-md-6">
            <input type="hidden" name="dt_atend_inicial" value="<?php echo date("d-m-Y"); ?>"/>
            <input type="hidden" name="dt_hora_inicial" value="<?php echo date("h:i"); ?>"/>
            <input type="hidden" id="tipoDoAtendimento" name="tipoDoAtendimento" class="tipoDoAtendimento" value = "FO">
            <input type="hidden" id="tipo_atendimento" value="<?= $this->atendimento->ate_tipo ?>">
            <div style="width: auto;">
                <label >Local:</label>
                <?= $this->selectLocais ?>
                <br/>
                <label >Unidade:</label>
                <input type="text" name="uni_desc" id="uni_desc" tabindex="1"
                       value="<?= $this->dados->uni_desc ? $this->dados->uni_desc : $this->uni_desc_controle ?>"
                       onkeypress="buscaUnidade()"/>
                <input type="hidden" name="uni_codigo" id="uni_codigo"
                       value="<?= $this->dados->uni_codigo ? $this->dados->uni_codigo : $this->uni_codigo_controle ?>">
                <br/>
                <label >Data:</label>
                <?
                $date = new DateTime($this->dados->ate_data);

                ?>
                <input type="text" name="data_atendimento" id="data_atendimento" class="inputDatas field mask data-futura" rel="99/99/9999"
                       tabindex="2" autocomplete="off"
                       value="<?= $this->dados->ate_data ? $date->format('d/m/Y') : $this->data_atendimento_controle ?>"/>
                <input type="hidden" name="data_valida" id="data_valida"/>
                <input type="hidden" name="data_atual" id="data_atual" value="<?= date("d/m/Y") ?>"/>
                <br/>
                <label >Turno:</label> <!-- OBRIGATÓRIO -->
                <select class="ui-state-default" id="turno" name="turno">
                    <option value="1"<?= $this->dados->turno == '1' ? 'selected' : '' ?>>Manhã</option>
                    <option value="2"<?= $this->dados->turno == '2' ? 'selected' : '' ?>>Tarde</option>
                    <option value="3"<?= $this->dados->turno == '3' ? 'selected' : '' ?>>Noite</option>
                </select>
                <br/>
                <label >Paciente:</label>
                <input type="text" name="usu_nome" id="usu_nome" onkeypress="buscaParticipante()"
                       value="<?= $this->dados->usu_nome ?>" tabindex="3"/>
                <input type="hidden" name="usu_codigo" id="usu_codigo" value="<?= $this->dados->usu_codigo ?>">
                <!-- Informações ocultas para atualização dos dados do cidadão -->
                <input type="hidden" name="id_nome" id="id_nome" value="usu_nome"/>
                <input type="hidden" name="id_codigo" id="id_codigo" value="usu_codigo"/>
                <input type="hidden" name="id_data" id="id_data" value=""/>
                <input type="hidden" name="id_button" id="id_button" value=""/>
                <input type="hidden" name="id_tipo" id="id_tipo" value="O"/>
                <input type="hidden" name="usu_sexo" id="usu_sexo" value="" class="ui-state-default">
                <?
                if ($this->ate_codigo) {
                    echo "<input type='hidden' name='ate_codigo' value='$this->ate_codigo' />";
                    echo "<input type='hidden' name='age_codigo' value='" . $this->dados->age_codigo . "' />";
                    echo "<input type='hidden' name='co_rl_cds_atend_odonto_tipo_encam' value='" . $this->dados->co_rl_cds_atend_odonto_tipo_encam . "' />";
                    echo "<input type='hidden' name='co_rl_cds_atend_odont_tip_vig_buc' value='" . $this->dados->co_rl_cds_atend_odont_tip_vig_buc . "' />";
                    echo "<input type='hidden' name='odo_trat_codigo' value='" . $this->dados->odo_trat_codigo . "' />";
                    echo "<input type='hidden' name='odo_pcon_codigo' value='" . $this->dados->odo_pcon_codigo . "' />";
                    echo "<input type='hidden' name='odo_preal_codigo' value='" . $this->dados->odo_preal_codigo . "' />";
                }
                ?>
                <!--end-->
                <div id="perguntaGestante" class="alinhamento" style="display: none;margin-bottom: 4px">
                    <label>Está Gestante?</label>
                    <input class="usu_esta_gestante" name="usu_esta_gestante" id="usu_esta_gestante_true" type="radio" value="T"/>
                        Sim
                    <input class="usu_esta_gestante" name="usu_esta_gestante" id="usu_esta_gestante_false" type="radio" value="F">
                        Não
                </div>
            </div>
            

            
            <div>
                <label style="width: 170px;">Necessidade especial ?</label>
                <input class="usu_possui_necessidade_especial" name="usu_possui_necessidade_especial" id="usu_possui_necessidade_especial" type="radio" value="T"/>
                    Sim
                <input checked class="usu_possui_necessidade_especial" name="usu_possui_necessidade_especial" id="usu_possui_necessidade_especial" type="radio" value="F">
                    Não
            </div>

            <!-- <select class="ui-state-default" id="tipo_busca">
                <option value="">Tipo de Busca</option>
                <option value="N">Nome</option>
                <option value="D">Dt.Nasc</option>
                <option value="M">Mãe</option>
                <option value="C">CNS</option>
                <option value="P">Prontuário</option>
            </select>
            <a href="#" class="ui-button paciente" style="margin-left: 5px;" tabindex="5">Novo / Editar</a><br/> -->
            <label >Profissional:</label>
            <input type="text" id="usr_nome" name="usr_nome" onkeyup="buscaProfissional()" tabindex="4"
                   value="<?= $this->dados->usr_nome ? $this->dados->usr_nome : $this->usr_nome_controle ?>"/>
            <input type="hidden" id="usr_codigo" name="usr_codigo"
                   value="<?= $this->dados->usr_codigo ? $this->dados->usr_codigo : $this->usr_codigo_controle ?>"/><br/>
            <input type="hidden" id="tipo_atendimento" name="tipo_atendimento" value="O"/><br/>

            <div>
                <label for="">Fornecimento Odonto</label>
                <select name="fornecimentoOdonto" id="fornecimentoOdonto">
                    <option value="0">Nenhum </option>
                    <option value="1">Escova dental</option>
                    <option value="2">Creme dental</option>
                    <option value="3">Fio dental</option>
                </select>
            </div>

            <div style="display:none;" id="especialidade">
                <label >Especialidade:</label>
                <input type="hidden" name="esp_codigo_controle" id="esp_codigo_controle"
                       value="<?= $this->dados->esp_codigo ? $this->dados->esp_codigo : $this->esp_codigo_controle ?>"></input>
                <select class='ui-state-default' name="esp_codigo" id="esp_codigo">
                    <?
                    if ($this->dados->esp_codigo) {
                        foreach ($this->especialidades as $row) {
                            echo "<option value='" . $row['esp_codigo'] . "' " . (($this->dados->esp_codigo == $row['esp_codigo']) ? 'selected' : '') . " >" . $row['esp_nome'] . "</option>";
                        }
                    }
                    ?>
                </select>
                <? if ($this->dados->esp_codigo) { ?>
                    <script> $("#especialidade").show(); </script>
                <? } ?>

            </div>
            <label >Procedimentos:</label>
            <input type="text" id="proc_nome" name="proc_nome" value=""
                   tabindex="4" onkeypress="buscaProcedimentos()"/>
            <input type="hidden" id="proc_codigo" name="proc_codigo" value="<?= $this->dados->proc_codigo ?>"/>
            <input type="hidden" id="proc_codigo_sus" name="proc_codigo_sus" value=""/><br/>
            <div id="dadosProcAtendSimp">

                <!-- Aqui o conteúdo é alimentado pelo jQuery -->
                <?php

                $count = 0;

                if ($this->procedimento) {
                    echo "<input id='procedimentos' type='hidden' value = '1'/>";
                } else {
                    echo "<input id='procedimentos' type='hidden'/>";
                }

                foreach ($this->procedimento as $procedimento):
                    $result = true;
                    $visible = 'style="display: none;"';

                    for ($i = 1; $i <= 32; $i++) {
                        $retorno = $retorno . "<option " . ($procedimento['quant'] == $i ? 'selected' : '') . " value='" . $i . "'>" . $i . "</option>";
                    }


                    echo
                        '<div class="procAtendSimp" style="width:60%; display: inline-block;" id="procAtendSimp' . $procedimento['proc_codigo'] . '-' . ($count) . '">
                <span class="titProcAtendSimp">
                    ' . $procedimento['proc_codigo_sus'] . ' - ' . substr($procedimento['proc_nome'], 0, 80) . ' ...
                </span>
                <!--div class="excProcAtendSimp">
                    <img src="' . $this->baseUrl() . '/public/images/icons/excluir.png" onclick="excluiProcedimento(" ' . $procedimento['proc_codigo'] . ')" title="Excluir Procedimento" style="cursor: pointer" />
                    <input type="hidden" name="procedimento[]" value="' . $procedimento['proc_codigo'] . '" />
                </div-->
            </div>
            <div id="divprocAtendSimp' . $procedimento['proc_codigo'] . '-' . ($count) . '" style="width:20px; display: inline-block; vertical-align: middle; padding:0; margin:0;">
                <input style="width:20px;margin-right:10px;text-align: center" type="text" style="20px" id="qtdeComboProcedimento' . $procedimento['proc_codigo'] . '" name="qtdeProc[]" value="' . ($procedimento['quant']) . '" readonly=readonly />
                <input type="hidden" name="procedimento[]" value="' . $procedimento['proc_codigo'] . '" />
            </div><img id="imgprocAtendSimp' . $procedimento['proc_codigo'] . '-' . ($count) . '" style="vertical-align: middle;margin-left:10px;" src="' . $this->baseUrl() . '/public/images/icons/excluir.png" onclick="excluiProcedimento(\'' . $procedimento['proc_codigo'] . '-' . ($count++) . '\')" title="Excluir Procedimento" style="cursor: pointer" />';
                endforeach;

                ?>

            </div>

            <div>
                <label >Procedimentos SIA:</label>
                <select style="width:227px!important"  name="procedimento_odonto_ab_sia" id="procedimento_odonto_ab_sia">
                    <option value="0">Procedimento SIA</option>
                    <?php
                        $recebeProcedimentoOdonto = $this->procedimento_odonto_ab_sia;
                        // echo "<pre>";print_r($recebeProcedimentoOdonto);die();

                        for ($count = 0; $count < count($recebeProcedimentoOdonto) ; $count++) { ?>
                            <option value="<?=$recebeProcedimentoOdonto[$count][proc_codigo]?>">
                                <?=$recebeProcedimentoOdonto[$count][proc_nome]?>
                            </option>
                        <?}
                    ?>
                </select>
            </div>
        </div>

        <div class="col-md-5">
            <div id="divAtendimentoConsulta">
                <fieldset id="fieldsetAtendimento">
                    <legend>
                        Tipo de atendimento:
                        <input type="hidden" name="conf_ta" id="conf_ta" <?= $this->dados->tat_codigo ? 'value=1' : '' ?>/>
                    </legend>

                    <input type="radio" name="tipo_atend" id="tipo_atend"
                           class="ate_tipo_atendimento" <?= ($this->tipoAtendFicha->tat_codigo == $this->dados->tat_codigo) ? "checked" : "" ?>
                           onclick="consultaObrigatoria(this.value);"
                           value="<?= $this->tipoAtendFicha->tat_codigo ?>"/>
                    <?= $this->tipoAtendFicha->tat_tipo ?><br/>

                    <fieldset style="border-radius: 9px;">
                        <legend>Demanda espontânea:</legend>
                        <input type="hidden" id="consultaObrigatoriaHidden" value="">
                        <?php
                        foreach ($this->demandaEspontanea as $val) { ?>
                            <input type="radio" name="tipo_atend" id="tipo_atend"
                                   class="ate_tipo_atendimento" <?= ($val->tat_codigo == $this->dados->tat_codigo) ? "checked" : "" ?>
                                   onclick="consultaObrigatoria(this.value);desabilitaTipoConsulta(this.value);"
                                   value="<?= $val->tat_codigo ?>" /><?= $val->tat_tipo ?><br/>
                            <?php
                        } ?>
                    </fieldset>
                </fieldset>

                <fieldset id="fieldsetConsulta">
                    <legend>
                        Tipo de consulta:
                        <input type="hidden" name="conf_tc" id="conf_tc" <?= $this->dados->tp_cod ? 'value=1' : '' ?>/>
                    </legend>
                    <div id="tipo_consulta">
                        <?php
                        foreach ($this->tipoCons as $val) { ?>
                            <input type="radio" name="tipo_cons" id="tipo_cons<?=$val->tp_cod?>"
                                   class="ate_tipo_atendimento" <?= ($val->tp_cod == $this->dados->tp_cod) ? "checked" : "" ?>
                                   onclick="validaTipoConsulta(this.value);liberarBotao(this.value)"
                                   value="<?=$val->tp_cod?>" />
                                   <p class="nomeProcedimento" id="tipo_cons<?=$val->tp_cod?>Nome"><?=$val->tp_nome?></p>
                                   <br/>
                            <?php
                        } ?>
                    </div>
                </fieldset>
            </div>      
        </div>
        <div class="col-md-11">
            <div id="divVigilanciaConduta">
                <fieldset id="fieldsetVigilancia">
                    <legend>
                        Vigilância em saúde bucal:
                        <input type="hidden" name="conf_vig"
                               id="conf_vig" <?= $this->dados->co_cds_tipo_vig_saude_bucal ? 'value=1' : '' ?> />
                    </legend>
                    <div id="vigilancia">
                        <?php
                        if ($this->codigoFicha == '') {
                            foreach ($this->vigilancia as $val) { ?>
                                <input
                                type="checkbox" <?= ($val->co_cds_tipo_vig_saude_bucal == $this->dados->co_cds_tipo_vig_saude_bucal) ? "checked" : "" ?>
                                name="vigilancia[]"   class="ate_tipo_atendimento" onclick="validaTipoVigilancia()"
                                value="<?= $val->co_cds_tipo_vig_saude_bucal ?>" /><?= $val->no_cds_tipo_vig_saude_bucal ?><br/>
                            <?php }
                        } else {
                            foreach ($this->vigilancia as $val) { ?>
                                <input
                                type="checkbox" <?= ($val->co_rl_cds_atend_odont_tip_vig_buc) ? "checked" : "" ?>
                                name="vigilancia[]"   class="ate_tipo_atendimento" onclick="validaTipoVigilancia()"
                                value="<?= $val->co_cds_tipo_vig_saude_bucal ?>" /><?= $val->no_cds_tipo_vig_saude_bucal ?><br/>
                        <?php }
                        } ?>
                    </div>
                </fieldset>

                <fieldset id="fieldsetConduta">
                    <legend>
                        Conduta:
                        <input type="hidden" name="conf_cond"
                               id="conf_cond" <?= $this->dados->co_cds_tipo_encam_odonto ? 'value=1' : '' ?>/>
                    </legend>
                    <div id="conduta">
                        <?php
                        if ($this->codigoFicha == '') {
                            foreach ($this->conduta as $val) { ?>
                                <input type="checkbox" name="conduta[]"
                                       id="<?= "conduta" . $val->co_cds_tipo_encam_odonto ?>" <?= ($val->co_cds_tipo_encam_odonto == $this->dados->co_cds_tipo_encam_odonto) ? "checked" : "" ?>
                                       class="ate_tipo_atendimento" 
                                       value="<?= $val->co_cds_tipo_encam_odonto ?>" /><?= $val->no_cds_tipo_encam_odonto ?><br/>
                            <?php }
                        } else {
                            foreach ($this->conduta as $val) { ?>
                                <input type="checkbox" name="conduta[]"
                                       id="<?= "conduta".$val->co_cds_tipo_encam_odonto ?>" <?=($val->co_rl_cds_atend_odonto_tipo_encam)?"checked":""?>
                                       class="ate_tipo_atendimento" 
                                       value="<?=$val->co_cds_tipo_encam_odonto?>" /><?=$val->no_cds_tipo_encam_odonto?><br/>
                            <?php }
                        } ?>
                        <fieldset style="border-radius: 9px;">
                            <legend>Encaminhamento</legend>
                            <?php
                            if ($this->codigoFicha == '') {
                                foreach ($this->encaminhamentos as $val) { ?>
                                    <input type="checkbox" name="conduta[]"
                                           id="<?= "conduta" . $val->co_cds_tipo_encam_odonto ?>" <?= ($val->co_cds_tipo_encam_odonto == $this->dados->co_cds_tipo_encam_odonto) ? "checked" : "" ?>
                                           class="ate_tipo_atendimento" 
                                           value="<?= $val->co_cds_tipo_encam_odonto ?>" /><?= $val->no_cds_tipo_encam_odonto ?><br/>
                                <?php }
                            } else {
                                foreach ($this->encaminhamentos as $val) { ?>
                                    <input type="checkbox" name="conduta[]"
                                           id="<?= "conduta".$val->co_cds_tipo_encam_odonto ?>" <?=($val->co_rl_cds_atend_odonto_tipo_encam)?"checked":""?>
                                           class="ate_tipo_atendimento" 
                                           value="<?=$val->co_cds_tipo_encam_odonto?>" /><?=$val->no_cds_tipo_encam_odonto?><br/>
                                <?php }
                            } ?>
                        </fieldset>
                    </div>
                </fieldset>
            </div> 
        </div>
    </div>
    

    <div class="clear"></div>
    <div class="space"></div>
    <div class="space"></div>
    <div id="divBotoesSalvar">
        <a href="#" id="botaoSalvar" class="ui-button salvar">Salvar</a>
        <a href="#" class="ui-button limpar">Limpar</a>
    </div>
    <div class="space"></div>
    <div id="itens"></div>
</form>