<?php $this->dialog(); ?>
<?php $this->errorMsg(); ?>
<form name='upload' action='<?=$this->url(array("action"=>"salvar"))?>' method='post' enctype='multipart/form-data' id="ativ-coletiva">

    <a href="<?=$this->url(array("controller"=>"atividade-coletiva","action"=>"index"));?>"  class="ui-button voltar" data-atalho="ESC">Voltar</a>
    <input type="hidden" name="codFicha" id="codFicha" value="<?=$this->dados->co_cds_ficha_ativ_col?>" />
    <input type="hidden" name="ativCol" id="ativCol" value="1" />
    
    <fieldset>  
        <legend>Local da Atividade</legend>
        <div id="informacoesDosLocais">
            <div id="unidadeSelecionada">
                <label >Unidade :</label>
                <select name="uni_codigo" id="uniCodigo" style="width:300px;" class="ui-state-default">

                    <option value="">Selecione</option>
                     <?php foreach ($this->unidade as $unidade):?>
                           <option class="unidades"
                                <?php if (trim($unidade->uni_codigo) == trim($this->dados->uni_codigo)) { 
                                    echo "selected"; 
                                }?> value="<?=$unidade->uni_codigo?>">
                                <?=$unidade->uni_desc?>
                           </option>
                    <?php endforeach ?>
                </select>
                <br />
            </div>
                
            <div >
            
                <label>Programa Saúde na Escola :</label>
                <div id="programaSaudeEscola">
                    
                    <input type="radio" name="saudeEduacao" id="educacaoEscola"
                           value="educacao"
                    <?= ($this->dados['pse_educacao'] >= 1 ? "checked" : "") ?> 
                    onchange="validacaoPseEducacao()"/>
                    <span>Educação</span>
                        
                        
                    <input type="radio" name="saudeEduacao" id="saudeEscola"
                            value="saude"
                    <?= ($this->dados['pse_saude'] >= 1 ? "checked" : "") ?> onchange="validacaoPseSaude()"/>
                    <span>Saúde</span>    
                    
                </div>
            
            </div>

            <div id="numeroINEP">
                <label class = "numeroDoInep">Nº INEP (escola/creche) :</label>
                <input id="inepDaEscola" type='text' name='num_inep' class="field" style="width: 150px;" value="<?=$this->dados->co_inep_escola?>" onkeypress="return SomenteNumero(event)" />
            </div>
            
            <div id="numeroDeParticipantes">
                <label for="">Programa&ccedil;&atilde;o de nºde Participantes</label>
                <input type='text' name='num_participantes' class="field" style="width: 220px;" onkeypress="return SomenteNumero(event)" value="<?=$this->dados->qt_participante_programado?>" />
            </div>

            <div>
                <label>Turno :</label> <!-- OBRIGATÓRIO -->
                    <select class="ui-state-default" id="turno" name="turno" style="width:100px;">
                        <option value="1"<?= $this->dados->turno == '1' ? 'selected' : '' ?>>Manhã</option>
                        <option value="2"<?= $this->dados->turno == '2' ? 'selected' : '' ?>>Tarde</option>
                        <option value="3"<?= $this->dados->turno == '3' ? 'selected' : '' ?>>Noite</option>
                    </select>
                <br/>
            </div>

            <label>Local das Atividades :</label>
            <div id="outrosLocais" class="textarea">
                <textarea name="ds_local" class="tinymce" style="width: 375px;height: 100px;"><?=trim($this->dados->ds_local_ativ)?></textarea>
            </div>
            
            <div id="nasf-div">
                <label style="width: 110px; float: left;">NASF / Polo: </label>
                <div id="inputsNasf">
                    <br>
                    <input type="checkbox" 
                        <?php if($this->dados->ate_nasf_aval){echo 'checked="checked"';}?>name="ate_nasf_aval" style="margin-left: 1.3%;" /> Avaliação / Diagnóstico 
                    <br />
                    <input type="checkbox" 
                        <?php if($this->dados->ate_nasf_proc){echo 'checked="checked"';}?>name="ate_nasf_proc" style="margin-left: 26%;" /> Procedimentos clínicos / Terapêutico 
                    <br />
                    <input type="checkbox" 
                        <?php if($this->dados->ate_nasf_presc){echo 'checked="checked"';}?>name="ate_nasf_presc" style="margin-left: 26%;" /> Prescrição terapêutica 
                    <br />
                </div>
            </div>

        </div>
        <br>
        <div id="horaEdata">

            <div id="dataDaAtividade">
                <label>Data de Atividade</label>
                <input type='text' name='dt_atividade' id="dt_atividade" class="field mask data-futura"
                       style="width: 125px;" rel="99/99/9999" onchange="validaData(this)"
                       value="<?=$this->data($this->dados->dt_ativ_col,Zend_Date::DATE_MEDIUM)?>" />
            </div>

            <div id="dataInicioDaAtividade">
                <label>Horário de Início</label>
                <input type='text' name='hr_inicio' id="hr_inicio" class="field mask" style="width: 120px;" rel="99:99" onblur="validaHoraInicial()" value="<?=$this->data($this->dados->hr_inicio,Zend_Date::TIME_SHORT)?>" />
            </div>

            <div id="horaFinalDaAtividade">
                <label>Horário de Fim</label>
                <input type='text' name='hr_fim' id="hr_fim" class="field mask" style="width: 120px;" rel="99:99" onblur="validaHoraFinal()" value="<?=$this->data($this->dados->hr_fim,Zend_Date::TIME_SHORT)?>" />
            </div>

        </div>
    </fieldset>
    
    <div id="tableDoProfissional">
        <fieldset>
            <input type="hidden" name="conf_prof" id="conf_prof" value="<?=(count($this->profsEdit) == 0 ? "" : count($this->profsEdit))?>" />

            <div id="nomeDoProfissional">
                <label>Nome do Profissional</label>
                <input type='text' name='profs_part_nome' id="profs_part_nome" onkeypress="buscaProfissionais()" />
                <input type='hidden' name='usr_codigo' id="usr_codigo"class="field" />
            </div>
            
            <div id="td_profs_part_esp">
                <label>Especialidade</label>
                <select name="profs_part_esp" id="profs_part_esp" class="ui-state-default">

                </select>
            </div>

            <div id="td_profs_part_conf">
                <br/>
                <a href="#" class="ui-button" id="enviar" onclick="confirmarProfsPart()">
                    Confirmar
                </a>
            </div>
            
            <table width="100%" id="profs_part" style="border: 1px solid #cef; margin-top: 20px; display: show;">
                <tr>
                    <th width='125'>Profissional</td>
                    <th width='125'>CBO</td>
                    <th width='10'>Ações</td>
                </tr>
                <?php if (count($this->profsEdit)>0) { ?>
                    <?php $i = 0; ?>
                    <?php foreach($this->profsEdit as $val) { ?>
                            <?php $i++; ?>
                            <tr id='profs_part_qtd<?=$i?>'>
                                <td width='125'>
                                    <?=$val["usr_nome"]?>
                                    <input type='hidden' name='profs_part[<?=$i;?>][usr_codigo]' value="<?=$val["usr_codigo"]?>" />
                                </td>
                                <td width='125'>
                                    <?=$val["cbo"]?>
                                    <input type='hidden' name='profs_part[<?=$i?>][cbo]' value="<?=$val["cbo"]?>" />
                                </td>
                                <td width='10'>
                                    <a href='#'>
                                        <img src="<?=$this->baseUrl()?>/public/images/icons/excluir.png" alt="Excluir" title="Excluir" onclick="excluirConfirmacaoResp(<?=$i?>)" />
                                    </a>
                                </td>
                            </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr id="profs_part_qtd0">
                        <td colspan="3">
                            Nenhum profissional registrado até o momento.
                        </td>
                    </tr>
                <?php } ?>
                <input type="hidden" id="profs_part_qtd" value="<?=$i?>" />
            </table> 
        </fieldset>
            
    </div>
    <!-- ATIVIDADE E TEMAS PARA REUNIÃO -->

    <!--  -->

    
    <div class = "divDosSelects">
        <div class="dropdown" data-control="checkbox-dropdown">
            <label style="text-align: left!important;" class="dropdown-label">Atividades </label>
          
            <div class="dropdown-list">

                <!-- <a href="#" data-toggle="check-all" class="dropdown-option">
                  Check All  
                </a> -->
                
                <?php foreach ($this->atividades as $valAtiv ){ ?>
                    <label style="width: 534px!important;text-align: left!important;" for="atividades" class="dropdown-option labelSelects">

                        <input  id = "atividades<?=$valAtiv->co_cds_tipo_ativ_col?>"
                                type="radio" 
                                name="atividades"
                                value="<?=$valAtiv->co_cds_tipo_ativ_col?>"
                                onclick="desabilitaTemasReuniao(); desabilitaPublicoAlvo();
                                         desabilitaTemasParaSaude(); desabilitaPraticasEmSaude();
                                         praticasObrigatórias()"
                                <?=($this->dados->tp_cds_ativ_col==$valAtiv->co_cds_tipo_ativ_col ? "checked" : "")?>         
                        />
                        <?=$valAtiv->no_cds_tipo_ativ_col?>
                    </label>
                <?php } ?>

            </div>
        </div>

    </div>

    <br>

    <div class = "divDosSelects">
        <div class="dropdown" data-control="checkbox-dropdown">
            <label style="text-align: left!important;" class="dropdown-label divTemasParaReuniao labelSelects" >Temas para reunião </label>
      
            <div class="dropdown-list">

                <!-- <a href="#" data-toggle="check-all" class="dropdown-option">
                  Check All  
                </a> -->

               <input   type="hidden" name="conf_temas" id="conf_temas" 
                        value="<?=(count($this->temasEdit) > 0 || $this->dados->tp_cds_ativ_col > 3 ? "1" : "")?>" />

                <?php foreach ($this->temas as $valTemas ){ ?>
                    
                    <label style="width: 534px!important;text-align: left!important;" for="temasParaReuniao" class="dropdown-option labelSelects">

                        <input id = "temasParaReuniao<?=$valTemas->co_cds_ativ_col_tema?>"type="checkbox" 
                               name="temasParaReuniao[]" 
                                value="<?=$valTemas->co_cds_ativ_col_tema?>"
                                
                                <?=($this->validaArray($valTemas->co_cds_ativ_col_tema, $this->temasEdit) >= 1 ? "checked" : "")?>
                        />
                            <?=$valTemas->no_cds_ativ_col_tema?>
                    </label>
                <?php } ?>

            </div>
        </div>
    </div>

    <br>

    <div class = "divDosSelects">
        <div class="dropdown" data-control="checkbox-dropdown">
            <label style="text-align: left!important;" class="dropdown-label divPublicoAlvo labelSelects">Publico alvo </label>
          
            <div class="dropdown-list">

                <!-- <a href="#" data-toggle="check-all" class="dropdown-option">
                  Check All  
                </a> -->

                <input type="hidden" name="conf_pub" id="conf_pub"
                value="<?=(count($this->pubAlvoEdit) > 0 ? count($this->pubAlvoEdit) : "")?>" />

                <?php foreach ($this->pubAlvo as $pubAlvo ){ ?>
                    
                    <label style="width: 534px!important;text-align: left!important;" for="publicoAlvo" class="dropdown-option">

                        <input  id = "publicoAlvo<?=$pubAlvo->co_cds_ativ_col_publico_alvo?>"type="checkbox" 
                                name="publicoAlvo" 
                                value="<?=$pubAlvo->co_cds_ativ_col_publico_alvo?>"
                                <?=($this->validaArray($pubAlvo->co_cds_ativ_col_publico_alvo, $this->pubAlvoEdit) >= 1 ?"checked" : "")?>
                        />
                            <?=$pubAlvo->no_cds_ativ_col_publico_alvo?>
                    </label>
                <?php } ?>

            </div>
        </div>
    </div>

    <br>

    <div class = "divDosSelects">
        <div class="dropdown" data-control="checkbox-dropdown">
            <label style="text-align: left!important;" class="dropdown-label divTemasParaSaude labelSelects">Temas Para Saúde </label>
          
            <div class="dropdown-list">

                <!-- <a href="#" data-toggle="check-all" class="dropdown-option">
                  Check All  
                </a> -->

                <input type="hidden" name="conf_pub" id="conf_pub"
                value="<?=(count($this->pubAlvoEdit) > 0 ? count($this->pubAlvoEdit) : "")?>" />

                <?php foreach ($this->temasSaude as $valTemas ){ ?>
                    
                    <label style="width: 534px!important;text-align: left!important;" for="temasSaude" class="dropdown-option">

                        <input  id = "temasParaSaude<?=$valTemas->co_cds_ativ_col_pratica?>"type="checkbox" name="temasSaude" 
                                value="<?=$valTemas->co_cds_ativ_col_pratica?>"
                                <?=($this->validaArray($valTemas->co_cds_ativ_col_pratica, $this->praticasEdit) >= 1 ?"checked" : "")?>
                        />
                            <?=$valTemas->no_cds_ativ_col_pratica?>
                    </label>
                <?php } ?>

            </div>
        </div>
    </div>

    <br>

    <div class = "divDosSelects">
        <div class="dropdown" data-control="checkbox-dropdown">
            <label style="text-align: left!important;" class="dropdown-label divPraticasParaSaude labelSelects">Praticas </label>
          
            <div class="dropdown-list">

                <!-- <a href="#" data-toggle="check-all" class="dropdown-option">
                  Check All  
                </a> -->

                <input type="hidden" name="conf_pub" id="conf_pub"
                value="<?=(count($this->pubAlvoEdit) > 0 ? count($this->pubAlvoEdit) : "")?>" />

                <?php foreach ($this->praticas as $valPrat ){ ?>
                    <label style="width: 534px!important;text-align: left!important;" for="praticas" class="dropdown-option">

                        <input onclick="habilitaOutroProcedimentoColetivo(); habilitaProgramaNacionalDoTabagismo() " 
                                id = "praticas<?=$valPrat->co_cds_ativ_col_pratica?>"type="checkbox" 
                                name="praticas" 
                                value="<?=$valPrat->co_cds_ativ_col_pratica?>"
                                <?=($this->validaArray($valPrat->co_cds_ativ_col_pratica, $this->praticasEdit) >= 1 ?"checked" : "")?>
                        />
                            <?=$valPrat->no_cds_ativ_col_pratica?>
                    </label>
                <?php } ?>
            </div>
        </div>
    </div>
    
    <br>

    <div class="divDosSelects" id="divOutrosProcedimentosColetivos">
        <div class="dropdown" data-control="checkbox-dropdown">
            <label style="text-align: left!important;" class="dropdown-label labelSelects">Outros Procedimentos Coletivos </label>
          
            <div class="dropdown-list">

                <!-- <a href="#" data-toggle="check-all" class="dropdown-option">
                  Check All  
                </a> -->

                <?php foreach ($this->outrosProcedimentosColetivos as $procedimento ){ ?>
                    <label style="width: 534px!important;text-align: left!important;" class="dropdown-option">

                        <input disabled id = "outrosProcedimentosColetivos<?=$procedimento->proc_codigo?>"
                                type="checkbox" name="dropdown-group" 
                                value="<?=$procedimento->proc_codigo?>" 
                        />
                            <?=$procedimento->proc_nome?>
                    </label>
                <?php } ?>
            </div>
        </div>
    </div>

    <br />

    <div id="divDoResponsavel" width="100%" cellspacing="0" cellpadding="0" border="0">
        <tr>
            <td>
                <fieldset>
                    <legend>Responsável</legend>
                    <table width='100%' cellspacing="0" cellpadding="0" border="0">
                        <tr>
                            <td width='30%'>
                                Profissional Responsável<br>
                                <select id="prof_resp_codigo" name="prof_resp_codigo" class="field" style="width: 292px;">
                                    <option value="">--Selecione--</option>
                                    <?php if (count($this->profsEdit)>0) { ?>
                                        <?php $i = 0; ?>
                                        <?php foreach($this->profsEdit as $val) { ?>
                                                <option value="<?=$val["usr_codigo"]?>" onclick="carregaCnes(<?=$val["usr_codigo"]?>)"
                                                    <?=($this->dados->usr_codigo == $val["usr_codigo"] ? "selected=selected" : "")?>>
                                                    <?=$val["usr_nome"]?>
                                                </option>
                                        <?php } ?>
                                    <?php }?>
                                </select>
                            </td>
                           <td width='14%'>
                                Cód. CNES Unidade<br>
                                <input type="hidden" name="cod_cnes_edit" id="cod_cnes_edit"
                                       value="<?=$this->dados->cod_cnes_unidade?>" />
                                <select name='cod_cnes_uni' id="cod_cnes_uni" style="width:230px;"  class="field">
                                    <option value = "" >Selecione Profissional Responsável</option>
                                </select>
                            </td>
                            <td width='14%'>
                                Cód. equipe(INE)<br>
                                <input type="hidden" name="cod_equipe_ine" id="cod_equipe_ine"
                                       value="<?=$this->dados->cod_equipe_ine?>" />
                                <select name='cod_equipe' id="cod_equipe" style="width:230px;"
                                        class="field" onchange="validaIne()">
                                    <option value="">Selecione Cód. CNES Unidade</option>
                                </select>
                            </td>
                            <td width='14%'>
                                Nº de participantes<br>
                                <input type='text' name='num_particip' id="num_particip"
                                       class="field" style="width: 94%;"
                                       onkeypress="return SomenteNumero(event)"
                                       value="<?=($this->dados->qt_participante_ativ == "" ? "0" : $this->dados->qt_participante_ativ)?>"  />
                            </td>
                            <td width='18%'>
                                Nº de avaliações alteradas<br>
                                <input type='text' name='num_aval' id="num_aval"
                                       class="field" style="width: 94%;" onkeypress="return SomenteNumero(event)"
                                       value="<?=$this->dados->qt_avaliacao_alterada?>" readonly="readonly" />
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </td>
        </tr>
    </div>

    <br>

    <table width="100%" cellspacing="0" cellpadding="0" border="0">
        <tr>
            <td>
                <fieldset>
                    <legend>Participantes
                        <input type="hidden" name="conf_part" id="conf_part" value="<?=(count($this->partsEdit) == 0 ? "" : count($this->partsEdit))?>" />
                    </legend>
                    <table width='100%' cellspacing="0" cellpadding="0" border="0">
                        <tr>
                            <td width='24%'>
                                Participante<br>
                                <input type='text' name='part_nome' id="part_nome" class="field" style="width: 96%;"
                                       onkeypress="buscaParticipante()" >
                                <input type="hidden" name="part_codigo" id="part_codigo" />
                                <!-- Informações ocultas para atualização dos dados do cidadão -->
                                <input type="hidden" name="id_nome" id="id_nome" value="part_nome" />
                                <input type="hidden" name="id_codigo" id="id_codigo" value="part_codigo" />
                                <input type="hidden" name="id_data" id="id_data" value="part_dtnasc" />
                                <input type="hidden" name="id_button" id="id_button" value="confirm_paciente" />
                                <input type="hidden" name="id_tipo" id="id_tipo" value="" />
                            </td>
                            <td width='10%'> <!-- obrigatório -->
                                Data de Nasc.<br>
                                <input type='text' name='part_dtnasc' id="part_dtnasc"
                                       class="field" style="width: 90%;">
                            </td>
                            <td width='8%'>
                                Peso(kg)<br>
                                <input type='text' name='part_peso' id="part_peso" maxlength="7"
                                       class="field" style="width: 90%;" onblur="formataPeso()" >
                            </td>
                            <td width='8%'>
                                Altura(cm)<br>
                                <input type='text' name='part_altura' id="part_altura"
                                       onkeypress="return SomenteNumero(event)" onblur="validaAltura()"
                                       class="field" maxlength="3" style="width: 90%;">
                            </td>
                            <td width='10%'>
                                Avaliação alterada?<br>
                                <input type='checkbox' name='part_aval' id="part_aval"
                                       class="field" value="1"  />
                            </td>
                            <td colspan="2">
                                <fieldset>
                                    <legend>Programa nacional de controle do tabagismo</legend>
                                    <table>
                                        <td width='8%'>
                                            Parou de fumar?<br>
                                            <input disabled type='checkbox' name='part_fuma' id="part_fuma"
                                                   class="field" value="1" />
                                        </td>

                                        <td width='10%'>
                                            Abandonou o grupo?<br>
                                            <input disabled type='checkbox' name='part_grupo' id="part_grupo"
                                                   class="field" value="1" />
                                        </td>

                                        <td width="4%">
                                            <a class="ui-button paciente ui-corner-bl ui-corner-tr" data-atalho="CTRL+G" onclick="abrirGrupos()">Grupos</a>
                                        </td>
                                        
                                    </table>
                                </fieldset>
                            </td>
                            <td width="4%">
                                <a href="#"  id="confirm_paciente" style="margin-left: 9px; display: none;"
                                   class="ui-button" onclick="confirmaParticipante()">Confirmar
                                </a>
                            </td>
                        </tr>
                    </table>
                    <table width="100%" id="usus_part" style="border: 1px solid #cef; margin-top: 20px; display: show;">
                        <tr>
                            <th width="24%">Participante</th>
                            <th>Data de Nascimento</th>
                            <th>Av. alt</th>
                            <th>Peso(Kg)</th>
                            <th>Altura(cm)</th>
                            <th>Cessou háb.</th>
                            <th>Abandonou o grupo</th>
                            <th>Ações</th>
                        </tr>
                        <?php if (count($this->partsEdit)>0) { ?>
                                <?php $y = 0; ?>
                                <?php foreach($this->partsEdit as $val) { ?>
                                        <?php $y++; ?>
                                        <tr id='usu_part_qtd<?=$y?>' class="participantes <?=($val->st_avaliacao_alterada == "1" ? "aval" : "")?>">
                                            <td>
                                                <?=$val->usu_nome?>
                                                <input type='hidden' name='usus_part[<?=$y?>][usu_codigo]' value="<?=$val->usu_codigo?>" />
                                            </td>
                                            <td>
                                                <?=$this->data($val->dt_nascimento,Zend_Date::DATE_MEDIUM)?>
                                                <input type='hidden' name='usus_part[<?=$y?>][dt_nascimento]' value="<?=$val->dt_nascimento?>" />
                                            </td>
                                            <td>
                                                <?=($val->st_avaliacao_alterada == "1" ? "SIM" : "NÃO")?>
                                                <input type='hidden' name='usus_part[<?=$y?>][st_avaliacao_alterada]' value="<?=$val->st_avaliacao_alterada?>" />
                                            </td>
                                            <td>
                                               <?=$val->nu_peso?>
                                               <input type='hidden' name='usus_part[<?=$y?>][nu_peso]' value="<?=$val->nu_peso?>" />
                                            </td>
                                            <td>
                                                <?=$val->nu_altura?>
                                                <input type='hidden' name='usus_part[<?=$y?>][nu_altura]' value="<?=$val->nu_altura?>" />
                                            </td>
                                            <td>
                                                <?=($val->st_cessou_habito_fumar == 1 ? "SIM" : "NÃO")?>
                                                <input type='hidden' name='usus_part[<?=$y?>][st_cessou_habito_fumar]' value="<?=$val->st_cessou_habito_fumar?>" />
                                            </td>
                                            <td>
                                                <?=($val->st_abandonou_grupo == 1 ? "SIM" : "NÃO")?>
                                                <input type='hidden' name='usus_part[<?=$y?>][st_abandonou_grupo]' value="<?=$val->st_abandonou_grupo?>" />
                                            </td>
                                            <td>
                                                <a href='#'>
                                                    <img src="<?=$this->baseUrl()?>/public/images/icons/excluir.png" alt="Excluir" title="Excluir" onclick="excluirConfirmacaoPart(<?=$y?>)" />
                                                </a>
                                            </td>
                                        </tr>
                                <?php } ?>
                        <?php } else { ?>
                                <tr id="usus_part_qtd0">
                                    <td colspan="7">Nenhum participante registrado até o momento.</td>
                                </tr>
                        <?php } ?>
                        <input type="hidden" id="usus_part_qtd" value="<?=$y?>" />
                    </table>
                </fieldset>
            </td>
        </tr>
    </table>

    <br>

    
    <div align='right'>
        <a href="<?=$this->url(array("controller"=>"atividade-coletiva","action"=>"index"));?>"  class="ui-button voltar" data-atalho="ESC">
            Voltar
        </a>
        <a href="#" class="ui-button salvar" id="enviar">Salvar Dados</a>
    </div>
   
</form>
