<form name="busca" method="POST" action="<?= $this->url(array("action" => "inconsistencias")); ?>" id="busca-comum">
    <label class="ui-corner-bl ui-corner-tr">Buscar por UUID:</label>
    <input type="text" name="uuid" /> 
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
</form>
<table style="width: 100%;">
    <tr>
        <th style="width: 5%;"><span style="margin-left: 4px;">ID</span></th>
        <th style="width: 16%"><span style="margin-left: 4px;">Cód. Atividade</span></th>
        <th style="width: 10%"><span style="margin-left: 4px;">Data</span></th>
        <th style="width: 24%"><span style="margin-left: 4px;">Profissional Responsável</span></th>
        <th style="width: 40%"><span style="margin-left: 4px;">Unidade</span></th>
        <th style="width: 10%"><span style="margin-left: 4px;">Opções</span></th>
    </tr>
    <?php if (count($this->dados) > 0) { ?>
        <?php //echo "<pre>";print_r($this->dados);die(); ?>
        <?php foreach ($this->dados as $dados) { ?>
                <tr class="odd">
                    <td style="width: 5%;"><span style="margin-left: 4px;"><?=$dados->eav_codigo?></span></td>
                    <td style="width: 16%"><span style="margin-left: 4px;"><?=$dados->co_cds_ficha_ativ_col?></span></td>
                    <td style="width: 10%"><span style="margin-left: 4px;"><?=$this->data($dados->eav_dt_atividade,Zend_Date::DATE_MEDIUM)?></span></td>
                    <td style="width: 24%"><span style="margin-left: 4px;"><?=$dados->usr_nome?></span></td>
                    <td style="width: 40%"><span style="margin-left: 4px;"><?=$dados->uni_desc?></span></td>
                    <td style="width: 10%">
                        <span style="margin-left: 4px;">
                            <a href="<?=$this->baseUrl();?>/programasfederais/atividade-coletiva/form/id/<?=$dados->co_cds_ficha_ativ_col?>">
                                <img src="<?=$this->baseUrl();?>/public/images/icons/editar.png" alt="Editar Item" title="Editar Item">
                            </a>    
                        </span>
                    </td>
                </tr>
        <?php } ?>
    <?php } else {  ?>
            <tr height="26">
                <td style="border: 1px solid #919B9C;" colspan="9">
                    <span style="margin-left: 04px;">Nenhuma inconsistência até o momento!</span>
                </td>
            </tr>
    <?php } ?>
</table>