<?php $this->errorMsg(); ?>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

<?
if($_GET['alert']){
    if($_GET['alert'] == "success"){ ?>
    <script>
        Swal.fire({
            title: 'Sucesso!',
            text: 'Atendimento salvo com sucesso',
            type: 'success',
            confirmButtonText: 'Ok'
        })
    </script>
    <? }
}
?>
<form name="busca" method="POST" action="<?=$this->baseUrl();?>/programasfederais/atividade-coletiva/buscar" id="form-busca">
    <a href="<?=$this->baseUrl();?>/programasfederais/atividade-coletiva/form" class="ui-button novo ui-corner-bl ui-corner-tr" data-atalho="CTRL+N">Novo</a>
    <label class="ui-corner-bl ui-corner-tr">Buscar:</label>
    <input size="50" class="focus ui-state-default" name="busca" value="" type="text">
    <select name="tipo_busca" class="ui-state-default">
        <option value="">Tipo de busca</option>
        <option value="1">Profissional</option>
        <option value="2">Data da atividade</option>
        <option value="3">Código Unidade(CNES)</option>
        <option value="4">Código INE</option>
    </select>
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
    
    <a class="ui-button paciente ui-corner-bl ui-corner-tr" data-atalho="CTRL+G" onclick="abrirCadastroGrupos()">Grupos</a>
</form>
<table class='grid ui-widget ui-widget-content ui-corner-all' width='100%'>
        <tr class='ui-widget-header'>
            <th>Data de atividade</th>
            <th>Tipo de atividade</th>
            <th>Profissional responsável</th>
            <th>Unidade</th>
            <th>Cód. equipe (INE)</th>
            <th>Turno</th>
            <th>Opções</th>
        </tr>
    <?php 
    if(count($this->dados)>0) {
    foreach($this->dados as $item) { ?>
        <tr>
            <td class='ui-state-default'><?=$this->data($item->dt_ativ_col)?></td>
            <td class='ui-state-default'><?=$item->tp_cds_ativ_col?></td>
            <td class='ui-state-default'><?=$item->usr_nome?></td>
            <td class='ui-state-default'><?=$item->cod_cnes_unidade?></td>
            <td class='ui-state-default'><?=$item->cod_equipe_ine?></td>
            <td class='ui-state-default'><?
            switch ($item->turno) {
                case '1':
                    echo 'Manha';
                    break;
                case '2':
                    echo 'Tarde';
                    break;
                case '3':
                    echo 'Noite';
                    break;
            }
            ?></td>
            <td class='ui-state-default c' width='80'>
                <a href='<?=$this->url(array("action"=>"editar", "module"=>"programasfederais", "controller"=>"atividade-coletiva","id"=>"$item->co_cds_ficha_ativ_col"), NULL, TRUE);?>' class='editar'>
                    <img src='<?=$this->baseUrl('/public/images/icons/editar.png');?>' alt='Editar Itens' title='Editar Itens' />
                </a>
            </td>
        </tr>
    <?php 
    } ?>
    <?php  
    } else {?>
        <td colspan="6">Nenhum item encontrado</td>
    <?php 
    } ?>
</table>