<?php $this->dialog(); ?>
<?php $this->errorMsg(); ?>
<br />
<form method="post" action="<?=$this->url(array("action"=>"salvar-categoria-convenios-procedimentos"))?>" id="form-categoria-conv">
    <input type="hidden" name="catcp_codigo" id="catcp_codigo" value="<?=$this->dadosEdicao->catcp_codigo?>" />
    <label style="width: 140px;"> Categoria de Convênio:</label>
    <?=$this->tipo_de_metodos?>
    <select name="catc_codigo" id="catc_codigo">
        <option value="">Selecione</option>
        <?php foreach ($this->lista_categorias as $value) { ?>
            <option value="<?=$value->catc_codigo?>" <?=$this->dadosEdicao->catc_codigo == $value->catc_codigo ? "selected='selected'" : ""; ?> >
                <?=$value->catc_nome?>
            </option>
        <?php } ?>
    </select><br />
    <label style="width: 140px;">Procedimento:</label>
    <input type="text" name="proc_nome" id="proc_nome" onkeypress="buscaProcedimentosSus();" value="<?=$this->dadosEdicao->proc_nome?>" />
    <input type="hidden" name="proc_codigo" id="proc_codigo" value="<?=$this->dadosEdicao->proc_codigo?>" /><br />
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+S" style="margin-left: 145px;">Salvar</a>
</form>
<br /><br />
<form id="categoria-de-exames" method="post" action="<?=$this->url(array("action"=>"busca-configuracoes"))?>" >
    <label class="ui-corner-bl ui-corner-tr">Buscar:</label>
    <input size="50" class="focus ui-state-default" name="busca" value="" type="text">
    <label class="ui-corner-bl ui-corner-tr">Tipo de Busca:</label>
    <select name="tipo_busca">
        <option value="P">Procedimento</option>
        <option value="C">Categoria de Convênio</option>
    </select>
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
</form>
<table class="sortable">
    <tr>
        <th>Código</th>
        <th>Categoria de Convênio</th>
        <th>Código SUS - Procedimento</th>
        <th colspan="2">Ações</th>
    </tr>
    <?php if (count($this->dados)>0) { ?>
        <?php foreach($this->dados as $value) { ?>    
                <tr>
                    <td><?=$value->catcp_codigo?></td>
                    <td><?=$value->catc_nome?></td>
                    <td><?=($value->proc_codigo_sus != "" ? $value->proc_codigo_sus : "SEM CÓDIGO")." - ".$value->proc_nome?></td>
                    <td>
                        <?php //catc_codigo/<?=$value->catc_codigo?>
                        <a href="<?=$this->baseUrl();?>/agenda/categoria-de-convenios/categoria-convenios-procedimentos/id/<?=$value->catcp_codigo?>" class="editar" >
                            <img src="<?=$this->baseUrl();?>/public/images/icons/editar.png" alt="Editar Item" title="Editar Item">
                        </a>
                    </td>
                    <td>
                        <a href="#">
                            <img src="<?=$this->baseUrl();?>/public/images/icons/excluir.png" alt="Excluir Item" title="Excluir Item" onclick="excluirCategoriaConveniosProcedimentos(<?=$value->catcp_codigo?>)">
                        </a>
                    </td>
                </tr>
        <?php } ?>
    <?php } else { ?>
            <tr>
                <td colspan="4">Nenhuma configuração realizada até o momento!</td>
            </tr>
    <?php } ?>
</table>
