<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
<meta http-equiv="content-type" content="text/html;"/>
<title>Google Maps - Rotas</title>
<link href="http://code.google.com/apis/maps/documentation/javascript/examples/default.css" rel="stylesheet" type="text/css" />
 
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
  <script type="text/javascript" src="/WebSocialComum/library/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="/WebSocialSaude/lib/ui/jquery-ui-1.8.16.custom.min.js"></script>
  <script type="text/javascript">
  $(function(){
 
  //Adiciona endereço à lista
  $('#adic').click(function(){
    var ender = $('#addr').val();
    if (ender != '') {
      $('#addr').val('');
      var newid = new Date().getTime();
      $('#route').append('<li id="' + newid + '">' + ender + '</li>');
    }
  });
 
  //Habilita função de ordenação da lista
  $('#route').sortable({axis:'y'});
 
  //exclui no duplo clique
  $('#route').delegate('li', 'dblclick', function(){
    $(this).remove();
  });
  var directionsService = new google.maps.DirectionsService();
 
 function getText(id) {
  return $('#'+id).text();
}
 
$('#trace').click(function () {
  var addresses = $('#route').sortable("toArray");
  var len       = addresses.length
 
  if (len < 2) {
    alert('Se liga... Não existe rota sem pelo menos dois endereços!');
    return false;
  }
 
  var start = getText(addresses[0]);
  var end   = getText(addresses[len - 1]);
  var waypts = [];
  for (var i = 1; i < len-1; i++) {
      waypts.push({
          location:getText(addresses[i]),
          stopover:true});
  }
 
  var request = {
      origin: start,
      destination: end,
      waypoints: waypts,
      optimizeWaypoints: false,
      travelMode: google.maps.DirectionsTravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    }
  });
});
});
  
  
  
    var directionDisplay;
    var map;
 
    function initialize() {
      directionsDisplay = new google.maps.DirectionsRenderer();
      var maringa = new google.maps.LatLng(-23.4166645,  -51.91666);
      var myOptions = {
        zoom: 12,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        center: maringa
      }
      map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
      directionsDisplay.setMap(map);
    }
 
  </script>
</head>
<body onload="initialize()">
<div id="map_canvas" style="float:left;width:70%;height:100%;"></div>
<div id="control_panel" style="float:right;width:30%;text-align:left;">
  <div style="padding:10px">
    <input type="text"   id="addr" name="address" />
    <input type="button" id="adic" name="adicionar" value="Adicionar à Rota" />
 
    <p>De um duplo clique para remover um endereço da rota</p>
 
    <ol id="route">
      <li id="1">Av. Brasil - Maringá-PR</li>
      <li id="2">Av. Cerro Azul - Maringá-PR</li>
    </ol>
 
    <input type="button" id="trace" name="trace" value="Traçar Rota" />
  </div>
 
</div>
<div id="map_canvas" style="float:left;width:100%;height:100%;"></div>
</body>
</html>