<form method="post" action="<?= $this->url(array("action" => "salvar")); ?>" id="edit-viagem_pass">
    <table class='grid ui-widget ui-widget-content ui-corner-all' width='70%'>
        <tr class='ui-widget-header'>
               <th>Passageiro</th>
               <th>Num. Acomp</th>
               <th>Opções</th>
           </tr>
    <?php
    if($this->pass && $this->pass->count()):
        foreach($this->pass as $p):?>
            <tr>
                <td class='ui-state-default c' width='150'><?=$p->usu_nome?></td>
                <td class='ui-state-default c' width='30'><?=$p->total?></td>
              
                <td class='ui-state-default c' width='150'>
                    <a href='<?=$this->url(array('controller'=>'viagem-usuario','action'=>'editar','id'=>$p->viausu_codigo));?>' class='ui-button atualizar'>Editar</a>
                    <a href='<?=$this->url(array('controller'=>'viagem-usuario','action'=>'excluir','id'=>$p->viausu_codigo));?>' class='ui-button excluir3'>Excluir</a>
                </td>
            </tr>
    <?php endforeach; ?>
    </table>
    <?php else:?>
        <em>Nenhum item encontrado</em>
    <?php endif;?>

</form>