<div style='font-weight:bold; margin-bottom: 5px;'>
<style>
.tag_usu {
    font-weight:bold;
    background: #BDBDBD;
}
.tag_total {
    font-weight:bold;
    background: #E0E0E0;
}
</style>

</div>
<?
foreach ($this->pacientes as $paciente){
?>
<!-- <input type="color" class="tag_usu" value="Usuário=<?=$paciente->usu_nome?> (<?=$paciente->usu_codigo?>)"> -->
<table >
    <tr >
        <th class="tag_usu" align="left">Usuário: <?=$paciente->usu_nome?> (<?=$paciente->usu_codigo?>)</th>
    </tr>
</table>

<table align="center">
    <tr>    
        <th width="40%">Exame(s)</th>
        <th width="20%">Data</th>
        <th width="5%">Quantidade</th>
        <th width="10%">Valor</th>
        <th width="25%">Unidade</th>
    </tr>
<?
$i = 0;
$valor = 0;

foreach ($this->dados[$paciente->usu_codigo] as $item){
    if($item->proc_codigo != null){
    $i++;
    $valor += $item->agei_valor;
?>
    <tr>
        <td><?=$item->proc_nome?>(<?=$item->proc_codigo?>)</td>
        <td><?
        $source = $item->age_data_insert;
        $date = new DateTime($source);
        echo $date->format('d/m/Y');
        ?></td>
        <td>1</td>
        <td><?=$item->agei_valor?></td>
        <td><?=$item->med_nome?></td>
    </tr>

<?
$total += 50;
    }
} ?>
</table>
<table class="tag_total">
    <tr style='font-weight:bold;' align="right">
        <td >Quantidade</td>
        <td ><?=$i?></td>
        <td >Total</td>
        <td ><?=$valor?></td>
    </tr>
</table>

<?
}
?>
