<? $this->dialog(); ?>
<? $this->errorMsg(); ?>
<form name="busca" method="POST" action="<?=$this->baseUrl();?>/farmacia/medicamentos-especiais/buscar" id="form-busca">
    <a href="<?=$this->baseUrl();?>/farmacia/medicamentos-especiais/componente-especializado" class="ui-button novo ui-corner-bl ui-corner-tr">Novo laudo de avaliação</a>
    <a href="<?=$this->baseUrl();?>/farmacia/medicamentos-especiais/solicitacao-medicamentos" class="ui-button novo ui-corner-bl ui-corner-tr">Nova solicitação de medicamento(s)</a>
    <label class="ui-corner-bl ui-corner-tr" style="width: 70px">Buscar:</label>

    <input size="50" class="focus ui-state-default" name="busca" value="" type="text">
    <select name="tipo_busca" class="ui-state-default">
        <option value="">Tipo de busca</option>
        <option value="1">Profissional</option>
        <option value="2">Data</option>
        <option value="3">CBO</option>
        <option value="4">Unidade</option>
    </select>
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
</form>
<table class='grid ui-widget ui-widget-content ui-corner-all' width='100%'>
    <tr class='ui-widget-header'>
        <th>#</th>
        <th>Data da solicitação</th>
        <th>Solicitante</th>
        <th>Tipo</th>
        <th>Ações</th>
    </tr>
    <? 
    if(count($this->dados) > 0) {
        foreach($this->dados as $item) { ?>
        <tr>
            <td class='ui-state-default text-center'><?=$item->id?></td>
            <td class='ui-state-default text-center'><?=$item->dataSolicitacao?></td>
            <td class='ui-state-default text-center'><?=$item->nomePaciente?></td>
            <td class='ui-state-default text-center'><?=$item->tipo == "S" ? 'Solicitação de medicamento' : "Laudo de avaliação"?>
            </td>
            
            <td class='ui-state-default text-center'>
                
                <a href="<?=$this->baseUrl();?>/farmacia/medicamentos-especiais/<?=$item->tipo == "S" ? "solicitacao-medicamentos" : "componente-especializado"?>?id=<?= $item->id; ?>" class="editar">
                    <img src="<?=$this->baseUrl();?>/public/images/icons/editar.png" alt="Editar Item" title="Editar Item" />
                </a>

                <a href="<?=$this->baseUrl();?>/farmacia/medicamentos-especiais/<?=$item->tipo == "S" ? "solicitacao-medicamentos" : "componente-especializado"?>?id=<?= $item->id; ?>&action=print" class="print">
                    <img src="<?=$this->baseUrl();?>/public/images/icons/printer.png" alt="Imprimir Item" title="Imprimir Item" />
                </a>
                
                <a href="<?=$this->baseUrl();?>/farmacia/medicamentos-especiais/posologia?id=<?=$item->id?>" class="">
                    <img src="<?=$this->baseUrl();?>/public/images/icons/tempo_periodo.png" alt="Posologia" title="Posologia" />
                </a>

                <a href="<?=$this->baseUrl();?>/farmacia/medicamentos-especiais/deletar?id=<?=$item->id?>" class="excluir">
                    <img src="<?=$this->baseUrl();?>/public/images/icons/excluir.png" alt="Excluir Item" title="Excluir Item" />
                </a>

            </td>

        </tr>
    <?  }
    } else { ?>
        <td colspan="6">Nenhum item encontrado</td>
    <? } ?>
</table>