<? //echo "<pre>".print_r($this->dados,1); exit;?>
<div id="receita">
	<div style="float:left;">
            Data Emissão:<?=$this->data($this->dados_req->rem_data); ?>
	</div>
	<br/>
	<br/>
	<div id="rec_titulo">
		<div class="left">Medicamento</div>
		<div class="right">Quant.</div>
		<div class="clear"></div>
	</div>
	<?php if ($this->itens): ?>
		<?php foreach ($this->itens as $item): ?>
			<div class="medItem">
				<div class="medTitulo">
					<?php
                                            echo $item->pro_nome;
					?>
				</div>
				<div class="medQtd"><?= $item->remi_quantidade; ?></div>	
				<div class="clear"></div>
			</div>
		<?php endforeach; ?>	 		
	<?php endif; ?>
</div>
