<?php
namespace esus;

/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Exception\TApplicationException;


class CDSTransportThrift {
  static $_TSPEC;

  public $atendimentoIndividualTransport = null;
  public $atendimentoOdontologicoTransport = null;
  public $atividadeColetivaTransport = null;
  public $cadastroDomiciliarTransport = null;
  public $cadastroIndividualTransport = null;
  public $cpf = null;
  public $procedimentosTransport = null;
  public $senha = null;
  public $visitaDomiciliarTransport = null;
  public $cidadaoTransport = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'atendimentoIndividualTransport',
          'type' => TType::STRUCT,
          'class' => '\esus\AtendimentoIndividualTransportThrift',
          ),
        2 => array(
          'var' => 'atendimentoOdontologicoTransport',
          'type' => TType::STRUCT,
          'class' => '\esus\AtendimentoOdontologicoTransportThrift',
          ),
        3 => array(
          'var' => 'atividadeColetivaTransport',
          'type' => TType::STRUCT,
          'class' => '\esus\AtividadeColetivaTransportThrift',
          ),
        4 => array(
          'var' => 'cadastroDomiciliarTransport',
          'type' => TType::STRUCT,
          'class' => '\esus\CadastroDomiciliarTransportThrift',
          ),
        5 => array(
          'var' => 'cadastroIndividualTransport',
          'type' => TType::STRUCT,
          'class' => '\esus\CadastroIndividualTransportThrift',
          ),
        6 => array(
          'var' => 'cpf',
          'type' => TType::STRING,
          ),
        7 => array(
          'var' => 'procedimentosTransport',
          'type' => TType::STRUCT,
          'class' => '\esus\ProcedimentosTransportThrift',
          ),
        8 => array(
          'var' => 'senha',
          'type' => TType::STRING,
          ),
        9 => array(
          'var' => 'visitaDomiciliarTransport',
          'type' => TType::STRUCT,
          'class' => '\esus\VisitaDomiciliarTransportThrift',
          ),
        10 => array(
          'var' => 'cidadaoTransport',
          'type' => TType::STRUCT,
          'class' => '\esus\CidadaoTransportThrift',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['atendimentoIndividualTransport'])) {
        $this->atendimentoIndividualTransport = $vals['atendimentoIndividualTransport'];
      }
      if (isset($vals['atendimentoOdontologicoTransport'])) {
        $this->atendimentoOdontologicoTransport = $vals['atendimentoOdontologicoTransport'];
      }
      if (isset($vals['atividadeColetivaTransport'])) {
        $this->atividadeColetivaTransport = $vals['atividadeColetivaTransport'];
      }
      if (isset($vals['cadastroDomiciliarTransport'])) {
        $this->cadastroDomiciliarTransport = $vals['cadastroDomiciliarTransport'];
      }
      if (isset($vals['cadastroIndividualTransport'])) {
        $this->cadastroIndividualTransport = $vals['cadastroIndividualTransport'];
      }
      if (isset($vals['cpf'])) {
        $this->cpf = $vals['cpf'];
      }
      if (isset($vals['procedimentosTransport'])) {
        $this->procedimentosTransport = $vals['procedimentosTransport'];
      }
      if (isset($vals['senha'])) {
        $this->senha = $vals['senha'];
      }
      if (isset($vals['visitaDomiciliarTransport'])) {
        $this->visitaDomiciliarTransport = $vals['visitaDomiciliarTransport'];
      }
      if (isset($vals['cidadaoTransport'])) {
        $this->cidadaoTransport = $vals['cidadaoTransport'];
      }
    }
  }

  public function getName() {
    return 'CDSTransportThrift';
  }

  public function read($input)
  {
      
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->atendimentoIndividualTransport = new \esus\AtendimentoIndividualTransportThrift();
            $xfer += $this->atendimentoIndividualTransport->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRUCT) {
            $this->atendimentoOdontologicoTransport = new \esus\AtendimentoOdontologicoTransportThrift();
            $xfer += $this->atendimentoOdontologicoTransport->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::STRUCT) {
            $this->atividadeColetivaTransport = new \esus\AtividadeColetivaTransportThrift();
            $xfer += $this->atividadeColetivaTransport->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::STRUCT) {
            $this->cadastroDomiciliarTransport = new \esus\CadastroDomiciliarTransportThrift();
            $xfer += $this->cadastroDomiciliarTransport->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 5:
          if ($ftype == TType::STRUCT) {
            $this->cadastroIndividualTransport = new \esus\CadastroIndividualTransportThrift();
            $xfer += $this->cadastroIndividualTransport->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 6:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->cpf);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 7:
          if ($ftype == TType::STRUCT) {
            $this->procedimentosTransport = new \esus\ProcedimentosTransportThrift();
            $xfer += $this->procedimentosTransport->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 8:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->senha);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 9:
          if ($ftype == TType::STRUCT) {
            $this->visitaDomiciliarTransport = new \esus\VisitaDomiciliarTransportThrift();
            $xfer += $this->visitaDomiciliarTransport->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 10:
          if ($ftype == TType::STRUCT) {
            $this->cidadaoTransport = new \esus\CidadaoTransportThrift();
            $xfer += $this->cidadaoTransport->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('CDSTransportThrift');
    if ($this->atendimentoIndividualTransport !== null) {
      if (!is_object($this->atendimentoIndividualTransport)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('atendimentoIndividualTransport', TType::STRUCT, 1);
      $xfer += $this->atendimentoIndividualTransport->write($output);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->atendimentoOdontologicoTransport !== null) {
      if (!is_object($this->atendimentoOdontologicoTransport)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('atendimentoOdontologicoTransport', TType::STRUCT, 2);
      $xfer += $this->atendimentoOdontologicoTransport->write($output);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->atividadeColetivaTransport !== null) {
      if (!is_object($this->atividadeColetivaTransport)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('atividadeColetivaTransport', TType::STRUCT, 3);
      $xfer += $this->atividadeColetivaTransport->write($output);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->cadastroDomiciliarTransport !== null) {
      if (!is_object($this->cadastroDomiciliarTransport)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('cadastroDomiciliarTransport', TType::STRUCT, 4);
      $xfer += $this->cadastroDomiciliarTransport->write($output);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->cadastroIndividualTransport !== null) {
      if (!is_object($this->cadastroIndividualTransport)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('cadastroIndividualTransport', TType::STRUCT, 5);
      $xfer += $this->cadastroIndividualTransport->write($output);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->cpf !== null) {
      $xfer += $output->writeFieldBegin('cpf', TType::STRING, 6);
      $xfer += $output->writeString($this->cpf);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->procedimentosTransport !== null) {
      if (!is_object($this->procedimentosTransport)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('procedimentosTransport', TType::STRUCT, 7);
      $xfer += $this->procedimentosTransport->write($output);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->senha !== null) {
      $xfer += $output->writeFieldBegin('senha', TType::STRING, 8);
      $xfer += $output->writeString($this->senha);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->visitaDomiciliarTransport !== null) {
      if (!is_object($this->visitaDomiciliarTransport)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('visitaDomiciliarTransport', TType::STRUCT, 9);
      $xfer += $this->visitaDomiciliarTransport->write($output);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->cidadaoTransport !== null) {
      if (!is_object($this->cidadaoTransport)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('cidadaoTransport', TType::STRUCT, 10);
      $xfer += $this->cidadaoTransport->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}


