<?= $this->doctype() . "\n"; ?>
<?php
$_SESSION[modulo] = "WebSocialSaude/"; $_SESSION[root] = $_SERVER[DOCUMENT_ROOT] . "/"; $_SESSION[linkroot] = "http://" . $_SERVER[HTTP_HOST] . "/"; $_SESSION[comum] = "WebSocialComum/"; $_SESSION[modulo] = "WebSocialSaude/"; require_once $_SESSION[root].$_SESSION[modulo]."sessao_controller.php";
$sessao = new TempoSessao();
    $_SESSION['time_m_agora'] = date("i"); # RECEBE O VALOR DO MINUTO ATUAL
    $_SESSION['time_m_fim'] = date("i") + 30; # ADICIONA O TEMPO DE DURAÇÃO DA SUA SESSÃO
    $_SESSION['time_h_fim'] = date("H"); # RECEBE O VALOR DA HORA ATUAL
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt">
    <head>
        <?= $this->headMeta() . "\n"; ?>
        <?= $this->headTitle() . "\n"; ?>
        <?= $this->headLink() . "\n"; ?>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta charset="UTF-8">
		<script type="text/javascript">
			var baseUrl = '<?=$this->baseUrl();?>';
		</script>
        <?= $this->headScript() . "\n"; ?>
		<?= $this->analytics(); ?>
    </head>
    <body>
		<div id="page">
			<div id="corpo">
				<div id='tabs'> 
					<ul class="tabs">
						<li><a href="#tabs-1"><?= $this->title; ?></a></li>
					</ul>
					<div id='tabs-1'>
						<?= $this->layout()->content; ?>
					</div>
				</div>
			</div>
		</div>
		<div id="sys"></div>
    </body>
</html>