<?= $this->doctype() . "\n"; ?>
<?php
$_SESSION[modulo] = "WebSocialSaude/";
$_SESSION[root] = $_SERVER[DOCUMENT_ROOT] . "/";
$_SESSION[linkroot] = "http://" . $_SERVER[HTTP_HOST] . "/";
$_SESSION[comum] = "WebSocialComum/";
$_SESSION[modulo] = "WebSocialSaude/";
$_SESSION[modulo] = "WebSocialSaude/";
$_SESSION[root] = $_SERVER[DOCUMENT_ROOT] . "/";
$_SESSION[linkroot] = "http://" . $_SERVER[HTTP_HOST] . "/";
$_SESSION[comum] = "WebSocialComum/";
$_SESSION[modulo] = "WebSocialSaude/";
require_once $_SESSION[root] . $_SESSION[modulo] . "sessao_controller.php";
$sessao = new TempoSessao();
$sessao->primeiraPagina();
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt">
<head>
	<?= $this->headMeta() . "\n"; ?>
	<?= $this->headTitle() . "\n"; ?>
	<?= $this->headLink() . "\n"; ?>
    <link href='<?= $this->baseUrl('/public/css/paisagem-print.css') ?>' rel='stylesheet' type='text/css'></link>
    <script type="text/javascript">
        var baseUrl = '<?=$this->baseUrl();?>';
        $(function () {
            // window.print();
        });
    </script>
	<?= $this->headScript() . "\n"; ?>
    <?= $this->analytics(); ?>
    <script>
        $(function(){
            var duasvias = <?= ($this->duasvias ? $this->duasvias : 'false')?>;
            if (duasvias) {
                $("#segundavia").removeClass("invisivel");
            } else {
                $("#segundavia").addClass("invisivel");
            }
        });
    </script>
</head>
<body>
    <div class="container-print">
        <div id="segundavia" class="page-print">
            <div class="cabecalho">
                <div class="brasao">
                    <img src="<?=$this->baseUrl("/public/images/brasao.jpg");?>" height="95" width="95"/>
                </div>
                <div class="informacoes">
                    <ul>
                        <li><b><?=$this->secretaria->nome_secretaria?></b></li>
                        <li>C.N.P.J.:<?=$this->secretaria->cnpj_secretaria?></li>
                        <li><b><?=$this->usr->uni_desc;?></b></li>
                    </ul>
                </div>
                <div class="cod-barras">
                    <img src="<?=$this->baseUrl()?>/public/images/codigo_barras.php?codigo=<?=$this->dados->codigo;?>&lw=1&hi=18" width="120" alt="Código de Barras: <?=$this->dados->codigo;?>" title="Código de Barras: <?=$this->dados->codigo;?>" width="110" />
                </div>
            </div>
            <div class="nome-relatorio">
                <div class="titulo_impressao"><b><?=$this->tipo_impressao;?></b></div>
                <div class="dados_titulo">
                    IDENTIFICAÇÃO DO PACIENTE
                </div>
            </div>
            <div class="corpo">
                <table class="table-dados">
                    <tr>
                        <td width="100" align="right"><b>Pront.| Paciente:</b></td>
                        <td colspan="5"><?=$this->dados->usu_prontuario?> | <?=$this->dados->usu_nome?></td>
                    </tr>
                    <tr>
                        <td width="100" align="right"><b>Idade | Sexo:</b></td>
                        <td><?=$this->idade($this->dados->idade)?> | <?=($this->dados->usu_sexo == "F" ? "Feminino" : "Masculino")?></td>
                        <td width="100" align="right"><b>Dt.Nascimento:</b></td>
                        <td width="60"><?=$this->data($this->dados->usu_datanasc)?></td>
                    </tr>
                    <tr>
                        <td width="100" align="right"><b>CNS:</b></td>
                        <td><?=($this->dados->usu_cartao_sus == "" ? "-" : $this->dados->usu_cartao_sus)?></td>
                        <td width="100" align="right"><b>Dt.Emissão:</b></td>
                        <td width="60"><?=date("d/m/Y");?></td>
                    </tr>
                    <tr>
                        <td width="100" align="right"><b>Endereço:</b></td>
                        <td colspan="3">
				            <?=($this->dados->rua_nome == "" ? "SEM ENDEREÇO" : $this->dados->rua_nome.",")?> <?= $this->dados->dom_numero == 0 ? "S/N" : $this->dados->dom_numero ?> - <?=$this->dados->cid_nome?>
                        </td>
                    </tr>
                </table>
	            <?= $this->layout()->content; ?>
            </div>
            <div class="rodape">
                <div class="assinatura">
			        <?=$this->dados->usr_nome?>
                    <p><?=$this->dados->con_descricao.": ".$this->dados->usr_num_conselho. " - ". $this->dados->cnes_sigla_est?></p>
                </div>
                <div id="endereco">
			        <?=$this->secretaria->endereco_secretaria?>, CNPJ:<?=$this->secretaria->cnpj_secretaria?>, FONE:<?=$this->secretaria->telefone_secretaria?>
                </div>
            </div>
        </div>
        <div class="page-print">
            <div class="cabecalho">
                <div class="brasao">
                    <img src="<?=$this->baseUrl("/public/images/brasao.jpg");?>" height="95" width="95"/>
                </div>
                <div class="informacoes">
                    <ul>
                        <li><b><?=$this->secretaria->nome_secretaria?></b></li>
                        <li>C.N.P.J.:<?=$this->secretaria->cnpj_secretaria?></li>
                        <li><b><?=$this->usr->uni_desc;?></b></li>
                    </ul>
                </div>
                <div class="cod-barras">
                    <img src="<?=$this->baseUrl()?>/public/images/codigo_barras.php?codigo=<?=$this->dados->codigo;?>&lw=1&hi=18" width="120" alt="Código de Barras: <?=$this->dados->codigo;?>" title="Código de Barras: <?=$this->dados->codigo;?>" width="110" />
                </div>
            </div>
            <div class="nome-relatorio">
                <div class="titulo_impressao"><b><?=$this->tipo_impressao;?></b></div>
                <div class="dados_titulo">
                    IDENTIFICAÇÃO DO PACIENTE
                </div>
            </div>
            <div class="corpo">
                <table class="table-dados">
                    <tr>
                        <td width="100" align="right"><b>Pront.| Paciente:</b></td>
                        <td colspan="5"><?=$this->dados->usu_prontuario?> | <?=$this->dados->usu_nome?></td>
                    </tr>
                    <tr>
                        <td width="100" align="right"><b>Idade | Sexo:</b></td>
                        <td><?=$this->idade($this->dados->idade)?> | <?=($this->dados->usu_sexo == "F" ? "Feminino" : "Masculino")?></td>
                        <td width="100" align="right"><b>Dt.Nascimento:</b></td>
                        <td width="60"><?=$this->data($this->dados->usu_datanasc)?></td>
                    </tr>
                    <tr>
                        <td width="100" align="right"><b>CNS:</b></td>
                        <td><?=($this->dados->usu_cartao_sus == "" ? "-" : $this->dados->usu_cartao_sus)?></td>
                        <td width="100" align="right"><b>Dt.Emissão:</b></td>
                        <td width="60"><?=date("d/m/Y");?></td>
                    </tr>
                    <tr>
                        <td width="100" align="right"><b>Endereço:</b></td>
                        <td colspan="3">
                            <?=($this->dados->rua_nome == "" ? "SEM ENDEREÇO" : $this->dados->rua_nome.",")?> <?= $this->dados->dom_numero == 0 ? "S/N" : $this->dados->dom_numero ?> - <?=$this->dados->cid_nome?>
                        </td>
                    </tr>
                </table>
	            <?= $this->layout()->content; ?>
            </div>
            <div class="rodape">
                <div class="assinatura">
	                <?=$this->dados->usr_nome?>
	                <p><?=$this->dados->con_descricao.": ".$this->dados->usr_num_conselho. " - ". $this->dados->cnes_sigla_est?></p>
                </div>
                <div id="endereco">
		            <?=$this->secretaria->endereco_secretaria?>, CNPJ:<?=$this->secretaria->cnpj_secretaria?>, FONE:<?=$this->secretaria->telefone_secretaria?>
                </div>
            </div>
        </div>
    </div>
</body>
</html>