<?= $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt">
    <head>
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <?= $this->headMeta() . "\n"; ?>
        <?= $this->headTitle() . "\n"; ?>
        <?= $this->headLink() . "\n"; ?>
		<script type="text/javascript">
			var baseUrl = '<?=$this->baseUrl();?>';
		</script>
        <?= $this->headScript() . "\n"; ?>
        <?= $this->analytics(); ?>
        <style>
            .recuado {
                left: 10px;
                top: 10px;
                right: 10px;
                bottom: 10px;
                padding: 10px;
            }
        </style>
    </head>
    <body>
        <div class="recuado">
            <?= $this->layout()->content; ?>
        </div>
    </body>
</html>
