<form method="post" name="form" id="form" action="<?= $this->url(array("action" => "salvar")); ?>">
    <input type="hidden" name="mic_codigo" value="<?=$this->dados->mic_codigo;?>">
    <br/>
    <label>Micro-Área</label>
    <input type="text" name="mic_descricao" id="mic_descricao" value="<?=$this->dados->mic_descricao;?>">
    <br/>
    <label>Área</label>
    <select class="ui-state-default" name="area_codigo">
        <option value="">Selecione</option>
        <? foreach($this->areas as $area):?>
            <option <?=($this->dados->area_codigo == $area->area_codigo ? "selected=selected" : "");?> value="<?=$area->area_codigo?>"><?=$area->area_desc?></option>
        <? endforeach;?>
    </select>
    <br/>
    <label>Responsável</label>
    <input type="text" name="usr_nome" id="usr_nome"  value="<?= $this->dados->usr_nome ; ?>" /><br />
    <input type="hidden" name="usr_codigo" id="usr_codigo" value="<?= $this->dados->usr_codigo?>">
    <br/>
    <a href="<?=$this->url(array("action"=>"index", "module"=>"domicilio","controller" => "micro-area"),NULL,TRUE)?>" class="ui-button voltar" data-atalho="ESC">Voltar</a>	
    <a href="#" class="ui-button salvar"  >Salvar</a>
</form>