<? //echo "<pre>".print_r($this->chamados,1);?>
<div id="page">
<div id="central">
    <div id="topo">
        <div id="topo-esquerda">            
<img class='img-tempo'>
            <div class='graus'></div>
            <div class='tempo' style='text-transform: capitalize;'></div>
            <h3 class='city'></h3>
            <div id='hora' class='hora'></div>
            <div class='date'><?= date('d/m/Y');?></div>          
        </div>

    </div>
    <div id="esquerda">        
        <div id="">
            <!-- <video id="mediaElement" width="100%" height="621" src="<?=$this->baseUrl('/public/videos/video1.ogg')?>" controls autoplay loop>
            Seu navegador não suporta o elemento <code>video</code>.
           </video> -->
        <figure>
            <img src="../public/images/manchester.jpg" width="100%" height="453">
        </figure>
            
<!--            <embed src="C:\Variedades\VideoDoidao\MOV01741.AVI" width="50" height="50"> </embed>-->
        
        </div>        
    </div>
    <div id="direita">
        <div class="espera">
            2º Chamada:
            <div>
                <div id="cor-2" style="width: 35px;height:35px; background-color: <?=$this->chamados[1]['cor']?>;; float: left; margin-right:10px;"></div>
                <div id="pac-2" style="margin-left:10px;   font-size: 30px;"><?=($this->proximo['age_paciente'] ? $this->chamados[1]['age_paciente'] : "Nenhum Paciente Chamado")?></div>
            </div>
           <div>
                <div class="setor">Setor:</div> <div id="set-2"><?=$this->chamados[1]['set_nome']?></div>
            </div>
        </div>
        <div class="espera">
            3º Chamada:
            <div>
                <div id="cor-3" style="width: 35px;height:35px; background-color: <?=$this->chamados[2]['cor']?>; float: left; margin-right:10px;"></div>
                <div id="pac-3" style="margin-left:10px;   font-size: 30px;"><?=($this->proximo['age_paciente'] ? $this->chamados[2]['age_paciente'] : "Nenhum Paciente Chamado")?></div>
            </div>
            <div>
                <div class="setor">Setor:</div> <div id="set-3"><?=$this->chamados[2]['set_nome']?></div>
            </div>
        </div>
        <div class="espera">
            4º Chamada:
            <div>
                <div id="cor-4" style="width: 35px;height:35px; background-color: <?=$this->chamados[3]['cor']?>; float: left; margin-right:10px;"></div>
                <div id="pac-4" style="margin-left:10px;  font-size: 30px;"><?=($this->proximo['age_paciente'] ? $this->chamados[3]['age_paciente'] : "Nenhum Paciente Chamado")?></div>
            </div>
            <div>
                <div class="setor">Setor:</div> <div id="set-4"><?=$this->chamados[3]['set_nome']?></div>
            </div>
        </div>
        <!-- <div class="espera">
            5º Chamada:
            <div>
                <div id="cor-5" style="width: 35px;height:35px; background-color: <?=$this->chamados[4]['cor']?>; float: left; margin-right:10px;"></div>
                <div id="pac-5" style="margin-left:10px;  font-size: 30px;"><?=($this->proximo['age_paciente'] ? $this->chamados[4]['age_paciente'] : "Nenhum Paciente Chamado")?></div>
            </div>
            <div>
                <div class="setor">Setor:</div> <div id="set-5"><?=$this->chamados[4]['set_nome']?></div>
            </div>
        </div> -->
         
    </div>
    <div id="proximo">        
        <div id="pac-1">
            <div id="cor-1" style="width: 60px;height:60px; background-color: <?=($this->proximo['cor']=="") ? "": $this->proximo['cor'] ?> ; 
                 float: left; margin-right:5px;"></div>
            <div id="paciente" style="margin-left:10px; font-size: 55px;"><?=($this->proximo['age_paciente'] ? $this->proximo['age_paciente'] : "Nenhum Paciente Chamado")?></div>       
        </div>
        <div>
           <div id="set-pac1" style="font-size: 30px;color:#5FBAFF;left:65px;position: relative"><b><?=$this->proximo['set_nome']?></b></div>
        </div>
    </div>
</div>
</div>