<?php $this->dialog(); ?>
<?php $this->errorMsg(); ?>
<br />
<form method="post" action="<?=$this->url(array("action"=>"salvar-config-grupo-de-exames"))?>" id="form-configuracao">
    <input type="hidden" name="txg_codigo" value="<?=$this->dadosEdicao[0]->txg_codigo?>" />
    <input type="hidden" name="gruex_codigo" value="<?=$this->gruex_codigo?>" />
    <label style="width: 140px;">Procedimento:</label>
    <input type="text" name="proc_nome" id="proc_nome" onkeypress="buscaProcedimentosSus();" value="<?=$this->dadosEdicao[0]->proc_nome?>" />
    <input type="hidden" name="proc_codigo" id="proc_codigo" value="<?=$this->dadosEdicao[0]->proc_codigo?>" /><br />
    <label style="width: 140px;"> Grupo de Exames:</label>
    <select name="grupo_de_exames" id="grupo_de_exames" style="width: 196px;">
        <?php foreach ($this->grupoexame as $value) { ?>
                <option value="<?=$value->gruex_codigo?>" <?=$this->gruex_codigo == $value->gruex_codigo ? "selected='selected'" : ""; ?>>
                    <?=$value->gruex_descricao?>
                </option>
        <?php } ?>
    </select>
    <a href="#" class="ui-button novo" style="margin-left: 5px;" id="novo-grupo-de-exames">Novo</a><br />
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+S" style="margin-left: 145px;">Salvar</a>
</form>
<br /><br />
<form id="categoria-de-exames" method="post" action="<?=$this->url(array("action"=>"busca-configuracoes"))?>" >
    <label class="ui-corner-bl ui-corner-tr">Buscar:</label>
    <input size="50" class="focus ui-state-default" name="busca" value="" type="text">
    <label class="ui-corner-bl ui-corner-tr">Tipo de Busca:</label>
    <select name="tipo_busca">
        <option value="P">Procedimento</option>
        <option value="G">Grupo</option>
    </select>
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
</form>
<table class="sortable">
    <tr>
        <th>Código</th>
        <th>Grupo</th>
        <th>Código SUS - Procedimento</th>
        <th colspan="2">Ações</th>
    </tr>
    <?php if (count($this->dados)>0) { ?>
        <?php foreach($this->dados as $value) { ?>    
                <tr>
                    <td>
                        <?=$value->txg_codigo?>
                        <input type="hidden" name="ordem[]" value="<?=$value->txg_codigo?>" />
                    </td>
                    <td><?=$value->gruex_descricao?></td>
                    <td><?=($value->proc_codigo_sus != "" ? $value->proc_codigo_sus : "SEM CÓDIGO")." - ".$value->proc_nome?></td>
                    <td>
                        <a href="<?=$this->baseUrl();?>/laboratorio/grupo-de-exames/index/gruex_codigo/<?=$value->gruex_codigo?>/id/<?=$value->txg_codigo?>" class="editar" >
                            <img src="<?=$this->baseUrl();?>/public/images/icons/editar.png" alt="Editar Item" title="Editar Item">
                        </a>
                    </td>
                    <td>
                        <a href="<?=$this->baseUrl();?>/laboratorio/grupo-de-exames/excluir-configuracoes/gruex_codigo/<?=$value->gruex_codigo?>/id/<?=$value->txg_codigo?>">
                            <img src="<?=$this->baseUrl();?>/public/images/icons/excluir.png" alt="Excluir Item" title="Excluir Item">
                        </a>
                    </td>
                    
                </tr>
        <?php } ?>
    <?php } else { ?>
            <tr>
                <td colspan="4">Nenhuma configuração encontrada até o momento!</td>
            </tr>
    <?php } ?>
</table>
