<br />
<table>
    <tr>
        <th>Hipertensão Arterial Sistêmica</th>
        <th>Diabetes Mellitus</th> 
        <th>Obesidade</th>  
        <th>Depressão</th>                   
    </tr>
 <?php //die(var_dump($this->atendQtd))?> 
    <tr>
        <td style='text-align:center'><?=$this->atendQtd['HAS']?></td>
        <td style='text-align:center'><?=$this->atendQtd['DM']?></td>
        <td style='text-align:center'><?=$this->atendQtd['Obes']?></td>
        <td style='text-align:center'><?=$this->atendQtd['Dep']?></td> 
    </tr>   

</table>