<div class="space"></div>
<table class="grid ui-widget ui-widget-content ui-corner-all" width="100%" id="grade">
	<?php echo $this->thTabelaData($this->data_inicial, $this->data_final); ?>
	<?php foreach($this->vagas as $coni_codigo => $dias): // para cada exame ?>
	<tr>
		<th class="ui-widget-header" style="font-size: 10px; min-width: 200px">
			<?=trim($this->nomeProcs[$coni_codigo]);?>
		</th>
		<?php $index = 0; foreach($dias as $dia => $vagas): // para cada dia ?>
		<?php if(!$index): ?>
		<th style="width: 20px" class="gram_mes"
			data-dia="<?=$dia;?>"
			data-padrao="<?=$vagas->coni_cota_mes;?>"
			data-agendados="<?=$vagas->agendado_mes;?>">
			<?#php echo "<pre>" . print_r($vagas, 1) . "</pre>";exit;?>
			<input type="text" style="width:60px;font-size: 10px;" name="mes[<?=$coni_codigo;?>][<?=  substr($dia, 0, -3);?>-01]" value="<?=($vagas->limite_mes==-1?"":$vagas->limite_mes);?>" id="coni_<?=$coni_codigo;?>" data-coni="<?=$coni_codigo;?>" class="alteracao" />
			<input type="hidden" style="width:60px;font-size: 10px;" name="mes_original[<?=$coni_codigo;?>][<?=  substr($dia, 0, -3);?>-01]" value="<?=($vagas->limite_mes==-1?"":$vagas->limite_mes);?>" />
		</th>
		<?php endif; ?>
                <td class="calend c agenda_<?=$vagas->limite_dia==$vagas->coni_cota_dia?"sem":"com";?>_alteracao dia"
			data-dia="<?=$dia;?>" 
			data-coni="<?=$coni_codigo;?>" 
			data-padrao="<?=$vagas->coni_cota_dia;?>" 
			data-agendados="<?=$vagas->agendado_dia;?>" 
			data-index="<?=(++$index);?>"
                        data-atual="<?=$vagas->limite_dia;?>"
                        data-conv="<?//=(++$index);?>">
			<input value="<?=($vagas->limite_dia<0?"":$vagas->limite_dia);?>" name="coni[<?=$coni_codigo;?>][<?=$dia;?>]" class="alteracao"/>
			<input value="<?=($vagas->limite_dia<0?"":$vagas->limite_dia);?>" name="original[<?=$coni_codigo;?>][<?=$dia;?>]" type="hidden" />
		</td>
		<?php endforeach; ?>
	</tr>
	<?php endforeach; ?>
</table>
<div class="space"></div>
<div id="horario">
</div>
<br />
<div id="legenda">
    <div class="agenda_com_alteracao"></div> Com alteração
    <div class="agenda_alterando"></div> Alterações a serem salvas
    <div class="border"></div> Horário não cadastrado
    <div class="marcada"></div> Selecionada
</div>
