<div class="space"></div>
<table class="grid ui-widget ui-widget-content ui-corner-all" width="100%" id="grade">
	<?php //echo $this->thTabelaData($this->data_inicial, $this->data_final); ?>
	<tr>
            <?php $i=0;
            foreach($this->distribuicao as  $hora => $vagas_pacientes): // para cada horario ?>
                <?php
                    $vagas_pacientes = explode("|",$vagas_pacientes);
                    $vagas = $vagas_pacientes[0];
                    $pacientes = $vagas_pacientes[1];
                    $hora_junto = explode(":",$hora);
                    $hora_junto = $hora_junto[0]."_".$hora_junto[1];
                    if($i == 18){
                        echo "</tr><tr>";
                        $i=0;
                    }
                ?>
                <td class="c <?=($vagas>0?"sem-vaga hora":"com-vaga hora_per");?>" pac="teste" hora="<?=$hora_junto;?>" data-hora="<?=$hora_junto;?>" data-coni="<?=$hora_junto;?>" data-paciente="<?=$pacientes;?>"  data-index="a"><?=$hora;?></td>
            <?php $i++;endforeach; ?>
	</tr>
</table>
