<? if ($this->itens && $this->itens->count()){ ?>
	<table class="ui-widget ui-widget-content ui-corner-all" width="100%">
		<tr class="ui-widget-header">
			<th width="120">Data</th>
			<th>Profissional</th>
			<th width="220">Especialidade</th>
            <th>Horário</th>
            <th>Tipo de Atendimento</th>
			<th width="120">Unidade</th>
            <th>Opções</th>
		</tr>
        <?
        $i = 0; 
            foreach ($this->itens as $item){ ?>
			<tr>
                <td class="ui-widget-content c"><?= $this->data($item->age_data); ?></td>
                <td class="ui-widget-content"><?= $this->escape($item->usr_nome); ?></td>
                <td class="ui-widget-content"><?= $this->escape($item->esp_nome); ?></td>
                <td class="ui-widget-content"><?= $this->escape($item->age_horario); ?></td>
                <td class="ui-widget-content"><?= $this->escape($item->tat_tipo); ?></td>
                <td class="ui-widget-content c" width="200"><?= $this->escape($item->uni_desc); ?></td>
                <td class="ui-widget-content c">
                    <? if($item->age_tipo != "ES"){ ?>
                        <? $action = $this->url(array("modulo" => "agendamento", "module" => "agendamento","controller" => "agendamento", "action" => "imprimir","age" => $item->age_codigo));?>
                        <a href="<?=$action?>" class="popup" rel="630x540">
                            <img src='<?=$this->baseUrl('/public/images/icons/printer.png');?>' alt='Imprimir Requisição' title='Imprimir Requisição' />
                        </a>
                    <? } ?>
                </td>
			</tr>
		<?php $i++; 
            } ?>   
	</table>
<? } else {
$i = 1;?>
	<em>Nenhum histórico encontrado.</em>
<? } ?>
<input type="hidden" name="sem-tamanho" id="sem-tamanho" value="<?=$i;?>">