<?php $this->dialog(); ?>
<?php echo $this->action('form','buscar');?>

<?php
$i=0;
if($this->itens && $this->itens->count()):?>
    <table class='grid ui-widget ui-widget-content ui-corner-all' width='100%'>
    <tr class='ui-widget-header'>
           <th>Cód</th>
           <th>Descrição</th>
           <th>CNPJ</th>
           <th>Endereço</th>  
           <th>Opções</th>
       </tr>
    <?foreach($this->itens as $item):?>     
            <tr>
                <td class='ui-state-default' width='50'><?=$this->escape($item->fab_codigo);?></td>
                <td class='ui-state-default c' width='150'><?=$this->escape($item->fab_descricao);?> </td>
                <td class='ui-state-default c' width='120'><?=$this->escape($item->fab_cnpj);?></td>
                <td class='ui-state-default c' width='150'><?=$this->escape($item->fab_endereco);?></td>
                <td class='ui-state-default c' width='50'>
                    <input type="hidden" name="id" id="id" value="<?=$item->fab_codigo?>">
                    <a href='<?=$this->url(array("module"=>"default", 'controller'=>'fabricante','action'=>'editar','id'=>$item->fab_codigo), NULL, TRUE);?>' class='editar'><img src='<?=$this->baseUrl('/public/images/icons/editar.png');?>' alt='Editar Itens' title='Editar Itens' /></a>
                    <a href=#' id='excluir' onclick="excluir(<?=$item->fab_codigo?>)"><img src='<?=$this->baseUrl('/public/images/icons/excluir.png');?>' alt='Excluir' title='Excluir' /></a>		
                </td>
            </tr>
<?php endforeach; ?>
</table>
<?php else:?>
        <em>Nenhum item encontrado</em>
<?php endif;?>
