<div class="abas">
    <ul class="tabs">
        <li><a href="#tabs2-1">Benefícios Concedidos</a></li>
        <li><a href="#tabs2-2">Listagem dos Benefícios Concedidos</a></li>
    </ul>
    <div id="tabs2-1">
        <?= $this->action("form-beneficios-concedidos", "atendimento-simplificado","atendimento"); ?>
    </div>    

    <div id="tabs2-2">
        <?= $this->action("lista-beneficios-concedidos", "atendimento-simplificado","atendimento"); ?>
    </div>
    
</div>