<?php $this->dialog(); ?>
<?php $this->errorMsg(); ?>


<br /><?php
if ($this->codigoAtendimento) {?>
  
  <script>
      window.open('<?=$this->url(array("action" =>"imprimir-beneficios-eventuais",'codigoAtendimento'=>$this->codigoAtendimento));?>', '', '', true);
  </script>  
  
  <?}

  ?>

<?
if($_GET['alert']){
    if($_GET['alert'] == "sucessexcluir"){ ?>
    <script>
        Swal.fire({
            title: 'Sucesso!',
            text: 'Sucesso ao excluir Ficha RAAS!',
            type: 'success',
            confirmButtonText: 'Ok'
        })
    </script>
    <? } else if($_GET['alert'] == "error"){?>
        <script>
            Swal.fire({
                title: 'Erro!',
                text: 'Erro ao cadastrar Unidade de ESF!',
                type: 'error',
                confirmButtonText: 'Ok'
            })
        </script>
    <? } else if($_GET['alert'] == "errorpaciente"){?>
        <script>
            Swal.fire({
                title: 'Erro!',
                text: 'Paciente não informado!',
                type: 'error',
                confirmButtonText: 'Ok'
            })
        </script>
    <?}else if($_GET['alert'] == "sucesseditar"){?>
        <script>
            Swal.fire({
                title: 'Sucesso!',
                text: 'Sucesso ao Editar Ficha!',
                type: 'success',
                confirmButtonText: 'Ok'
            })
        </script>
    <?}else if($_GET['alert'] == "errorcid"){?>
        <script>
            Swal.fire({
                title: 'Erro!!',
                text: 'Necessário cadastrar 1 CID!',
                type: 'error',
                confirmButtonText: 'Ok'
            })
        </script>
    <?}
}
?>



  <script>
    function abrirCarterinhaNova() {
        var paciente = '<?php echo $this->usu_codigo;?>';

        if(paciente == ""){
            paciente = $("#usu_codigo").val();
        }

        url = "/WebSocialSaude/zf/vacina/imprimir-carteirinha/usu/" + paciente;
        window.open(url, null, "height=620,width=650,status=yes,toolbar=no,menubar=no,location=no,scrollbars=yes");
    }

</script>

<link rel="stylesheet" href="/WebSocialSaude/zf/public/css/atendimento/atendimento-simplificado/form-procedimento.css">
<script src="/WebSocialSaude/zf/public/js/atendimento/atendimento-simplificado/form-ficha-raas.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<?

if($_GET['imprimir'] > 0){ 
    $codigoAtendimento = $_GET['imprimir']?>
    
    <script>    
        window.open('<?=$this->url(array("action" =>"imprimir-beneficios-eventuais",'codigoAtendimento'=>$codigoAtendimento));?>', '', '', true);
    </script>

    <?}
    ?>


<form name="busca" method="post" action="<?=$this->url(array("action" => "lista-ficha-raas"))?>">
    <label style= "padding: 5px;padding-right: 0px; text-align: left; font-size: 14px; width: 150px;height: 20px" class="ui-corner-bl ui-corner-tr">Buscar:</label>

    <input size="50" class="focus ui-state-default" name="busca" value="" type="text" style="width: 300px; height: 20px; padding-top: 2px; padding-bottom: 5px">

    <label style= "padding: 5px;padding-right: 0px; text-align: left; font-size: 14px; width: 150px; height: 20px" class="ui-corner-bl ui-corner-tr">Tipo de Movimento:</label>
    
    <select style="width: 302px;    margin-bottom: 10px !important;height: 30px !important;border-radius: 5px !important;    border: 1px solid #c5dbec;background: #dfeffc url(images/ui-bg_glass_85_dfeffc_1x400.png) 50% 50% repeat-x;font-weight: bold;color: #2e6e9e;" name="tipo_busca">
        <option value="P">Paciente</option>
    </select>
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
</form>
<br/>
<table>
    <tr>
        <th>Prontuario</th>
        <th>Data</th>
        <th>Paciente</th>
        <th>Opções</th>
    </tr>
    <? if (count($this->dados) > 0) { ?>
        <div id="finaldialog" name="finaldialog" hidden>
                    <p>
                    <label>Motivo da Saida:</label>
                    <select id="motivosaida" name="motivosaida" value="">
                        <optgroup label="POR ALTA:">
                            <option value="11">Alta Curado</option>
                            <option value="12">Alta Melhorado</option>
                            <option value="13">Alta da Puérpera e permanência do recém-nascido</option>
                            <option value="14">Alta a pedido</option>
                            <option value="15">Alta com previsão de retorno para acompanhamento do paciente</option>
                            <option value="16">Alta por Evasão</option>
                            <option value="17">Alta da Puérpera e recém-nascido</option>
                            <option value="18">Alta por Outros motivos</option>
                        </optgroup>

                        <optgroup label="POR PERMANENCIA:">
                            <option value="21">Por características próprias da doença</option>
                            <option value="22">Por Intercorrência</option>
                            <option value="23">Por impossibilidade sócio-familiar</option>
                            <option value="24">Por Processo de doação de órgãos, tecidos e células - doador vivo</option>
                            <option value="25">Por Processo de doação de órgãos, tecidos e células - doador morto</option>
                            <option value="26">Por mudança de Procedimento</option>
                            <option value="27">Por reoperação</option>
                            <option value="28">Outros motivos</option>
                        </optgroup>

                        <optgroup label="POR TRANSFERENCIA:">
                                <option value="31">Transferido para outro estabelecimento</option>
                        </optgroup>
                        <optgroup label="POR OBITO:------------"></option>
                            <option value="41">Com declaração de óbito fornecida pelo médico assistente</option>
                            <option value="42">Com declaração de Óbito fornecida pelo Instituto Médico Legal - IML</option>
                            <option value="43">Com declaração de Óbito fornecida pelo Serviço de Verificação de Óbito - SVO.</option>
                        </optgroup>
                        <optgroup label="POR OUTROS MOTIVOS:">
                            <option value="51">Encerramento Administrativo</option>
                        </optgroup>
                    </select>
                </div>
        <? foreach ($this->dados as $item) { ?>
        <tr>
            <td><?=$item->ras_prontuario?></td>
            <td><?=$this->data($item->ras_val_ini,Zend_Date::DATE_MEDIUM)?></td>
            <td><?=$item->ras_paciente?></td>
            <td>
                <?php //echo "<pre>";print_r($item->ras_motivosaida);die(); ?>
                <?php if($item->ras_motivosaida==""){?>
                <a onclick="recebeProntuario(<?=$item->ras_prontuario?>)"href="adicionar-acoes-raas?prontuario=<?=$item->ras_prontuario?>"> 
                    <img src="<?=$this->baseUrl("public/images/icons/add.png")?>" title='Adicionar' alt='Clique aqui para adicionar' style='cursor: pointer'  />
                </a> 
                <?}?>
                <a href="<?=$this->url(array("action"=>"lista-acoes-raas","module"=>"atendimento","controller"=>"atendimento-simplificado","prontuario"=>"$item->ras_prontuario"), NULL, TRUE);?>">
                    <img src="<?=$this->baseUrl("public/images/icons/historico.png")?>" title='Listar' alt='Clique aqui para listar' style='cursor: pointer'  />
                </a>

                <?php if($item->ras_motivosaida==""){?>
                <a href="<?=$this->url(array("action"=>"index-ficha-raas","module"=>"atendimento","controller"=>"atendimento-simplificado","ras_prontuario"=>"$item->ras_prontuario"), NULL, TRUE);?>">
                    <img src="<?=$this->baseUrl("public/images/icons/editar.png")?>" title='Editar' alt='Clique aqui para editar' style='cursor: pointer' />
                </a>
                <?}?>

                <?php if($item->ras_motivosaida==""){?>
                 <a href="#" > 
                    <img src="<?=$this->baseUrl("public/images/icons/finalizar.png")?>" title='Finalizar' alt='Clique aqui para finalizar' style='cursor: pointer' onclick="meuDialog(<?=$item->ras_prontuario?>);"  />
                </a>  
                <?}
                 ?>

                <?php //NOVA FUNÇÃO EDITAR FIM #96579 ?>
                  <a href="<?=$this->url(array("action"=>"excluir-ficha-raas","module"=>"atendimento","controller"=>"atendimento-simplificado","ras_prontuario"=>"$item->ras_prontuario"), NULL, TRUE);?>" > 
                    <img src="<?=$this->baseUrl("public/images/icons/excluir.png")?>" title='Excluir' alt='Clique aqui para excluir' style='cursor: pointer' />
                </a> 


            </td>
        </tr>
    <?  } ?>
<?  } else { ?>
        <tr>
            <td colspan="4">Nenhum atendimento realizado até o momento!</td>
        </tr>
<?  } ?>
</table>