<?php $this->dialog(); ?>
<?php $this->errorMsg(); ?>
<br />
<form name="busca" method="post" action="#tabs2-2">
    <label class="ui-corner-bl ui-corner-tr">Buscar:</label>
    <input size="50" class="focus ui-state-default" name="busca" value="" type="text">
    <label class="ui-corner-bl ui-corner-tr">Tipo de Movimento:</label>
    <select name="tipo_busca">
        <option value="P">Paciente</option>
        <option value="D">Data</option>
        <option value="U">Profissional</option>
    </select>
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
</form>
<br />
<table>
    <tr>
        <th>Data</th>
        <th>Paciente</th>
        <th>Profissional</th>
        <th>Opções</th>
    </tr>
    <? if (count($this->dados) > 0) { ?>
        <? foreach ($this->dados as $item) { ?>
        <tr>
            <td><?=$this->data($item->ate_data,Zend_Date::DATE_MEDIUM)?></td>
            <td><?=$item->usu_nome?></td>
            <td><?=$item->usr_nome?></td>
            <td>
                <?php //NOVA FUNÇÃO EDITAR #96579 ?>
                <a href="<?=$this->url(array("action"=>"index","module"=>"atendimento","controller"=>"atendimento-simplificado","ate_codigo"=>"$item->ate_codigo","age_codigo"=>$item->age_codigo), NULL, TRUE);?>"> 
                    <img src="<?=$this->baseUrl("public/images/icons/editar.png")?>" title='Editar' alt='Clique aqui para editar' style='cursor: pointer' onclick="validaEditar()" />
                </a> 
                <?php //NOVA FUNÇÃO EDITAR FIM #96579 ?>
                <a href="<?=$this->url(array("action"=>"excluir-atendimento-simplificado","module"=>"atendimento","controller"=>"atendimento-simplificado","ate_codigo"=>"$item->ate_codigo","age_codigo"=>$item->age_codigo, "ate_tipo"=> 'A'), NULL, TRUE);?>" > 
                    <img src="<?=$this->baseUrl("public/images/icons/excluir.png")?>" title='Excluir Horários' alt='Clique aqui para excluir os horários do dia' style='cursor: pointer' />
                </a>                            
            </td>
        </tr>
    <?  } ?>
<?  } else { ?>
        <tr>
            <td colspan="4">Nenhum atendimento realizado até o momento!</td>
        </tr>
<?  } ?>
</table>