<link href='<?=$this->baseUrl('/public/css/prontuario/receita-medica/imprimir-anvisa.css')?>' rel='stylesheet' type='text/css'> </link>
<link href='<?=$this->baseUrl('/public/css/print.css')?>' rel='stylesheet' type='text/css'> </link>
<head>
    <script>
        window.print();
    </script>
</head>
<body>
<div style="clear:both;"></div>
<?for($i=1;$i<=2;$i++):?>
    <div class="div_cabecalho">
        <div class="identificacao_estabelecimento">
            <div class="brasao">
                <img src="<?=$this->baseUrl("/public/images/brasao.jpg");?>" width="80" height="70"/>
            </div>
            <div class="dados_sec">
                <br/>
                <b><?=$this->sec[nome_secretaria]?></b><br/>
                C.N.P.J.:<?=$this->sec[cnpj_secretaria]?><br/>
                <b><?=$this->usr->uni_desc;?></b>
            </div>
            <div class="cod_bar">
                <div id="img_bar">
                    <img src="<?=$this->baseUrl()?>/public/images/codigo_barras.php?codigo=<?=$this->dados->codigo;?>&lw=1&hi=18" alt="Código de Barras: <?=$this->dados->codigo;?>" title="Código de Barras: <?=$this->dados->codigo;?>" width="110" />
                </div>
            </div>
        </div>
        <div id="titulo_impressao"><b>RECEITUÁRIO CONTROLE ESPECIAL</b></div>
        <div class="dados_titulo">
            IDENTIFICAÇÃO DO EMITENTE
        </div>
        <div class="identificacao_formulario">
            <div class="dados_form_dir">
                Nome Completo:<br/> 
                CRM:<br/>
                End.Completo:<br/>
                Telefone:<BR/>
                Cidade:
            </div>
            <div class="dados_form_esq_anvisa">
                <b> <?=$this->dados->usr_nome?><br/></b> 
                <b> <?=$this->dados->usr_num_conselho?></b><br/>
                <b> <?=($this->usr->uni_endereco != "" ? $this->usr->uni_endereco : "NÃO INFORMADO")?>, <?=($this->usr->uni_numero != "" ? $this->usr->uni_numero : "-")?>, <?=($this->usr->uni_bairro != "" ? $this->usr->uni_bairro : "-")?></b><br/>
                <b> <?=$this->usr->cnes_telefone?></b><BR/>
                <b> <?=$this->usr->cid_nome?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UF:<?=$this->usr->uf_sigla?></b>
            </div>
            <div class="dados_form_dir2">
                Dt.Emissão: <b><?=date("d/m/Y");?></b>
                <br/>
                <?if($i == 1){
                   echo $i."ª Via Farmácia";
                }else{
                   echo $i."ª Via Paciente";
                }
?>
            </div>
        </div>

        <div class="identificacao_responsavel_anvisa">
           <div class="dados_form_dir">
                Paciente:<br/> 
                Endereco:<br/>
            </div>
            <div class="dados_form_esq">
                <table>
                    <b><?=$this->dados->usu_prontuario?> &nbsp;&nbsp;&nbsp; <?=$this->dados->usu_nome?><br/></b> 
                    <b><?=($this->dados->rua_nome == "" ? "SEM ENDEREÇO" : $this->dados->rua_nome.",")?> <?=$this->dados->dom_numero?> - <?=$this->dados->cid_nome?></b><br/>
                </table>
                
            </div>
        </div>

        <div class="identificacao_responsavel_receb">
            <div class="dados_resp_receb">
                <b>Prescrição</b>
            </div>
            <div class="medicamentos_prescricao">
                <?php if ($this->dados->itens): ?>
		<?php foreach ($this->dados->itens as $item): ?>
			<div class="medItem">
                                
                                <!-- #105247 NOVOS ITENS PRODUTO E DESCRIÇÃO -->
                            
                                <div class="medTitulo">
                                    <?php
                                    if ($this->tipo == "externo") {
                                            echo $item->irec_produto . " / " . $item->desc_produto;
                                            echo $item->pro_nome;
                                    }
                                    ?>
				</div>
                            
                                <!-- #105247 FIM NOVOS ITENS -->
                            
				<div class="medTitulo">
					<?php
                                        echo $this->escape($item->pro_nome);
					?>
				</div>
				<div class="medQtd"><?= $item->irec_quantidade; ?></div>	
				<div class="clear"></div>
				<div class="medUso"><?= $item->irec_recomendacao; ?></div>
			</div>
		<?php endforeach; ?>	 		
            <?php endif; ?>
            </div>
            <div class="assinatura_resp">
               --------------------------------------------------------------<br/>
                    <?=$this->dados_usr->usr_nome?><br/>
                    <?=$this->dados_usr->con_descricao.": ".$this->dados_usr->usr_num_conselho. " - ". $this->dados_usr->cnes_sigla_est?>
            </div>
        </div>
        
        <div class="identificacoes">
           <div class="identificacao_comprador">
               <div class="titulo_identificacao_comprador">  
                   IDENTIFICAÇÃO DO COMPRADOR
               </div>
               <div class="identificacao_comprador_dados">  
                   Nome:&nbsp; _____________________<br/>
                   Ident:__________Org.Emissor: __<br/>
                   End:  _______________________<br/>
                   Cidade: ___________Estado: ___<br/>
                   Fone: ______________________<br/>
               </div>
            </div>
            <div class="identificacao_fornecedor">
                <div class="titulo_identificacao_fornecedor">  
                   IDENTIFICAÇÃO DO FORNECEDOR  
               </div>
                <div class="identificacao_fornecedor_dados">
                    <br/>
                   ______________________________<br/>
                   Assinatura do Farmacêutico<br/>
                   <br/>
                   Data:___/___/___
               </div>
            </div>
        </div>
        <div id="endereco">
           
             <?=$this->usr->uni_endereco?>, CNPJ:<?=$this->usr->uni_cnpj?>, FONE:<?=$this->usr->cnes_telefone?>
        </div>
        
    </div>
<?  endfor;?>
</body>

