<form id="relatorioProducaoDiaria" style="margin-top: -3%" method="post" action="<?= $this->url(array("action" => "visita-domiciliar")); ?>" target="_blank">
    <input name="tipo" id="tipo" type="hidden" value="<?=$this->action?>"/><br />


    <!-- <input name="tipo" id="tipo" type="hidden" value="<?=$this->action?>"/><br />
    <label>Profissional:</label>
    <input name="usr_nome" id="usr_nome" />
    <input name="usr_codigo" id="usr_codigo" type="hidden" /> -->
    
    
    <input name="tipo" id="tipo" type="hidden" value="<?=$this->action?>"/><br />
    <label>Unidade:</label>
    <input name="uni_desc" id="uni_desc" />
    <input name="uni_codigo" id="uni_codigo" type="hidden" />
        
	<div class="clear"></div>
	<div class="space"></div>
        
	<label>Data Inicial:</label>
	<input name="data_inicial" class="data" style="width: 80px"/><br />
	
	<label>Data Final:</label>
	<input name="data_final" class="data" style="width: 80px" /><br />

        <div class="clear"></div>
        <a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;" 
           title="Para melhor vizualização dos dados, selecione um filtro!" onclick=validarFiltrosRelatorioProducaoDiaria()>Gerar Relatório</a>	
</form>