<form name="busca" method="POST" action="<?=$this->baseUrl();?>/programasfederais/grupo-atividade-coletiva/buscar" id="form-busca">
    <a href="<?=$this->baseUrl();?>/programasfederais/grupo-atividade-coletiva/form" class="ui-button novo ui-corner-bl ui-corner-tr" data-atalho="ALT+N">Novo</a>
    <label style="width: 70px" class="ui-corner-bl ui-corner-tr">Buscar:</label>
    <input size="50" class="focus ui-state-default" name="busca" value="" type="text">
    <a href="#" class="ui-button salvar ui-corner-bl ui-corner-tr" data-atalho="CTRL+F">Buscar</a>
    <a class="ui-button voltar ui-corner-bl ui-corner-tr" onclick="parent.location.reload(true)">Voltar</a>
</form>
<table class='grid ui-widget ui-widget-content ui-corner-all' width='100%'>
    <tr class='ui-widget-header'>
        <th width="55%">Nome</th>
        <th width="15%">Qtde. Part.</th>
        <th width="15%">Ativo</th>
        <th width="15%">Opções</th>
    </tr>
	<?php
	if(count($this->dados)>0) {
		foreach($this->dados as $item) { ?>
            <tr>
                <td class='ui-state-default'><?= $item->gac_descricao?></td>
                <td class='ui-state-default' align="center"><?= $item->qtd_part?></td>
                <td class='ui-state-default' align="center"><?= ($item->gac_status ? 'Sim' : 'Não')?></td>
                <td class='ui-state-default c' width='80'>
                    <a href='<?=$this->url(array("action"=>"form", "module"=>"programasfederais", "controller"=>"grupo-atividade-coletiva","id"=>$item->gac_codigo), NULL, TRUE);?>' class='editar'>
                        <img src='<?=$this->baseUrl('/public/images/icons/editar.png');?>' alt='Editar Grupo' title='Editar Grupo' />
                    </a>
                    <? if($item->gac_status): ?>
                    <a type="button" href="#" onclick="desativarGrupo('<?= $item->gac_codigo?>')" class='editar'>
                        <img src='<?=$this->baseUrl('/public/images/icons/excluir.png');?>' alt='Desativar Grupo' title='Desativar Grupo' />
                    </a>
                    <?php else : ?>
                        <a href='<?=$this->url(array("action"=>"ativar", "module"=>"programasfederais", "controller"=>"grupo-atividade-coletiva","id"=>$item->gac_codigo), NULL, TRUE);?>' class='editar'>
                            <img src='<?=$this->baseUrl('/public/images/icons/accept.png');?>' alt='Ativar Grupo' title='Ativar Grupo' />
                        </a>
                    <?php endif;?>
                </td>
            </tr>
			<?php
		} ?>
		<?php
	} else {?>
        <td colspan="6">Nenhum item encontrado</td>
		<?php
	} ?>
</table>