<form method="post"  action="<?=$this->url(array("action"=>"rel-procedimento-por-mes-por-profissional"));?>" target="_blank">
	<input name="filtro" id="filtro" type="hidden" value="s" />

	<input name="tipo" id="tipo" type="hidden" value="<?=$this->action?>"/><br />
	<label>Unidade:</label>
	<input name="uni_desc" id="uni_desc"  class="focus"/>
	<input name="uni_codigo" id="uni_codigo" type="hidden" /><br />
	<label>Profissional:</label>
	<input name="usr_nome" id="usr_nome"  class="focus"/>
	<input name="usr_codigo" id="usr_codigo" type="hidden" /><br />
        
	<label>Data inicial:</label>
	<input name="data_inicial" id="data_inicial" class="data" style="width: 80px"/><br />
	<label>Data final:</label>
	<input name="data_final" id="data_final" class="data" style="width: 80px" /><br />

	<input name="tipo" id="tipo" type="hidden" value="<?=$this->action?>"/>
	<label>Procedimento:</label>
	<input name="proc_nome" id="proc_nome"/>
	<input name="proc_codigo" id="proc_codigo" type="hidden" /><br />

	<div class="clear"></div>
	<a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;" class="popup" rel="600x500">Gerar Relatório</a>
</form>