  <br />
<link href='../../../estilo.css' rel='stylesheet' type='text/css'></style>
<table class="lista">
  <?php 
    //die(var_dump($this->profs));
    $total = 0;
    foreach($this->profs as $prof){
      //die(var_dump($prof->usr_nome));
      ?>
      <tr>
        <th colspan="6" style="font-size: 16px; background-color: #CDC9C9;" ><?= $prof->usr_nome?>(<?= $prof->usr_codigo?>)</th>
     </tr>
      <?php
      if($this->select_relatorio == 0) {
    ?>
 <tr>
      <th style="font-weight: bold; font-size: 10px; text-align: left" width="20%">PACIENTE</th>
      <th style="font-weight: bold; font-size: 10px; text-align: left" width="20%">GRUPO</th>
      <th style="font-weight: bold; font-size: 10px; text-align: left" width="20%">CLASSIFICAÇÃO</th>
      <th style="font-weight: bold; font-size: 10px; text-align: left" width="20%">UNIDADE RESPONSÁVEL</th>
      <th style="font-weight: bold; font-size: 10px; text-align: left" width="20%">DATA DO ÚLTIMO INTERNAMENTO</th>
      <th style="font-weight: bold; font-size: 10px; text-align: left" width="20%">RESPONSÁVEL</th>
      
</tr>
<tr></tr>
  <?php
  if($this->select_grupo == 0 || $this->select_grupo == 1 || $this->select_grupo == 3) { 
    foreach ($this->dadosG1 as $dado) {
      foreach ($dado as $d) {
        if($d["usr_codigo"] == $prof->usr_codigo){
          $total = $total + 1;
  ?>
 <tr></tr>
 <tr>
      <td><?= $d["usu_nome"]?></td>
      <td><?= $d["er_grupo"]?></td>
      <td><?= $d["er_desc"]?></td>
      <td><?= $d["uni_desc"]?></td>
      <td><?= $this->data($d["ate_data"])?></td>
      <?php if($d["age"] <= 1){
        ?>
      <td><?= $d["usu_mae"]?></td>
      <?php
      } ?>
</tr>
    <p></p>
    <p></p>
        <?php
            }   
          }
        }
      }
  if($this->select_grupo == 0 || $this->select_grupo == 2 || $this->select_grupo == 3) { 
    foreach ($this->dadosG2 as $dado) {
      foreach ($dado as $d) {
        if($d["usr_codigo"] == $prof->usr_codigo){
      $total = $total + 1;
    ?>
 <tr></tr>
 <tr>
      <td><?= $d["usu_nome"]?></td>
      <td><?= $d["er_grupo"]?></td>
      <td><?= $d["er_desc"]?></td>
      <td><?= $d["uni_desc"]?></td>
      <td><?= $this->data($d["ate_data"])?></td>
      <?php if($d["age"] <= 1){
        ?>
      <td><?= $d["usu_mae"]?></td>
      <?php
      } ?>
</tr>
    <p></p>
    <p></p>
        <?php  
            } 
          }
        }
      }


          } else {
            $total = 0;
            $t_g1 = 0;
            $t_g2 = 0;
            ?>
        <tr>
            <td style="font-weight: bold; font-size: 10px" width="50%">QUANTIDADE DE INTERNAMENTOS NO GRUPO 1</td>
            <td style="font-weight: bold; font-size: 10px" width="50%">QUANTIDADE DE INTERNAMENTOS NO GRUPO 2</td>
          
        </tr>
         <tr>
            <?php
              foreach ($this->pacientes as $key => $paciente) {
                if($paciente["er_grupo"] == 1){
                  $t_g1++;
                } else if ($paciente["er_grupo"] == 2) {
                  $t_g2++;
                }
                $total++;
              }
            ?>
              <td><?= $t_g1?></td>
              <td><?= $t_g2?></td>
        </tr>
        <?php
            }
          }
      ?>
      <td style="font-weight: bold; font-size: 10px">TOTAL: <?= $total?></td>
</table>
<br />