<br />
<table>
    <tr>
        <th>Primeiras Consultas Odontológicas</th>
        <th>Total de Atendimentos Conluídos</th>                  
    </tr>
 <?php // echo "<pre>".print_r($this->total,1)."aaaaaa";die();?> 
    <tr>
        <td style='text-align:center'><?=$this->primConsulta?>(<?=$this->primConsultaPerc?>%)</td>
        <td style='text-align:center'><?=$this->tratConcluido?>(<?=$this->tratConcluidoPerc?>%)</td> 
    </tr>   

</table>