<br />
<table>
    <tr>
        <th>Total Agendamentos atendidos</th>
        <th>Agendado</th>  
        <th>Demanda espontânea</th>            
    </tr>
 <?php // echo "<pre>".print_r($this->total,1)."aaaaaa";die();?> 
    <tr>
        <td style='text-align:center'><?=$this->total?></td>
        <td style='text-align:center'><?=$this->agenda?></td>   
        <td style='text-align:center'><?=$this->demanda?></td>
    </tr>   

</table>