<form method="post" action="<?=$this->url($this->action);?>" target="_blank">
	<label>Setor:</label>
	<input name="set_nome" id="set_nome" />
	<input name="set_codigo" id="set_codigo" type="hidden" /><br />
	
	<label>Data inicial:</label>
	<input name="data_inicial" class="data" style="width: 80px"/><br />
	
	<label>Data final:</label>
	<input name="data_final" class="data" style="width: 80px" /><br />
	<label>Somente psicotrópicos?</label>
	<input type="radio" name="psi" value="s" checked="checked"/>Sim
	<input type="radio" name="psi" value="n"/>Não<br />
	<div class="clear"></div>
	<a href="#" class="ui-button submit historico" data-atalho="CTRL+R" style="margin-left: 185px;">Gerar Relatório</a>
	
</form>