<form method="post" action="<?= $this->url(array("action" => "salvar")); ?>">
	<?php $this->errorMsg(); ?>
	    <input type="hidden"  name="fechaPopUp" value="<?=$this->fechaPopUp?>">
        <input type="hidden" id="proc_cadastrado_manualmente" name="proc_cadastrado_manualmente" value="TRUE" class="focus" />
        <input type="hidden" id="proc_codigo" name="proc_codigo" value="<?=$this->dados->proc_codigo?>">
	<label>Procedimento:</label>
	<input type="text" id="proc_nome" name="proc_nome" value="<?=$this->dados->proc_nome?>"class="focus" />
        <br/>
        <label>Valor do Procedimento <small>(R$)</small>:</label>
        <input type="text" id="proc_valor" name="proc_vlsa" value="<?=number_format($this->dados->proc_vlsa,2,",",".")?>" class="float" rel="5,2" style="width:80px;"/>
        <br/>
        <label>Idade Maxima:</label>
	<input type="text" id="proc_idade_maxima" name="proc_idade_maxima" value="<?=$this->dados->proc_idade_maxima?>" />
        <br/>
        <label>Idade Minima:</label>
	<input type="text" id="proc_idade_minima" name="proc_idade_minima" value="<?=$this->dados->proc_idade_minima?>" />
        <br/>
        <label>Sexo:</label>
	<?=$this->formSelect("proc_sexo_novo", $this->dados->proc_sexo_novo, null,array("I"=>"Indiferente","M"=>"Masculino","F"=>"Feminino"));?>
	<div class="space"></div>

	<a href="#" class="ui-button salvar-icon salvar-proc">Salvar</a>
	<a href="#" class="ui-button limpar">Limpar</a>
</form>